### ISSUE TITLE
Integration-tests bugs

### ISSUE THREAD

**Issue by KoangHoYeom** [web3j/web3j#1007]
##  Steps To Reproduce
_Describe the exact steps or scenario to reproduce the issue._

1. Run the testContarct method of the [HumanStandardTokenIT](https://github.com/web3j/web3j/blob/master/integration-tests/src/test/java/org/web3j/protocol/scenarios/HumanStandardTokenIT.java) Class
2. I knew that HumanStandardToken.bin is missing. So it is taken from the codgen module.
3. The next step

I faced NullPointException.

### Expected behavior

Test Clear

### Actual behavior
NullPointException

## Environment

- Web3j version
- JDK 8
- MAC 10.14.6

## Additional context

I think that response message, `{"jsonrpc": "2.0", "id": 1, "error": {"code":-32000, "message": "invalid sender"}}` is the cause but I don't know how to fix it .

```
18:15:15.859 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
18:15:15.863 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
18:15:15.863 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 124
18:15:15.865 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
18:15:15.865 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0x3f17f1962b36e491b30a40b2405849e597ba5fb5","latest"],"id":0}
18:15:15.866 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> END POST (124-byte body)
18:15:15.999 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (133ms)
18:15:16.000 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
18:15:16.001 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Vary: Origin
18:15:16.001 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Date: Wed, 21 Aug 2019 09:15:15 GMT
18:15:16.001 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 40
18:15:16.002 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
18:15:16.002 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":0,"result":"0x0"}

18:15:16.002 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (40-byte body)
url : /solidity/contracts/build/HumanStandardToken.bin
url : file:/Users/kwanghoyeom/dev/spring/workspace/workplace/web3j/web3j/integration-tests/build/classes/java/test/
url : file:/Users/kwanghoyeom/dev/spring/workspace/workplace/web3j/web3j/integration-tests/build/resources/test/solidity/contracts/build/HumanStandardToken.bin
18:15:16.573 [Test worker] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
18:15:16.573 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
18:15:16.573 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 5708
18:15:16.573 [Test worker] DEBUG org.web3j.protocol.http.HttpService - 
18:15:16.574 [Test worker] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf90afe8085051f4d5c0083419ce08080b90aab60c0604052600460808190527f48302e310000000000000000000000000000000000000000000000000000000060a090815261003e91600691906100d0565b5034801561004b57600080fd5b506040516109ab3803806109ab8339810160409081528151602080840151838501516060860151336000908152600185529586208590559484905590850180519395909491939101916100a3916003918601906100d0565b506004805460ff191660ff841617905580516100c69060059060208401906100d0565b505050505061016b565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061011157805160ff191683800117855561013e565b8280016001018555821561013e579182015b8281111561013e578251825591602001919060010190610123565b5061014a92915061014e565b5090565b61016891905b8082111561014a5760008155600101610154565b90565b6108318061017a6000396000f3006080604052600436106100955763ffffffff60e060020a60003504166306fdde0381146100a7578063095ea7b31461013157806318160ddd1461016957806323b872dd14610190578063313ce567146101ba57806354fd4d50146101e557806370a08231146101fa57806395d89b411461021b578063a9059cbb14610230578063cae9ca5114610254578063dd62ed3e146102bd575b3480156100a157600080fd5b50600080fd5b3480156100b357600080fd5b506100bc6102e4565b6040805160208082528351818301528351919283929083019185019080838360005b838110156100f65781810151838201526020016100de565b50505050905090810190601f1680156101235780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34801561013d57600080fd5b50610155600160a060020a0360043516602435610372565b604080519115158252519081900360200190f35b34801561017557600080fd5b5061017e6103d9565b60408051918252519081900360200190f35b34801561019c57600080fd5b50610155600160a060020a03600435811690602435166044356103df565b3480156101c657600080fd5b506101cf6104cc565b6040805160ff9092168252519081900360200190f35b3480156101f157600080fd5b506100bc6104d5565b34801561020657600080fd5b5061017e600160a060020a0360043516610530565b34801561022757600080fd5b506100bc61054b565b34801561023c57600080fd5b50610155600160a060020a03600435166024356105a6565b34801561026057600080fd5b50604080516020600460443581810135601f8101849004840285018401909552848452610155948235600160a060020a031694602480359536959460649492019190819084018382808284375094975061063f9650505050505050565b3480156102c957600080fd5b5061017e600160a060020a03600435811690602435166107da565b6003805460408051602060026001851615610100026000190190941693909304601f8101849004840282018401909252818152929183018282801561036a5780601f1061033f5761010080835404028352916020019161036a565b820191906000526020600020905b81548152906001019060200180831161034d57829003601f168201915b505050505081565b336000818152600260209081526040808320600160a060020a038716808552908352818420869055815186815291519394909390927f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925928290030190a35060015b92915050565b60005481565b600160a060020a038316600090815260016020526040812054821180159061042a5750600160a060020a03841660009081526002602090815260408083203384529091529020548211155b80156104365750600082115b156104c157600160a060020a03808416600081815260016020908152604080832080548801905593881680835284832080548890039055600282528483203384528252918490208054879003905583518681529351929391927fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9281900390910190a35060016104c5565b5060005b9392505050565b60045460ff1681565b6006805460408051602060026001851615610100026000190190941693909304601f8101849004840282018401909252818152929183018282801561036a5780601f1061033f5761010080835404028352916020019161036a565b600160a060020a031660009081526001602052604090205490565b6005805460408051602060026001851615610100026000190190941693909304601f8101849004840282018401909252818152929183018282801561036a5780601f1061033f5761010080835404028352916020019161036a565b3360009081526001602052604081205482118015906105c55750600082115b156106375733600081815260016020908152604080832080548790039055600160a060020a03871680845292819020805487019055805186815290519293927fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef929181900390910190a35060016103d3565b5060006103d3565b336000818152600260209081526040808320600160a060020a038816808552908352818420879055815187815291519394909390927f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925928290030190a383600160a060020a031660405180807f72656365697665417070726f76616c28616464726573732c75696e743235362c81526020017f616464726573732c627974657329000000000000000000000000000000000000815250602e019050604051809103902060e060020a9004338530866040518563ffffffff1660e060020a0281526004018085600160a060020a0316600160a060020a0316815260200184815260200183600160a060020a0316600160a060020a03168152602001828051906020019080838360005b8381101561077f578181015183820152602001610767565b50505050905090810190601f1680156107ac5780820380516001836020036101000a031916815260200191505b509450505050506000604051808303816000875af19250505015156107d057600080fd5b5060019392505050565b600160a060020a039182166000908152600260209081526040808320939094168252919091522054905600a165627a7a723058203f2de808df5359509254dc2a0d616b226de2b64f0bf28bae7323aeba4487199b002900000000000000000000000000000000000000000000000000000000000f42400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000c776562336a20746f6b656e730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000477336a24000000000000000000000000000000000000000000000000000000001ba0089923ee2eb13690f8d1208847c0009de2f47a30ae26885d12be8f849e1e26aca060ae1bed04b7ae841d70df1be32400f64f90203970099fa7e270c5a3e041d007"],"id":1}
18:15:16.581 [Test worker] DEBUG org.web3j.protocol.http.HttpService - --> END POST (5708-byte body)
18:15:16.614 [Test worker] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (32ms)
18:15:16.615 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
18:15:16.615 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Vary: Origin
18:15:16.615 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Date: Wed, 21 Aug 2019 09:15:16 GMT
18:15:16.616 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 76
18:15:16.616 [Test worker] DEBUG org.web3j.protocol.http.HttpService - 
18:15:16.616 [Test worker] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"invalid sender"}}

18:15:16.616 [Test worker] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (76-byte body)
null

java.lang.NullPointerException
	at org.web3j.protocol.scenarios.HumanStandardTokenIT.createContract(HumanStandardTokenIT.java:144)
	at org.web3j.protocol.scenarios.HumanStandardTokenIT.testContract(HumanStandardTokenIT.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:819)
```

Let me know if you need any additional information and I'm sorry for the poor English.

**Comment by iikirilov** [comment]
You need to make the appropriate changes in the superclass `Scenario`

**Comment by KoangHoYeom** [comment]
thank you ! 
It was successful after change the Scenario file.
