### ISSUE TITLE
Could not construct a recoverable key. This should never happen.

### ISSUE THREAD

**Issue by otembajelle** [web3j/web3j#103]
Update 1: If I use the correct format for the keyset, then this issue does not arise. So my assumptions below turned out correct.

Update 2 workaround: I failed to generate a public key from a private key, but I found a valid keyset in org.web3j.crypto.SampleKeys. Still, I am curious to know how the makers of web3j created that.

Update 3: To whom is looking for other keysets. You may want to check ...
 ```
   @Test
    public void testCreateEcKeyPair() throws Exception {
        ECKeyPair ecKeyPair = Keys.createEcKeyPair();
        assertThat(ecKeyPair.getPublicKey().signum(), is(1));
        assertThat(ecKeyPair.getPrivateKey().signum(), is(1));
    }
```

Thank you for creating Web3j. I am new.

I am speculating that the error may be originated in wrong credentials. In my testcase (annex), Alices is created as `		alice = Credentials.create("0xede2b8b4c3a8dcbeb90ceed6fc116d5686b35ae84787056a1788d9c6bda7104e", // 32 byte hex
				"0xb2fb6b157b8febf57baa91ffaf6ed57d99419dbf" // 64 byte hex
		);
`

Might that trigger the issue? If so then my question is: how the hell do I get a 64 byte public key. TestRpc wont reveil it when it starts up.

This is what I have done so far:

I generated HelloWorld from new. It processed fine and I became a fresh
[HelloWorld.java.txt](https://github.com/web3j/web3j/files/1068317/HelloWorld.java.txt)
[HelloWorldTest.java.txt](https://github.com/web3j/web3j/files/1068318/HelloWorldTest.java.txt)

 HelloWorld.java easily (annex).

Apparently I do not know how to use it because I get this RuntimeException.

What am I doing wrong? OR Where can I get a running example?

java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not construct a recoverable key. This should never happen.
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.agilityarchitects.ethereum.HelloWorldTest.testDeploy(HelloWorldTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.RuntimeException: Could not construct a recoverable key. This should never happen.
	at org.web3j.crypto.Sign.signMessage(Sign.java:55)
	at org.web3j.crypto.TransactionEncoder.signMessage(TransactionEncoder.java:21)
	at org.web3j.tx.RawTransactionManager.signAndSend(RawTransactionManager.java:89)
	at org.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:78)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:45)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:43)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:203)
	at org.web3j.tx.Contract.create(Contract.java:293)
	at org.web3j.tx.Contract.deploy(Contract.java:268)
	at org.web3j.tx.Contract.lambda$deployAsync$24(Contract.java:310)
	at org.web3j.utils.Async.lambda$run$28(Async.java:20)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by otembajelle** [comment]
From the comment in the generated HelloWorld.java, I gather that Alices address is not sufficient. I am starting to speculate. What I found is a hint to calculate the public - from the private key. 

https://bitcoin.stackexchange.com/questions/42055/what-is-the-approach-to-calculate-an-ethereum-address-from-a-256-bit-private-key

What puzzles me is that close to noone else questions. I am lost in the dark.
