### ISSUE TITLE
Generated "HelloWorld.sol" does not depoy. ( invalid opcode )

### ISSUE THREAD

**Issue by otembajelle** [web3j/web3j#105]
I am new and trying to get Web3j to work for me. Please help me out, 

What I did:

1. I used truffle to compile (annex)
2. I took the HelloWorld.json apart and created HelloWorld.abi and HelloWorld.bin (annexes)
3. I generated the HelloWorld.java (annex) (so far so good)
4. I created a Unit Test to run its deploy method BANG!
5. The testrpc console shows different outputs (annexes
[consoleError.txt](https://github.com/web3j/web3j/files/1080778/consoleError.txt)
[consoleTruffleOK.txt](https://github.com/web3j/web3j/files/1080779/consoleTruffleOK.txt)

`java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error processing transaction request: VM Exception while processing transaction: invalid opcode
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.agilityarchitects.ethereum.HelloWorldTest.testDeploy(HelloWorldTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.RuntimeException: Error processing transaction request: VM Exception while processing transaction: invalid opcode
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:60)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:46)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:43)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:203)
	at org.web3j.tx.Contract.create(Contract.java:293)
	at org.web3j.tx.Contract.deploy(Contract.java:268)
	at org.web3j.tx.Contract.lambda$deployAsync$24(Contract.java:310)
	at org.web3j.utils.Async.lambda$run$28(Async.java:20)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
`
[HelloWorld.json.txt](https://github.com/web3j/web3j/files/1080760/HelloWorld.json.txt)
[HelloWorld.abi.txt](https://github.com/web3j/web3j/files/1080762/HelloWorld.abi.txt)
[HelloWorld.bin.txt](https://github.com/web3j/web3j/files/1080765/HelloWorld.bin.txt)
[HelloWorld.java.txt](https://github.com/web3j/web3j/files/1080772/HelloWorld.java.txt)

**Comment by conor10** [comment]
Did you generate the wrapper with the web3j command line tools? I see a hex prefix in the BINARY value in the HellowWorld.java file, which doesn't seem right. See these examples https://github.com/web3j/web3j/tree/master/src/integration-test/java/org/web3j/generated.

**Comment by otembajelle** [comment]
Ah forgot to say, I am running a Beta of TestRpc of last week. I found a recent incident: https://ethereum.stackexchange.com/questions/3613/getting-invalid-opcode-error

Is it related?

**Comment by conor10** [comment]
Please can you try running the code using Geth or Parity?

**Comment by otembajelle** [comment]
Hi Conor, thank you for reopening my case. Yes I am willing to try. No, I never used Geth or Parity. 

Parity challenged my curiousity lately, so I am happy to try it out. For you it means that I will need some time. Also, please consider the case where the result is negative. Then it may be questionable for the real cause may be my wrongdoings with Parity. Please excuse me for not being able to be a reliable source.

**Comment by conor10** [comment]
No problem. Please reopen this issue if it is still an issue once you've tested in Geth or Parity.
