### ISSUE TITLE
EIP-712 implementation fails on bytes and bytes1..32 types

### ISSUE THREAD

**Issue by avaness** [web3j/web3j#1054]
`StructuredDataEncoder.hashStructuredData()` fails on `bytes` and `bytes1..32` types with following

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class [B (java.lang.String and [B are in module java.base of loader 'bootstrap')

	at org.web3j.crypto.StructuredDataEncoder.encodeData(StructuredDataEncoder.java:250)
	at org.web3j.crypto.StructuredDataEncoder.encodeData(StructuredDataEncoder.java:255)
	at org.web3j.crypto.StructuredDataEncoder.hashMessage(StructuredDataEncoder.java:354)
	at org.web3j.crypto.StructuredDataEncoder.hashStructuredData(StructuredDataEncoder.java:417)
```

on the following sample

```
{
  "types": {
    "EIP712Domain": [
      {"name": "name", "type": "string"},
      {"name": "version", "type": "string"},
      {"name": "chainId", "type": "uint256"},
      {"name": "verifyingContract", "type": "address"}
    ],
    "Person": [
      {"name": "name", "type": "string"},
      {"name": "wallet", "type": "address"},
      {"name": "personInfo", "type": "bytes"},
      {"name": "personData", "type": "bytes3"}
    ],
    "Mail": [
      {"name": "from", "type": "Person"},
      {"name": "to", "type": "Person"},
      {"name": "contents", "type": "string"}
    ]
  },
  "primaryType": "Mail",
  "domain": {
    "name": "Ether Mail",
    "version": "1",
    "chainId": 1,
    "verifyingContract": "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
  },
  "message": {
    "from": {
      "name": "Cow",
      "wallet": "0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826",
      "personInfo": "0xABCD01234",
      "personData": "0x12345"
    },
    "to": {
      "name": "Bob",
      "wallet": "0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB",
      "personInfo": "0x01234ABCD",
      "personData": "0x54321"
    },
    "contents": "Hello, Bob!"
  }
}
```

there's a problem on line StructuredEncodeData.java:250
```
byte[] hashedValue = sha3((byte[]) value);
```
where `value` can't be converted to `((byte[]) value)` since it's `json string` but not `byte[]`

the same problem appears for `bytes1..32` types.

I have a patch for this being completely according to EIP-712. It's verified and used in my project. will attach PR for this soon

**Comment by iikirilov** [comment]
this fixes a bug - should not be closed
