### ISSUE TITLE
Unavailable to process logs with payload size greater than 405KB (Approx.)

### ISSUE THREAD

**Issue by CodeUltimate** [web3j/web3j#1071]
When attempting to publish an event in Quorum using the Web3J library with Web3J Quorum with a payload size approximately greater than 405KB, we are encountering the following error:

`org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 413; content length too large (526385>524288)

	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:163)
	at org.web3j.protocol.Service.send(Service.java:34)
	at org.web3j.protocol.core.Request.send(Request.java:72)
	at org.web3j.quorum.tx.ClientTransactionManager.sendTransaction(ClientTransactionManager.java:83)` 

This is the scenario:

I have some "data" using BZIP that I need to publish to Quorum in which the contract I publish it with should emit back with the data that the contract was triggered with, however when the data I deploy with the contract is greater than 405KB it does not mine the block.

**Comment by antonydenyer** [comment]
The 413 staus code is coming from the server-side and appears to be a (perhaps reasonable) limitation of not being able to upload more than 0.5MB.

**Comment by CodeUltimate** [comment]
@antonydenyer Does this mean we have to report the issue to the Quorum team? The issues does not seem to be an issue with Web3J or Web3J Quorum but more to do with Quorum's emit event mechanism as we can't upload more than 0.5MB.

**Comment by antonydenyer** [comment]
Yes, I'm pretty sure this is a quorum issue (sorry I had should have been clearer when we spoke).

**Comment by CodeUltimate** [comment]
@antonydenyer Sure, I'll catch it up with them.
