### ISSUE TITLE
This happens When I use the multithreaded call method.... 

### ISSUE THREAD

**Issue by sclei007** [web3j/web3j#1078]
### Actual behavior
com.fasterxml.jackson.databind.JsonMappingException: Read timed out (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"]->org.web3j.protocol.core.methods.response.EthBlock$Block["transactions"])

## Environment
_Describe the environment in which the issue occurs
use the multithreaded call method
- Web3j version
<dependency>
    <groupId>org.web3j</groupId>
    <artifactId>core</artifactId>
    <version>4.5.5</version>
</dependency>
- Java 
- Operating System

## Additional context
```
com.fasterxml.jackson.databind.JsonMappingException: Read timed out (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"]->org.web3j.protocol.core.methods.response.EthBlock$Block["transactions"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:982) ~[jackson-databind-2.9.8.jar:2.9.8]
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:629) ~[core-4.5.5.jar:?]
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:620) ~[core-4.5.5.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070) ~[jackson-databind-2.9.8.jar:2.9.8]
	at org.web3j.protocol.Service.send(Service.java:44) ~[core-4.5.5.jar:?]
	at org.web3j.protocol.core.Request.send(Request.java:81) ~[core-4.5.5.jar:?]
	at com.blockchain.blockchainweb.service.CollectBasicDataService.getEthBlockByNumber(CollectBasicDataService.java:123) [classes/:?]
	at com.blockchain.blockchainweb.service.CollectBasicDataService.dealWithBlockInfo(CollectBasicDataService.java:195) [classes/:?]
	at com.blockchain.blockchainweb.service.CollectBasicDataService.getTotalInfo(CollectBasicDataService.java:73) [classes/:?]
	at com.blockchain.blockchainweb.thread.Taskthread.run(Taskthread.java:19) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

```

**Comment by AlexandrouR** [comment]
@sclei007 can you provide a snippet of the code you are using so I can try and replicate this issue?

**Comment by sclei007** [comment]
@AlexandrouR  
=================================================================
	ExecutorService ExecutorService = Executors.newFixedThreadPool(20);

	public void method(long SblockNum, long EblockNum) {
              //SblockNum=8000000,EblockNum=8001026
		for (long i = SblockNum; i < EblockNum + 1; i++) {
		try {
			ExecutorService.submit(new Taskthread(i, service));
		} catch (Throwable e) {
		}
		}
	}
===============================================================
private Block getEthBlockByNumber(long blockNumber, Web3j web3j) {

		Block result = null;
		Request<?, EthBlock> ethGetBlockByNumber = web3j
				.ethGetBlockByNumber(new DefaultBlockParameterNumber(BigInteger.valueOf(blockNumber)), true);
		try {
			result = ethGetBlockByNumber.send().getResult();
		} catch (IOException e) {
		}
		return result;
	}
==========================================================
sometimes  i  will get another exception:
    com.fasterxml.jackson.databind.JsonMappingException: unexpected end of stream (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"]->org.web3j.protocol.core.methods.response.EthBlock$Block["transactions"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:982) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:629) ~[core-4.5.5.jar!/:?]
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:620) ~[core-4.5.5.jar!/:?]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at org.web3j.protocol.Service.send(Service.java:44) ~[core-4.5.5.jar!/:?]
	at org.web3j.protocol.core.Request.send(Request.java:81) ~[core-4.5.5.jar!/:?]
	at com.blockchain.blockchainweb.service.CollectBasicDataService.getEthBlockByNumber(CollectBasicDataService.java:165) [classes!/:0.0.1-SNAPSHOT]
	at com.blockchain.blockchainweb.service.CollectBasicDataService.dealWithBlockInfo(CollectBasicDataService.java:237) [classes!/:0.0.1-SNAPSHOT]
	at com.blockchain.blockchainweb.service.CollectBasicDataService.getTotalInfo(CollectBasicDataService.java:69) [classes!/:0.0.1-SNAPSHOT]
	at com.blockchain.blockchainweb.thread.Taskthread.run(Taskthread.java:19) [classes!/:0.0.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_141]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.RuntimeException: unexpected end of stream
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:196) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:604) ~[core-4.5.5.jar!/:?]
	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:587) ~[core-4.5.5.jar!/:?]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	... 22 more
Caused by: java.net.ProtocolException: unexpected end of stream
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:432) ~[okhttp-3.8.1.jar!/:?]
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:430) ~[okio-1.13.0.jar!/:?]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:205) ~[jackson-core-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMoreGuaranteed(UTF8StreamJsonParser.java:2348) ~[jackson-core-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2433) ~[jackson-core-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2413) ~[jackson-core-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:269) ~[jackson-core-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:672) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:277) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:192) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:604) ~[core-4.5.5.jar!/:?]
	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:587) ~[core-4.5.5.jar!/:?]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	... 22 more
***************************************************************************
 thinks

**Comment by sclei007** [comment]
@AlexandrouR 
ExecutorService ExecutorService = Executors.newFixedThreadPool(20);

public void method(long SblockNum, long EblockNum) {
          //SblockNum=8000000,EblockNum=8001026
	for (long i = SblockNum; i < EblockNum + 1; i++) {
	try {
		ExecutorService.submit(new Taskthread(i, service));
	} catch (Throwable e) {
	}
	}
}
===============================================================
private Block getEthBlockByNumber(long blockNumber, Web3j web3j) {

	Block result = null;
	Request<?, EthBlock> ethGetBlockByNumber = web3j
			.ethGetBlockByNumber(new DefaultBlockParameterNumber(BigInteger.valueOf(blockNumber)), true);
	try {
		result = ethGetBlockByNumber.send().getResult();
	} catch (IOException e) {
	}
	return result;
}
==========================================================
sometimes i will get another exception:
com.fasterxml.jackson.databind.JsonMappingException: unexpected end of stream (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"]->org.web3j.protocol.core.methods.response.EthBlock$Block["transactions"])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:982) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:629) ~[core-4.5.5.jar!/:?]
at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:620) ~[core-4.5.5.jar!/:?]
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at org.web3j.protocol.Service.send(Service.java:44) ~[core-4.5.5.jar!/:?]
at org.web3j.protocol.core.Request.send(Request.java:81) ~[core-4.5.5.jar!/:?]
at com.blockchain.blockchainweb.service.CollectBasicDataService.getEthBlockByNumber(CollectBasicDataService.java:165) [classes!/:0.0.1-SNAPSHOT]
at com.blockchain.blockchainweb.service.CollectBasicDataService.dealWithBlockInfo(CollectBasicDataService.java:237) [classes!/:0.0.1-SNAPSHOT]
at com.blockchain.blockchainweb.service.CollectBasicDataService.getTotalInfo(CollectBasicDataService.java:69) [classes!/:0.0.1-SNAPSHOT]
at com.blockchain.blockchainweb.thread.Taskthread.run(Taskthread.java:19) [classes!/:0.0.1-SNAPSHOT]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_141]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.RuntimeException: unexpected end of stream
at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:196) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:604) ~[core-4.5.5.jar!/:?]
at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:587) ~[core-4.5.5.jar!/:?]
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar!/:2.9.8]
... 22 more
Caused by: java.net.ProtocolException: unexpected end of stream
at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:432) ~[okhttp-3.8.1.jar!/:?]
at okio.RealBufferedSource$1.read(RealBufferedSource.java:430) ~[okio-1.13.0.jar!/:?]
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:205) ~[jackson-core-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMoreGuaranteed(UTF8StreamJsonParser.java:2348) ~[jackson-core-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2433) ~[jackson-core-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2413) ~[jackson-core-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:269) ~[jackson-core-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:672) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:277) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:192) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:604) ~[core-4.5.5.jar!/:?]
at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:587) ~[core-4.5.5.jar!/:?]
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar!/:2.9.8]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar!/:2.9.8]
... 22 more

thanks

**Comment by AlexandrouR** [comment]
@sclei007 hey I tried to replicate the issue using the code snippet you provided but was unsuccessful. I used Infura to do so. What type of node are you connected to? Is it local or?

**Comment by AlexandrouR** [comment]
Closing due to inactivity.
