### ISSUE TITLE
NPE using replayPastAndFutureTransactionsFlowable or other subscription functions with start or end block parameter

### ISSUE THREAD

**Issue by helllynx** [web3j/web3j#1081]
## Steps To Reproduce
```
            val webSocketClient = WebSocketClient(URI("wss://ropsten.infura.io/ws/{here you'r api key}"))
            val includeRawResponses = true
            val webSocketService = WebSocketService(webSocketClient, includeRawResponses)
            webSocketService.connect()
            val web3 = Web3j.build(webSocketService)

            val address = "0x88a007ec4f1819f24c0988fc9c26496b99b436d1"

            web3.replayPastTransactionsFlowable(
                DefaultBlockParameter.valueOf(BigInteger("6531004")), DefaultBlockParameter.valueOf(BigInteger("6635881"))
            ).filter { tx -> tx.from == address }.subscribe {
                Log.d("Transaction Hash", it.hash)
            }

```

### Expected behavior
Log some transactions between 6623000 and 6623469.

### Actual behavior
```
D/Transaction Hash: 0x38241a39b0f49f2b7dfdd34c614f25dea20587942a9b5dee3d5781e31d6a0bcc
W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | Attempt to invoke virtual method 'java.util.List org.web3j.protocol.core.methods.response.EthBlock$Block.getTransactions()' on a null object reference
W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:275)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:234)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:152)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:547)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:471)
W/System.err:     at org.web3j.utils.Flowables.lambda$range$0(Flowables.java:41)
W/System.err:     at org.web3j.utils.-$$Lambda$Flowables$URttK3xEo4ZrCXqU3ObVQQ4j39U.subscribe(Unknown Source:4)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:14479)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:14479)
W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:14426)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
W/System.err:     at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
W/System.err:     at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.web3j.protocol.core.methods.response.EthBlock$Block.getTransactions()' on a null object reference
W/System.err:     at org.web3j.protocol.rx.JsonRpc2_0Rx.toTransactions(JsonRpc2_0Rx.java:237)
W/System.err:     at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$3hcalqpDuldIEW534GcL9JuzI9k(Unknown Source:0)
W/System.err:     at org.web3j.protocol.rx.-$$Lambda$JsonRpc2_0Rx$3hcalqpDuldIEW534GcL9JuzI9k.apply(Unknown Source:2)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:265)
W/System.err: 	... 22 more
E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
    Process: io.web3.repository.test, PID: 10603
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | Attempt to invoke virtual method 'java.util.List org.web3j.protocol.core.methods.response.EthBlock$Block.getTransactions()' on a null object reference
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
        at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:275)
        at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:234)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:152)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:547)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:471)
        at org.web3j.utils.Flowables.lambda$range$0(Flowables.java:41)
        at org.web3j.utils.-$$Lambda$Flowables$URttK3xEo4ZrCXqU3ObVQQ4j39U.subscribe(Unknown Source:4)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.Flowable.subscribe(Flowable.java:14426)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.web3j.protocol.core.methods.response.EthBlock$Block.getTransactions()' on a null object reference
        at org.web3j.protocol.rx.JsonRpc2_0Rx.toTransactions(JsonRpc2_0Rx.java:237)
        at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$3hcalqpDuldIEW534GcL9JuzI9k(Unknown Source:0)
        at org.web3j.protocol.rx.-$$Lambda$JsonRpc2_0Rx$3hcalqpDuldIEW534GcL9JuzI9k.apply(Unknown Source:2)
        at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:265)
        at io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext(FlowableFlattenIterable.java:174) 
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:234) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:152) 
        at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:547) 
        at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:471) 
        at org.web3j.utils.Flowables.lambda$range$0(Flowables.java:41) 
        at org.web3j.utils.-$$Lambda$Flowables$URttK3xEo4ZrCXqU3ObVQQ4j39U.subscribe(Unknown Source:4) 
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14426) 
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82) 
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260) 
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
I/Process: Sending signal. PID: 10603 SIG: 9
```

If i remove ``filter`` in logs i see many hashes but after that same exception.

## Environment
_Describe the environment in which the issue occurs_
- org.web3j:core:4.2.0-android
- Check on 22,23,26,28 SDK versions.

## Additional context
 - ropsten link to address: https://ropsten.etherscan.io/address/0x88a007ec4f1819f24c0988fc9c26496b99b436d1

**Comment by AlexandrouR** [comment]
``` 
 web3.replayPastTransactionsFlowable(
                DefaultBlockParameter.valueOf(BigInteger.valueOf(6531004)),
                DefaultBlockParameter.valueOf(BigInteger.valueOf(6635881)))
                .filter(tx -> tx.getFrom().equals(address)).subscribe(tx ->
                System.out.println(tx.getHash()), Throwable::printStackTrace);
``` 
Try defining the onError in the subscribe as i did above.
I've been running the modified example for over 20 minutes.
No issues so far.

**Comment by helllynx** [comment]
> ```
>  web3.replayPastTransactionsFlowable(
>                 DefaultBlockParameter.valueOf(BigInteger.valueOf(6531004)),
>                 DefaultBlockParameter.valueOf(BigInteger.valueOf(6635881)))
>                 .filter(tx -> tx.getFrom().equals(address)).subscribe(tx ->
>                 System.out.println(tx.getHash()), Throwable::printStackTrace);
> ```
> 
> Try defining the onError in the subscribe as i did above.
> I've been running the modified example for over 20 minutes.
> No issues so far.

Hi! This is not helped at all. It just catching the Exception, but after that web3 falls and doesn't receive transactions. Here some example:

**Comment by helllynx** [comment]
> ```
>  web3.replayPastTransactionsFlowable(
>                 DefaultBlockParameter.valueOf(BigInteger.valueOf(6531004)),
>                 DefaultBlockParameter.valueOf(BigInteger.valueOf(6635881)))
>                 .filter(tx -> tx.getFrom().equals(address)).subscribe(tx ->
>                 System.out.println(tx.getHash()), Throwable::printStackTrace);
> ```
> 
> Try defining the onError in the subscribe as i did above.
> I've been running the modified example for over 20 minutes.
> No issues so far.

Hi!

This metod doesn't help. It just prevent app falling, but still no right output.

**Comment by AlexandrouR** [comment]
@helllynx  does it fail at the same block every time or randomly?

**Comment by helllynx** [comment]
@AlexandrouR 

Run few times and it fails on the same block:
```
Transaction Hash: 0x55b3d145b309e089ae6e24a9a3a6d7975de602f8819ab978b262977aaf24cb7e  
Block: 6642833
```

**Comment by AlexandrouR** [comment]
@helllynx I still can't replicate. With the code snippet, I provided above i get :
```
0xa04585fb62b2a2244e68af37ef154ff22baace50e0d5b3f192a2af087a7ba1b9 Looking in block number: 6642799
0xc01314c8e2520c128002ddc03f9c5a68608af1269ace6e84fd96c3edf32ee412 Looking in block number: 6642811
0x086bc8fdf29384871f6ee38bed9a153a1b32401264ed633b0bc3c720683938ba Looking in block number: 6642821
0x55b3d145b309e089ae6e24a9a3a6d7975de602f8819ab978b262977aaf24cb7e Looking in block number: 6642833
0x7744cc8536c238012463ee60ad8477cc6b0a6daaa5105d859be679908133477d Looking in block number: 6642838
0xac951e10d02a559955e50d3186241765a835d8b2f0f33819c08ca1e1c8d1db16 Looking in block number: 6642851
0xcc33656f940b43bee91e81a4de014737f0fa207fe093c21b380d5cdf348f9904 Looking in block number: 6643104
0x89d25e50cdf7f76639488220d8c70eb9f4744a92bc9ccaf4f7167f94f62f7709 Looking in block number: 6643107
0x8cd9e9ee8ad764a02cf0425e0228578f9031314c3efa7637eb660be9eb61eaf1 Looking in block number: 6643108
0xb9c0f1475878e3a9649637c086620057b89ed2c0aca17cd0f70870403e1ede75 Looking in block number: 6643110
0x577c10659b1c93322fb74ab23b8583673142a438418aabb175ce71b06e5c8107 Looking in block number: 6643123
0x20ec1bec7c7ec821d32fa73fe8716c828cc5c8a68badf81c8a6637d22bab6acc Looking in block number: 6643125
0x77b282433b08e9a328a30b421bcd21f47fa453b3d997398e13d2b8524f71aa09 Looking in block number: 6643590
0xf26e817fe822d2f4c000a1bfb122d12184245e7b61406599ef9e09904470e753 Looking in block number: 6643590
0x878c112690f8bbb69b5b4007c9bc91117d15a069eadc4b1fcfdd941b3052fd2c Looking in block number: 6643596
0x4e867f0aa816ffda089400b167356567fdc745a205dc232f47a300cf0de224c0 Looking in block number: 6643677
0xf637d4b0aae8ff4dd52301e320fddefe16682732209f7567dd054ed4b93ec825 Looking in block number: 6643689
0x8a58ffef607f95ff08586bdcd188c18cfbc1870d2c788387c7c1c399c4172153 Looking in block number: 6643699
0x1fdaa41e5d2166b32b2901e9d37c5c1ae7e08ee39a09a1f836591254d3883139 Looking in block number: 6643804
```

**Comment by Erdenian** [comment]
> ```
>  web3.replayPastTransactionsFlowable(
>                 DefaultBlockParameter.valueOf(BigInteger.valueOf(6531004)),
>                 DefaultBlockParameter.valueOf(BigInteger.valueOf(6635881)))
>                 .filter(tx -> tx.getFrom().equals(address)).subscribe(tx ->
>                 System.out.println(tx.getHash()), Throwable::printStackTrace);
> ```
> 
> Try defining the onError in the subscribe as i did above.
> I've been running the modified example for over 20 minutes.
> No issues so far.

@AlexandrouR, are you running this snippet on Android with Android version of web3j? I see `System.out.println` instead of `Log.d`.

**Comment by AlexandrouR** [comment]
@Erdenian the outcome is the same on android version of web3j.
