### ISSUE TITLE
Main thread doesn't terminate despite of web3j.shutdown() is called, OkHttp thread is still alive

### ISSUE THREAD

**Issue by vsbogd** [web3j/web3j#1085]
# Main thread doesn't terminate despite of web3j.shutdown() is called, OkHttp thread is still alive
I use `web3j` to read value from the contract deployed in `Ropsten` network. After value is returned, I cleanup `web3j` by calling `Web3j.shutdown()` method. But `main()` method of the application doesn't terminate because one of the non-daemon threads still works. `jstack` shows that it is one of the OkHttp threads `OkHttp ropsten.infura.io` . May be it is related to the issue #710.

## Steps To Reproduce
Pseudo-code:
```java
public class TestApp {

    public static void main(String[] args) throws Exception {
        Web3j web3j = Web3j.build(new HttpService("https://ropsten.infura.io"));
        try {
            ReadonlyTransactionManager roTransactionManager = new ReadonlyTransactionManager(
                    web3j, "0x<address>");
            ContractGasProvider gasProvider = new DefaultGasProvider();

            TestContract contract = TestContract.load("0x<contract address>", web3j,
                    roTransactionManager, gasProvider);

            Object value = contract.readValue().send();
        } finally {
            web3j.shutdown();
            System.out.println("shutdown");
        }
    }
}
```
### Expected behavior
TestApp prints `shutdown` and exits.

### Actual behavior
TestApp prints `shutdown` and hangs

## Environment
- Web3j version: 4.5.5
- Operating System: Ubuntu 18.04.2 LTS
- Java version:
```sh
$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```

## Additional context
<details>
<summary>jstack results</summary>

```
2019-10-31 20:32:32
Full thread dump OpenJDK 64-Bit Server VM (11.0.4+11-post-Ubuntu-1ubuntu218.04.3 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fe7840026d0, length=17, elements={
0x00007fe7d0010000, 0x00007fe7d01ce800, 0x00007fe7d01d0800, 0x00007fe7d01d5800,
0x00007fe7d01d8000, 0x00007fe7d01da000, 0x00007fe7d01dc000, 0x00007fe7d023b000,
0x00007fe7d0243800, 0x00007fe75041d800, 0x00007fe750428000, 0x00007fe750529000,
0x00007fe75052a800, 0x00007fe76410a000, 0x00007fe7640e3800, 0x00007fe75050f800,
0x00007fe784001800
}

"main" #1 prio=5 os_prio=0 cpu=1613.47ms elapsed=9.78s tid=0x00007fe7d0010000 nid=0x292a in Object.wait()  [0x00007fe7d967a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <0x0000000714c639c0> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.4/Thread.java:1305)
	- waiting to re-lock in wait() <0x0000000714c639c0> (a java.lang.Thread)
	at org.codehaus.mojo.exec.ExecJavaMojo.joinThread(ExecJavaMojo.java:408)
	at org.codehaus.mojo.exec.ExecJavaMojo.joinNonDaemonThreads(ExecJavaMojo.java:397)
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:312)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.4/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.4/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.4/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.4/Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=1.12ms elapsed=9.77s tid=0x00007fe7d01ce800 nid=0x2931 waiting on condition  [0x00007fe7a4ff3000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.4/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.4/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.4/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.33ms elapsed=9.77s tid=0x00007fe7d01d0800 nid=0x2932 in Object.wait()  [0x00007fe7a4ef2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <0x0000000707a00b08> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.4/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000707a00b08> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.4/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.4/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.27ms elapsed=9.76s tid=0x00007fe7d01d5800 nid=0x2933 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 cpu=1806.46ms elapsed=9.76s tid=0x00007fe7d01d8000 nid=0x2934 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=0 cpu=1237.36ms elapsed=9.76s tid=0x00007fe7d01da000 nid=0x2935 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=0 cpu=44.62ms elapsed=9.76s tid=0x00007fe7d01dc000 nid=0x2936 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #10 daemon prio=9 os_prio=0 cpu=0.12ms elapsed=9.74s tid=0x00007fe7d023b000 nid=0x2937 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=0 cpu=1.00ms elapsed=9.74s tid=0x00007fe7d0243800 nid=0x2939 in Object.wait()  [0x00007fe77bdfb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <0x0000000707a02920> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.4/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000707a02920> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.4/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.4/InnocuousThread.java:134)

"RxSchedulerPurge-1" #17 daemon prio=5 os_prio=0 cpu=2.80ms elapsed=7.85s tid=0x00007fe75041d800 nid=0x2944 waiting on condition  [0x00007fe779e92000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
	- parking to wait for  <0x00000007168e0438> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.4/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.4/AbstractQueuedSynchronizer.java:2123)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.4/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.4/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.4/ThreadPoolExecutor.java:1054)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"RxCachedWorkerPoolEvictor-1" #18 daemon prio=5 os_prio=0 cpu=0.13ms elapsed=7.85s tid=0x00007fe750428000 nid=0x2945 waiting on condition  [0x00007fe779d91000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
	- parking to wait for  <0x00000007167a4188> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.4/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.4/AbstractQueuedSynchronizer.java:2123)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.4/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.4/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.4/ThreadPoolExecutor.java:1054)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"OkHttp ropsten.infura.io" #19 prio=5 os_prio=0 cpu=7.56ms elapsed=7.00s tid=0x00007fe750529000 nid=0x2946 runnable  [0x00007fe77b8d2000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.4/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.4/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.4/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.4/SocketInputStream.java:140)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@11.0.4/SSLSocketInputRecord.java:448)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@11.0.4/SSLSocketInputRecord.java:68)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(java.base@11.0.4/SSLSocketImpl.java:1104)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(java.base@11.0.4/SSLSocketImpl.java:823)
	- locked <0x000000071505ee40> (a sun.security.ssl.SSLSocketImpl$AppInputStream)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:67)
	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:95)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:566)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"OkHttp ConnectionPool" #20 daemon prio=5 os_prio=0 cpu=0.66ms elapsed=7.00s tid=0x00007fe75052a800 nid=0x2947 in Object.wait()  [0x00007fe77b7d1000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <0x0000000713a5f780> (a okhttp3.ConnectionPool)
	at java.lang.Object.wait(java.base@11.0.4/Object.java:462)
	at okhttp3.ConnectionPool$1.run(ConnectionPool.java:67)
	- waiting to re-lock in wait() <0x0000000713a5f780> (a okhttp3.ConnectionPool)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"OkHttp Http2Connection" #21 daemon prio=5 os_prio=0 cpu=0.51ms elapsed=7.00s tid=0x00007fe76410a000 nid=0x2948 waiting on condition  [0x00007fe77968d000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
	- parking to wait for  <0x0000000714d6c5b0> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.4/LockSupport.java:234)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(java.base@11.0.4/SynchronousQueue.java:462)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(java.base@11.0.4/SynchronousQueue.java:361)
	at java.util.concurrent.SynchronousQueue.poll(java.base@11.0.4/SynchronousQueue.java:937)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.4/ThreadPoolExecutor.java:1053)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"OkHttp Http2Connection" #22 daemon prio=5 os_prio=0 cpu=0.55ms elapsed=6.99s tid=0x00007fe7640e3800 nid=0x2949 waiting on condition  [0x00007fe77958c000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
	- parking to wait for  <0x0000000714d6c5b0> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.4/LockSupport.java:234)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(java.base@11.0.4/SynchronousQueue.java:462)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(java.base@11.0.4/SynchronousQueue.java:361)
	at java.util.concurrent.SynchronousQueue.poll(java.base@11.0.4/SynchronousQueue.java:937)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.4/ThreadPoolExecutor.java:1053)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.4/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.4/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

"Okio Watchdog" #23 daemon prio=5 os_prio=0 cpu=0.30ms elapsed=6.99s tid=0x00007fe75050f800 nid=0x294a in Object.wait()  [0x00007fe77948b000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <0x0000000715032680> (a java.lang.Class for okio.AsyncTimeout)
	at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:347)
	at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:312)
	- waiting to re-lock in wait() <0x0000000715032680> (a java.lang.Class for okio.AsyncTimeout)

"Attach Listener" #24 daemon prio=9 os_prio=0 cpu=0.31ms elapsed=0.10s tid=0x00007fe784001800 nid=0x295e waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=22.87ms elapsed=9.77s tid=0x00007fe7d01cb800 nid=0x2930 runnable  

"GC Thread#0" os_prio=0 cpu=23.84ms elapsed=9.78s tid=0x00007fe7d0027000 nid=0x292b runnable  

"GC Thread#1" os_prio=0 cpu=32.62ms elapsed=9.46s tid=0x00007fe798001000 nid=0x293c runnable  

"GC Thread#2" os_prio=0 cpu=19.96ms elapsed=9.46s tid=0x00007fe798002800 nid=0x293d runnable  

"GC Thread#3" os_prio=0 cpu=19.74ms elapsed=9.46s tid=0x00007fe798004000 nid=0x293e runnable  

"GC Thread#4" os_prio=0 cpu=22.04ms elapsed=9.46s tid=0x00007fe798006000 nid=0x293f runnable  

"GC Thread#5" os_prio=0 cpu=19.64ms elapsed=9.46s tid=0x00007fe798007800 nid=0x2940 runnable  

"G1 Main Marker" os_prio=0 cpu=0.77ms elapsed=9.78s tid=0x00007fe7d0084800 nid=0x292c runnable  

"G1 Conc#0" os_prio=0 cpu=5.48ms elapsed=9.78s tid=0x00007fe7d0086800 nid=0x292d runnable  

"G1 Conc#1" os_prio=0 cpu=5.19ms elapsed=7.93s tid=0x00007fe7a8001000 nid=0x2942 runnable  

"G1 Conc#2" os_prio=0 cpu=5.04ms elapsed=7.93s tid=0x00007fe7a8002800 nid=0x2943 runnable  

"G1 Refine#0" os_prio=0 cpu=0.34ms elapsed=9.78s tid=0x00007fe7d018e800 nid=0x292e runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=2.39ms elapsed=9.78s tid=0x00007fe7d0190000 nid=0x292f runnable  
"VM Periodic Task Thread" os_prio=0 cpu=6.54ms elapsed=9.74s tid=0x00007fe7d023d800 nid=0x2938 waiting on condition  

JNI global refs: 17, weak refs: 0
```
</details>

**Comment by AlexandrouR** [comment]
@vsbogd  could not replicate, using the code snippet you provided on the ropsten network my application runs as expected.

**Comment by AlexandrouR** [comment]
@vsbogd correction. This works fine on Java 8 however, on java 11 it seems to behave as you described. I would recommend you to use java 8 for now.

**Comment by vsbogd** [comment]
Under Java 8 it works better but still maven claims that daemon threads don't handle `interrupted` properly. Probably it is `RxJava` and `OkHttp` libraries issue though. See example attached: [web3j-test-app.zip](https://github.com/web3j/web3j/files/3808202/web3j-test-app.zip)

I use maven, so to run example one should execute:
```sh
$ mvn clean compile exec:java
```
Java version:
```
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```
<details>
<summary>Java 8 exec results</summary>

```
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 33 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 47 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.756 s
[INFO] Finished at: 2019-11-05T12:34:17+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'java' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/vital/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
(base) vital@vital-workstation:~/projects/singnet/snet-sdk-java/web3j-test-app$ mvn compile exec:java
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< org.web3j.test:web3j-test-app >--------------------
[INFO] Building web3j-test-app 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ web3j-test-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vital/projects/singnet/snet-sdk-java/web3j-test-app/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ web3j-test-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/vital/projects/singnet/snet-sdk-java/web3j-test-app/target/classes
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ web3j-test-app ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Contract response: hello world
web3j.shutdown()
[WARNING] thread Thread[RxSchedulerPurge-1,5,org.web3j.test.Web3jTestApp] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[RxSchedulerPurge-1,5,org.web3j.test.Web3jTestApp] will linger despite being asked to die via interruption
[WARNING] thread Thread[RxCachedWorkerPoolEvictor-1,5,org.web3j.test.Web3jTestApp] will linger despite being asked to die via interruption
[WARNING] thread Thread[OkHttp ConnectionPool,5,org.web3j.test.Web3jTestApp] will linger despite being asked to die via interruption
[WARNING] thread Thread[Okio Watchdog,5,org.web3j.test.Web3jTestApp] will linger despite being asked to die via interruption
[WARNING] NOTE: 4 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=org.web3j.test.Web3jTestApp,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:778)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:328)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.908 s
[INFO] Finished at: 2019-11-05T12:34:43+03:00
[INFO] ------------------------------------------------------------------------
```
</details>

[stack.8.log](https://github.com/web3j/web3j/files/3808290/stack.8.log)

**Comment by vsbogd** [comment]
Java 11 issue is probably caused by https://github.com/square/okhttp/issues/4029

**Comment by AlexandrouR** [comment]
This issue was fixed. The dependency needs to be updated.

**Comment by dfsantamaria** [comment]
I'm experiencing the same issue with Web3j 5.0.0 and java 13.

**Comment by raul1ro** [comment]
I have the same problem with Web3j v5.0.0 and java-17.0.4.1

**Comment by vhagedorn** [comment]
repro on coretto 17 and web3j 5.0.0 

```java
public static void main(String[] args) throws Exception {
		Web3j web3j = Web3j.build(new HttpService("https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"));

		try {
			ReadonlyTransactionManager roTransactionManager = new ReadonlyTransactionManager(
					web3j, CONTRACT);
			ContractGasProvider gasProvider = new DefaultGasProvider();

			MyContract contract = MyContract.load(CONTRACT, web3j, roTransactionManager, gasProvider);

			Object value = contract.getStaked().send();
		} finally {
			web3j.shutdown();
			System.out.println("shutdown");
		}
	}
```

prints "shutdown" (no stacktraces) and proceeds to hang indefinitely

**Comment by lakechain** [comment]
Are there any update for this issue?
