### ISSUE TITLE
import org.web3j.abi.datatypes.AbiTypes cannot be resolved

### ISSUE THREAD

**Issue by sankarshandamle** [web3j/web3j#1087]
import org.web3j.abi.datatypes.AbiTypes cannot be resolved

I am trying to fetch integer/string from a smart contract using web3j. However, on using sendAsync().get() to get the data, I am unable to call the smart contract. I believe the error is caused by the following:

Caused by: java.lang.NoClassDefFoundError: org/web3j/abi/datatypes/AbiTypes
	at org.web3j.protocol.core.methods.response.EthCall.<clinit>(EthCall.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:269)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.web3j.abi.datatypes.AbiTypes
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more

--------------------------

The following is my maven dependency

  <dependency>
  <groupId>org.web3j</groupId>
  <artifactId>core</artifactId>
  <version>4.5.5</version>
  </dependency>

**Comment by SweeXordious** [comment]
Hello,
Can you post your code?
The general structure of the code can be like this: 

```
val web3j = Web3j.build( HttpService(endpoint))
val function = Function(functionName, arguments, returnTypes)
val txData = FunctionEncoder.encode(function)
val transaction = Transaction.createEthCallTransaction(from, to, txData)
web3j.ethCall(transaction, defaultBlockParameter).send()
```
In case you are still deplying the contract, check the [documentation](https://docs.web3j.io/smart_contracts/)

**Comment by kangvai** [comment]
I hava met the same problem,when I use web3j .Do you hava solved it now ? I will appreciate it if you can help me.

**Comment by SweeXordious** [comment]
@kangvai can you post your code ?

**Comment by kangvai** [comment]
> @kangvai can you post your code ?

ok, this is my smart contract
![image](https://user-images.githubusercontent.com/59158970/78229639-dc063480-7502-11ea-98b5-716ce5b9c301.png)
and this is ganache-cli to simulate ethereum
![image](https://user-images.githubusercontent.com/59158970/78229921-399a8100-7503-11ea-8fad-4b3cb99105c9.png)
this class is auto-genereted by web3j using SimpleStorage.sol
![image](https://user-images.githubusercontent.com/59158970/78230206-9e55db80-7503-11ea-8f60-d7dbe65a3c4c.png)
this is to connect ganache-cli and call method in smartcontract
![image](https://user-images.githubusercontent.com/59158970/78230407-de1cc300-7503-11ea-8c33-45294157b76f.png)
the follow is result and exception
![image](https://user-images.githubusercontent.com/59158970/78230561-13291580-7504-11ea-8625-19ae44082f6f.png)

**Comment by SweeXordious** [comment]
What is on Web3jClient: 38 ?
Also which version of web3j you're using and how did you generate the contract wrappers ?

**Comment by kangvai** [comment]
1.on Web3jClient : line 38 there is nothing 
![image](https://user-images.githubusercontent.com/59158970/78256428-184d8b00-752b-11ea-9d73-f1c34a7e6430.png)
2.the version of web3j core I use is 4.5.12
![image](https://user-images.githubusercontent.com/59158970/78256825-a164c200-752b-11ea-8981-a0cb0bcc74e0.png)
3.I use web3j-maven-plugin to generate the contract wrappers
![image](https://user-images.githubusercontent.com/59158970/78257465-7464df00-752c-11ea-9bee-2fea23b35612.png)
4.the generate process is successful
![image](https://user-images.githubusercontent.com/59158970/78256716-8003d600-752b-11ea-9412-3084cbd1d2b1.png)
 and the generated files does exist
![image](https://user-images.githubusercontent.com/59158970/78256944-ca855280-752b-11ea-967c-3e081b0b5ebe.png)
5.last thanks for your patient!

**Comment by kangvai** [comment]
when I change the version of web3j-maven-plugin to 0.3.7 and solidity to 0.4.24,bulid and run......
the code is
`package com.kangvai;


import org.web3j.crypto.Credentials;
import org.web3j.model.SimpleStorage;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.protocol.core.methods.response.Web3ClientVersion;
import org.web3j.protocol.http.HttpService;

import java.math.BigInteger;

public class Web3JClient {

    public static void main(String[] args) throws Exception {
        Web3j web3 = Web3j.build(new HttpService("http://localhost:8545/"));

        String pk = "0x6591270828d15a21e1919c6e9ca0a0d9f5c868b9d55e58cff3335468bdaacafc";
        Credentials credentials = Credentials.create(pk);

        Web3ClientVersion web3ClientVersion = web3.web3ClientVersion().sendAsync().get();
        String clientVersion = web3ClientVersion.getWeb3ClientVersion();
        System.out.println("clientVersion========>"+clientVersion);

        SimpleStorage simpleStorage = SimpleStorage.deploy(
                web3,credentials, BigInteger.valueOf(1), BigInteger.valueOf(800000)
                ).send();  // ether value of contract

        TransactionReceipt transactionReceipt = simpleStorage.set("a").send();
        System.out.println("transactionReceipt======>"+transactionReceipt.getTransactionHash());

        String result = simpleStorage.get().send();
        System.out.println("result=====>"+result);
    }
}
`
the result is the same
`D:\Jdk\Jdk1.8.0\bin\java.exe "-javaagent:D:\IntelliJ IDEA 2019.3.1\lib\idea_rt.jar=1194:D:\IntelliJ IDEA 2019.3.1\bin" -Dfile.encoding=UTF-8 -classpath D:\Jdk\Jdk1.8.0\jre\lib\charsets.jar;D:\Jdk\Jdk1.8.0\jre\lib\deploy.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\access-bridge-64.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\cldrdata.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\dnsns.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\jaccess.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\jfxrt.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\localedata.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\nashorn.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\sunec.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\sunjce_provider.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\sunmscapi.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\sunpkcs11.jar;D:\Jdk\Jdk1.8.0\jre\lib\ext\zipfs.jar;D:\Jdk\Jdk1.8.0\jre\lib\javaws.jar;D:\Jdk\Jdk1.8.0\jre\lib\jce.jar;D:\Jdk\Jdk1.8.0\jre\lib\jfr.jar;D:\Jdk\Jdk1.8.0\jre\lib\jfxswt.jar;D:\Jdk\Jdk1.8.0\jre\lib\jsse.jar;D:\Jdk\Jdk1.8.0\jre\lib\management-agent.jar;D:\Jdk\Jdk1.8.0\jre\lib\plugin.jar;D:\Jdk\Jdk1.8.0\jre\lib\resources.jar;D:\Jdk\Jdk1.8.0\jre\lib\rt.jar;E:\Study\Project\Java\blockchain\target\classes;D:\apache-maven-3.6.3-bin\repository\org\web3j\core\4.5.12\core-4.5.12.jar;D:\apache-maven-3.6.3-bin\repository\org\web3j\tuples\4.5.12\tuples-4.5.12.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jnr-unixsocket\0.21\jnr-unixsocket-0.21.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jnr-ffi\2.1.9\jnr-ffi-2.1.9.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jffi\1.2.17\jffi-1.2.17.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jffi\1.2.16\jffi-1.2.16-native.jar;D:\apache-maven-3.6.3-bin\repository\org\ow2\asm\asm\5.0.3\asm-5.0.3.jar;D:\apache-maven-3.6.3-bin\repository\org\ow2\asm\asm-commons\5.0.3\asm-commons-5.0.3.jar;D:\apache-maven-3.6.3-bin\repository\org\ow2\asm\asm-analysis\5.0.3\asm-analysis-5.0.3.jar;D:\apache-maven-3.6.3-bin\repository\org\ow2\asm\asm-tree\5.0.3\asm-tree-5.0.3.jar;D:\apache-maven-3.6.3-bin\repository\org\ow2\asm\asm-util\5.0.3\asm-util-5.0.3.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jnr-a64asm\1.0.0\jnr-a64asm-1.0.0.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jnr-x86asm\1.0.2\jnr-x86asm-1.0.2.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jnr-constants\0.9.11\jnr-constants-0.9.11.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jnr-enxio\0.19\jnr-enxio-0.19.jar;D:\apache-maven-3.6.3-bin\repository\com\github\jnr\jnr-posix\3.0.47\jnr-posix-3.0.47.jar;D:\apache-maven-3.6.3-bin\repository\com\squareup\okhttp3\okhttp\4.3.1\okhttp-4.3.1.jar;D:\apache-maven-3.6.3-bin\repository\com\squareup\okio\okio\2.4.1\okio-2.4.1.jar;D:\apache-maven-3.6.3-bin\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.3.50\kotlin-stdlib-common-1.3.50.jar;D:\apache-maven-3.6.3-bin\repository\org\jetbrains\kotlin\kotlin-stdlib\1.3.61\kotlin-stdlib-1.3.61.jar;D:\apache-maven-3.6.3-bin\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;D:\apache-maven-3.6.3-bin\repository\com\squareup\okhttp3\logging-interceptor\4.3.1\logging-interceptor-4.3.1.jar;D:\apache-maven-3.6.3-bin\repository\org\java-websocket\Java-WebSocket\1.3.8\Java-WebSocket-1.3.8.jar;D:\apache-maven-3.6.3-bin\repository\com\fasterxml\jackson\core\jackson-databind\2.8.5\jackson-databind-2.8.5.jar;D:\apache-maven-3.6.3-bin\repository\com\fasterxml\jackson\core\jackson-annotations\2.8.0\jackson-annotations-2.8.0.jar;D:\apache-maven-3.6.3-bin\repository\com\fasterxml\jackson\core\jackson-core\2.8.5\jackson-core-2.8.5.jar;D:\apache-maven-3.6.3-bin\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;D:\apache-maven-3.6.3-bin\repository\org\web3j\parity\3.5.0\parity-3.5.0.jar;D:\apache-maven-3.6.3-bin\repository\org\web3j\crypto\3.5.0\crypto-3.5.0.jar;D:\apache-maven-3.6.3-bin\repository\org\web3j\rlp\3.5.0\rlp-3.5.0.jar;D:\apache-maven-3.6.3-bin\repository\org\web3j\utils\3.5.0\utils-3.5.0.jar;D:\apache-maven-3.6.3-bin\repository\org\bouncycastle\bcprov-jdk15on\1.54\bcprov-jdk15on-1.54.jar;D:\apache-maven-3.6.3-bin\repository\org\web3j\abi\3.5.0\abi-3.5.0.jar;D:\apache-maven-3.6.3-bin\repository\org\web3j\codegen\3.5.0\codegen-3.5.0.jar;D:\apache-maven-3.6.3-bin\repository\com\squareup\javapoet\1.7.0\javapoet-1.7.0.jar;D:\apache-maven-3.6.3-bin\repository\com\github\ipfs\java-ipfs-http-client\v1.2.3\java-ipfs-http-client-v1.2.3.jar;D:\apache-maven-3.6.3-bin\repository\com\github\multiformats\java-multiaddr\v1.3.1\java-multiaddr-v1.3.1.jar;D:\apache-maven-3.6.3-bin\repository\com\github\ipld\java-cid\v1.1.0\java-cid-v1.1.0.jar;D:\apache-maven-3.6.3-bin\repository\com\github\multiformats\java-multibase\v1.0.0\java-multibase-v1.0.0.jar;D:\apache-maven-3.6.3-bin\repository\com\github\multiformats\java-multihash\v1.1.0\java-multihash-v1.1.0.jar;D:\apache-maven-3.6.3-bin\repository\io\reactivex\rxjava2\rxjava\2.2.10\rxjava-2.2.10.jar;D:\apache-maven-3.6.3-bin\repository\org\reactivestreams\reactive-streams\1.0.2\reactive-streams-1.0.2.jar com.kangvai.Web3JClient
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
clientVersion========>EthereumJS TestRPC/v2.10.2/ethereum-js
transactionReceipt======>0xbc3c028adae38c3bd32e70178ee163864ebcf492fccd546aa85d89fa87a0e4a7
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.web3j.protocol.core.methods.response.EthCall, problem: org/web3j/abi/datatypes/AbiTypes
 at [Source: buffer(ResponseBodySource(okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource@1aafa419)).inputStream(); line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1441)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:476)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:495)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:262)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
	at org.web3j.protocol.Service.send(Service.java:44)
	at org.web3j.protocol.core.Request.send(Request.java:81)
	at org.web3j.tx.RawTransactionManager.sendCall(RawTransactionManager.java:135)
	at org.web3j.tx.ManagedTransaction.call(ManagedTransaction.java:121)
	at org.web3j.tx.Contract.executeCall(Contract.java:292)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:300)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:311)
	at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:397)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at com.kangvai.Web3JClient.main(Web3JClient.java:32)
Caused by: java.lang.NoClassDefFoundError: org/web3j/abi/datatypes/AbiTypes
	at org.web3j.protocol.core.methods.response.EthCall.<clinit>(EthCall.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:260)
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.web3j.abi.datatypes.AbiTypes
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 21 more

Process finished with exit code 1
`
the ganache-cli result is 
`Listening on 127.0.0.1:8545
web3_clientVersion
eth_getTransactionCount
eth_sendRawTransaction

  Transaction: 0xb3d0bfa3b9f70fee78a34a20107d91a6d7fbf7c0a14b0870e641585b13fc3a61
  Contract created: 0x2a09910e0f562acad2410a9dd6e892f394e64e54
  Gas usage: 199603
  Block Number: 1
  Block Time: Thu Apr 02 2020 22:23:38 GMT+0800 (中国标准时间)

eth_getTransactionReceipt
eth_getTransactionCount
eth_sendRawTransaction

  Transaction: 0xbc3c028adae38c3bd32e70178ee163864ebcf492fccd546aa85d89fa87a0e4a7
  Gas usage: 42946
  Block Number: 2
  Block Time: Thu Apr 02 2020 22:23:38 GMT+0800 (中国标准时间)

eth_getTransactionReceipt
eth_call`

**Comment by SweeXordious** [comment]
no worries. 
I can't seem to be able to reproduce your error. Your main works fine for me.
Try using a more recent version of web3j (core, crypto, plugin etc) and regenerate the wrapper. If didn't work, share your project (not pictures but code so i can run it on my machine and check it more closely)

**Comment by kangvai** [comment]
thanks. the issue has solved.
**reason**:
when i try to change my local solc's version to 0.5.7(its previous version is 0.4.x) and  i change the version of web3j core  because its version (4.5.12) is different from the web3j-maven-plugin version(4.5.11) .then i build and rerun the main code ,no errors appear.
**correct result picture**：
![image](https://user-images.githubusercontent.com/59158970/78319493-dc9dda00-7599-11ea-98ad-e033260539cb.png)
**conclusion**:
i doubt the issue is caused by different version of web3j core and web3j-maven-plugin.
Thanks again buddy!!!
