### ISSUE TITLE
Unable to generate client wrappers for CorDapp

### ISSUE THREAD

**Issue by adelRestom** [web3j/web3j#1115]
Steps to reproduce the error:
1. Create a new Corda project: `web3j-corda new -o web3j-iou -n IOU -p com.example`
2. Browse to the project: `cd web3j-iou`
3. Run gradle task: `./gradlew generateCorDappWrappers`

Error:
```
Exception in thread "main" java.lang.NoSuchFieldError: PROPERTY_DELEGATE
        at com.pinterest.ktlint.core.ast.ElementType.<clinit>(ElementType.kt:33)
        at com.pinterest.ktlint.ruleset.standard.ChainWrappingRule.<init>(ChainWrappingRule.kt:36)
        at com.pinterest.ktlint.ruleset.standard.StandardRuleSetProvider.get(StandardRuleSetProvider.kt:11)
        at org.web3j.corda.codegen.CordaGeneratorUtils.<clinit>(CordaGeneratorUtils.kt:29)
        at org.web3j.corda.codegen.CorDappClientCodegen.processOpts(CorDappClientCodegen.kt:58)
        at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:196)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:910)
        at org.web3j.corda.codegen.CorDappClientGenerator.generate(CorDappClientGenerator.kt:69)
        at org.web3j.corda.console.GenerateCommand.run(GenerateCommand.kt:68)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
        at picocli.CommandLine.execute(CommandLine.java:1864)
        at org.web3j.corda.console.CordaCommandMain$Companion.main(CordaCommandMain.kt:34)
        at org.web3j.corda.console.CordaCommandMain.main(CordaCommandMain.kt)

> Task :generateCorDappWrappers FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateCorDappWrappers'.
> Process 'command '/opt/jdk/jdk1.8.0_202/bin/java'' finished with non-zero exit value 1
```

**Comment by Puneetha17** [comment]
Hi, 

Thanks for raising the issue. https://github.com/web3j/web3j-corda/commit/f81c091bca675219cb10f73f55b2f1518a3782b2 should fix it, will fix a few more bugs and cut release by EOD. 

Also we track `web3j-corda` specific bugs [here](https://github.com/web3j/web3j-corda/issues).

**Comment by adelRestom** [comment]
Thank you Puneetha for the prompt response and sorry about my late reply; your fix worked.
