### ISSUE TITLE
Contract Function Signature Error with 2-Dimension Static Array (staticarray2)

### ISSUE THREAD

**Issue by mawenpeng** [web3j/web3j#1128]
# _Bug_title_
The signature of contract function verifyTx(**uint[2][2]** memory a, uint b) will be converted to verifyTx(**staticarray2[2]**,uint256) at runtime. 
Thus the method ID of verifyTx(...) is incorrect, and then the transaction input data to run verifyTx(...) is incorrect. Hence the transaction fails.

## Steps To Reproduce
1. Generate wrapper class with web3j util for following cotranct.

pragma solidity ^0.6.0;
contract Verifier {
  uint counter = 0;
  function verifyTx(uint[2][2] memory a, uint b) public returns (bool r) {
    counter = b;
    return true;
  }
  function get() public view returns (uint) {
    return counter;
  }
}

2. Deploy this contract and run function verifyTx(...). 

### Expected behavior
The transaction to run function verifyTx(...) succeeds.

### Actual behavior
The transaction fails with errors:
Exception in thread "main" org.web3j.protocol.exceptions.TransactionException: Transaction has failed with status: 0x0. Gas used: 23378. (not-enough gas?)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:372)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:345)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:339)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:334)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:401)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at com.yongyang.app.DeployVerifier.deployContract(DeployVerifier.java:90)
	at com.yongyang.app.DeployVerifier.main(DeployVerifier.java:43)

## Environment
- Web3j 4.5.11
- Java 64-Bit Server VM (build 25.231-b11, mixed mode)
- Ubuntu 18.04 x64

## Additional context
When debugging, I saw org.web3j.abi.FunctionEncoder.buildMethodSignature(...) returns `verifyTx(staticarray2[2],uint256)`, which is incorrect.

**Comment by AlexandrouR** [comment]
@mawenpeng Hey, what is the transaction error?

**Comment by mawenpeng** [comment]
The error is:
Exception in thread "main" org.web3j.protocol.exceptions.TransactionException: Transaction has failed with status: 0x0. Gas used: 25426. (not-enough gas?)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:372)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:345)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:339)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:334)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:401)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at com.yongyang.app.DeployVerifier.deployContract(DeployVerifier.java:90)
	at com.yongyang.app.DeployVerifier.main(DeployVerifier.java:43)

**Comment by mawenpeng** [comment]
@AlexandrouR I updated the descriptions, please review.

**Comment by hea9549** [comment]
is this bug still alive?
