### ISSUE TITLE
Library not working on anfroid <API 26

### ISSUE THREAD

**Issue by Alexinzaz** [web3j/web3j#1156]
# Library not working on anfroid <API 26
2020-02-08 20:56:57.860 4377-4944/com.test.market E/AndroidRuntime: FATAL EXCEPTION: android_0
    Process: com.chicago.market, PID: 4377
    java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-oj.jar)
        at org.web3j.abi.TypeReference.getClassType(TypeReference.java:94)
        at org.web3j.abi.DefaultFunctionReturnDecoder.build(DefaultFunctionReturnDecoder.java:82)
        at org.web3j.abi.DefaultFunctionReturnDecoder.decodeFunctionResult(DefaultFunctionReturnDecoder.java:47)
        at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:49)
        at org.web3j.tx.Contract.executeCall(Contract.java:294)
        at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:300)
        at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:311)
        at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1$Contract(Contract.java:397)
        at org.web3j.tx.-$$Lambda$Contract$oYGWABDpPbmg8SXDB6ogrDJA-Nw.call(lambda)
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
        at com.chicago.remote.quorum.QuorumModule.createUser(QuorumModule.kt:117)

## Steps To Reproduce
Library not working on anfroid <API 26

### Actual behavior
app crashed

## Environment
Android api 1-25

## Additional context

**Comment by Mike-bel** [comment]
I get the same issue on 4.8.7 library. why?
