### ISSUE TITLE
Not able to fetch data from infura in subscription body

### ISSUE THREAD

**Issue by rw026** [web3j/web3j#1193]
# Not able to fetch data from infura in subscription body
I am listening to my contract Transfer events via a websocket connection with an Infura endpoint. When a new transfer event occur on the Blockchain my subscription body gets executed as it should. In the subscription body I make an additional request to infura (with the same websocket) to fetch the details of this Token. This additional request always fails with the Error: `Request with id <number> timed out`

## Steps To Reproduce
Try to retrieve data from Infura in web3j.logNotifications subscription body

### Expected behavior
Retrieve token information from Infura

### Actual behavior
An IOException occurs

## Environment
_Describe the environment in which the issue occurs_
- Web3j version: 4.5.17
- Java 11
- Spring Boot 2.2.6.RELEASE
- Operating System: Windows 10

## Additional context
**Publisher.java**
```java
web3j.logsNotifications(List.of(customToken.getContractAddress()), List.of(EventEncoder.encode(CustomToken.TRANSFER_EVENT)))
                        .subscribe(logNotification -> {
                            Log transferEventLog = logNotification.getParams().getResult();
                            publisher.publishEvent(transferEventLog);
                        }, throwable -> {
                            logger.error("Error in subscription", throwable);
                        }, () -> {
                            logger.info("Complete transfer event subscription");
                        });
```

**Listener.java**
```java
public void transferEventListener(Log transferEvent) {
        // code to parse log -> to get id of token
        // Here I get the IOException
        Tuple2<String, BigInteger> response= customToken._tokens(id).send();
        
        // Further code to handle response
}
```

```
java.io.IOException: Request with id 4 timed out
	at org.web3j.protocol.websocket.WebSocketService.lambda$setRequestTimeout$3(WebSocketService.java:253) ~[core-4.5.17.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by AlexandrouR** [comment]
Any change if you increase the timeout?

**Comment by AlexandrouR** [comment]
stale ..
