### ISSUE TITLE
Using QueuingTransactionReceiptProcessor throws exception when Contract.executeTransaction is called

### ISSUE THREAD

**Issue by mohrezaei** [web3j/web3j#1207]
# Using QueuingTransactionReceiptProcessor throws exception when Contract.executeTransaction is called

## Steps To Reproduce
Use QueuingTransactionReceiptProcessor  and call any contract transactional method.

### Expected behavior
`UnsupportedOperationException` should not be thrown.

### Actual behavior
the following exception is thrown:
```
	java.lang.UnsupportedOperationException: Empty transaction receipt, only transaction hash is available
	at org.web3j.tx.response.EmptyTransactionReceipt.unsupportedOperation(EmptyTransactionReceipt.java:43)
	at org.web3j.tx.response.EmptyTransactionReceipt.getStatus(EmptyTransactionReceipt.java:139)
	at org.web3j.protocol.core.methods.response.TransactionReceipt.isStatusOK(TransactionReceipt.java:161)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:372)
```

## Environment
_Describe the environment in which the issue occurs_
- Web3j version: 4.5.18. 
- Java 11
- Operating System: any

## Additional context
This broke in this commit: https://github.com/web3j/web3j/commit/99e9df1e386a13403a53f2d36009409bc52b4efb#diff-a71774ffb4764fa21a66e2f3dbbe40f7
The code in `TransactionReceipt` was changed from:
```
    public boolean isStatusOK() {
        if (null == status) {
            return true;
        }
```
to 
```
    public boolean isStatusOK() {
        if (null == getStatus()) { // <-- call to getter method that throws the exception
            return true;
        }
```

`EmptyTransactionReceipt` throws `UnsupportedOperationException` on `getStatus()`.

Possible solutions:
Either revert the call to `getStatus()` or override `isStatusOK()` in `EmptyTransactionReceipt`.

**Comment by KohliSuraj** [comment]
I am facing the same issue when using QueuingTransactionReceiptProcessor. Is there a way around it?

**Comment by mohrezaei** [comment]
First create a subclass of `EmptyTransactionReceipt` that overrides `isStatusOK`. Let's call that `FixedEmptyTransactionReceipt`.
Then subclass `QueuingTransactionReceiptProcessor`, override 

```java
    @Override
    public TransactionReceipt waitForTransactionReceipt(String transactionHash)
            throws IOException, TransactionException {
        super.waitForTransactionReceipt(transactionHash);
        return FixedEmptyTransactionReceipt(transactionHash);
    }
```

**Comment by georgmittendorfer** [comment]
Same issue when using NoOpProcessor.

```
CompletableFuture<TransactionReceipt> transactionInProgress = someContract.doSomething(...);
transactionInProgress.thenAccept(...).exceptionally(...);
```
Always leads to the following exception:
```
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Empty transaction receipt, only transaction hash is available
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
        at org.web3j.utils.Async.lambda$run$1(Async.java:40)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.UnsupportedOperationException: Empty transaction receipt, only transaction hash is available
        at org.web3j.tx.response.EmptyTransactionReceipt.unsupportedOperation(EmptyTransactionReceipt.java:43)
        at org.web3j.tx.response.EmptyTransactionReceipt.getStatus(EmptyTransactionReceipt.java:139)
        at org.web3j.protocol.core.methods.response.TransactionReceipt.isStatusOK(TransactionReceipt.java:161)
        at org.web3j.tx.Contract.executeTransaction(Contract.java:375)
```

Problem is here in Contract.java:375:
```
TransactionReceipt receipt =
                send(
                        contractAddress,
                        data,
                        weiValue,
                        gasProvider.getGasPrice(funcName),
                        gasProvider.getGasLimit(funcName),
                        constructor);

        if (!receipt.isStatusOK()) { // throws if EmptyTransactionReceipt
```
