### ISSUE TITLE
ethEstimateGas.getAmountUsed() Error

### ISSUE THREAD

**Issue by csyzhou1037** [web3j/web3j#1216]
# _Issue_title_
ethEstimateGas.getAmountUsed() throws "org.web3j.exceptions.MessageDecodingException"

## _Issue_description_
I picked up a transaction in the pending transaction pool and wanted to get its estimated gas by using ethEstimateGas, my code is shown below (the fields of hash, from, nonce, .gasPrice, gas, to, value, data were extracted from the picked-up transaction)
```
Web3j web3j = Web3j.build(new HttpService());
            // hash: 0xf27ed319f214118180f6122bea37e22899a95c18010c416560e88eeb6fd26d72
            from = "0x01da3542aec2fd8ef345c33f672c89bf1c38abe1";
            nonce = new BigInteger("44", 10);
            gasPrice = new BigInteger("31000000000", 10);
            gas = new BigInteger("367777", 10);
            to = "0x1e0447b19bb6ecfdae1e4ae1694b0c3659614e4e";
            value = new BigInteger("0", 10);
            data = "0xa67a6a45000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a00000000000000000000" +
                    "00000000000000000000000000000000000000000000100000000000000000000000001da3542aec2fd8ef345c33f672c89bf1c38abe100000000000000000000000000000000000000000000000" +
                    "000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000" +
                    "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" +
                    "000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" +
                    "000000000000000000000000000000000000000000000000000000bebc20000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000" +
                    "00000000000000000000000000000000000000000000000000000000001da3542aec2fd8ef345c33f672c89bf1c38abe100000000000000000000000000000000000000000000000000000000000" +
                    "0000000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000000";

            org.web3j.protocol.core.methods.request.Transaction requestTxn = new org.web3j.protocol.core.methods.request.Transaction(from, nonce, gasPrice, gas, to, value, data);
            EthEstimateGas ethEstimateGas = web3j.ethEstimateGas(requestTxn).send();
            ethEstimateGas.getAmountUsed();
```
When I run the above code, I got the "org.web3j.exceptions.MessageDecodingException". 

## _Issue_context_
org.web3j.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
	at org.web3j.utils.Numeric.decodeQuantity(Numeric.java:47)
	at org.web3j.protocol.core.methods.response.EthEstimateGas.getAmountUsed(EthEstimateGas.java:23)
	at pendingTxn.main(pendingTxn.java:44)

**Comment by AlexandrouR** [comment]
@csyzhou1037 Sorry but can't replicate this. It works fine for me, is this still an issue?

**Comment by xellDart** [comment]
@csyzhou1037 I get same error, how I can fix this?

**Comment by maxyou** [comment]
> @csyzhou1037 I get same error, how I can fix this?

look at this:
https://github.com/web3j/web3j/issues/1095#issuecomment-595718384

createFunctionCallTransaction is work for me
