### ISSUE TITLE
Random Filter Exception with Web3J 4.6.4 and Geth v1.9.14-stable-6d74d1e5/linux-amd64/go1.14.2

### ISSUE THREAD

**Issue by kunalbarchha** [web3j/web3j#1218]
Hi, 

I had been struggling with Subscription from a long time. The socket disconnects randomly within few minute to few hours. Had gone through a similar issue here which was dated back to 2018, and also it was fixed. But I am still struggling. Can someone help ? 

I have also tried to synchronize so that entire process runs in the same thread, but somehow I am doing something wrong. 

System: Ubuntu 18.04
Web3J: 4.5.7 
Geth: 1.9.14-stable
Sync: Light. Running on same machine locally. 
32GB RAM, 1.9T HDD, 12vCPU. 

Please check the code snippet as well : 

    @PostConstruct
    public void start() throws OnErrorNotImplementedException, ConnectException {

        WebSocketService socketService = new WebSocketService(config.getMainNetSocket(), true);        web3J();
        log.info("Started >>>>>>> ");

        Web3j web3jSocket = Web3j.build(socketService);
        socketService.connect();

        synchronized (this) {
            Disposable subscription = web3jSocket.transactionFlowable().subscribe(
                    tx ->
                    {
                        log.info("Tx Hash > " + tx.getHash());
                        getTransactionByHash(tx.getHash());

                    }, throwable -> {
                        log.info("Message >>>> " + throwable.getMessage());
                        throwable.printStackTrace();
                    });
        }

## _Log_
    020-06-05 15:05:01.380  INFO 11903 --- [pool-6-thread-1] c.c.e.c.e.services.SubscriptionService   : Got To Address >>>> 0x210ac5deb43ac5da6c3b1c9e5bb02e2f7bd30ee6
    2020-06-05 15:05:01.381  INFO 11903 --- [pool-6-thread-1] c.c.e.c.e.services.SubscriptionService   : Tx Hash > 0x8156ce08cbf2da3e70d6a0376689831250e40fef0cb64641aae3e7c7b0d1f085
    2020-06-05 15:05:01.662  INFO 11903 --- [pool-6-thread-1] c.c.e.c.e.services.SubscriptionService   : Got To Address >>>> 0x18f6bb93069af5051dc03ef00b65db5b24ea9eb9
    2020-06-05 15:05:01.890  WARN 11903 --- [pool-6-thread-3] org.web3j.protocol.core.filters.Filter   : The filter has not been found. Filter id: 15024254281210356192837031431077094624
    2020-06-05 15:05:01.900 ERROR 11903 --- [pool-6-thread-3] org.web3j.protocol.core.filters.Filter   : Error sending request

    org.web3j.protocol.core.filters.FilterException: Error sending request
	at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:189) ~[core-4.5.7.jar:na]
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:104) ~[core-4.5.7.jar:na]
	at org.web3j.protocol.core.filters.Filter.reinstallFilter(Filter.java:154) ~[core-4.5.7.jar:na]
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:136) ~[core-4.5.7.jar:na]
	at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92) ~[core-4.5.7.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_241]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_241]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_241]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_241]
    Caused by: java.io.IOException: Interrupted WebSocket request
	at org.web3j.protocol.websocket.WebSocketService.send(WebSocketService.java:153) ~[core-4.5.7.jar:na]
	at org.web3j.protocol.core.Request.send(Request.java:81) ~[core-4.5.7.jar:na]
	at org.web3j.protocol.core.filters.BlockFilter.sendRequest(BlockFilter.java:34) ~[core-4.5.7.jar:na]
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:59) ~[core-4.5.7.jar:na]
	... 10 common frames omitted
    Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347) ~[na:1.8.0_241]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[na:1.8.0_241]
	at org.web3j.protocol.websocket.WebSocketService.send(WebSocketService.java:150) ~[core-4.5.7.jar:na]
	... 13 common frames omitted`

**Comment by kunalbarchha** [comment]
Any help on this ?

**Comment by holiman** [comment]
Related: https://github.com/ethereum/go-ethereum/issues/21386#issuecomment-694145722

**Comment by kunalbarchha** [comment]
@holiman As per your latest test result, this issue is with Web3J

**Comment by kunalbarchha** [comment]
The issue is resolved by using following logic: 

Web3j web3j=Web3j.build((new HttpService("https://mainnet.infura.io/v3/<Infura Key>")));

    @PostConstruct
    public void getLatestBlock(){

        Thread thread = new Thread();
        BlockNumberEntity entity;
        Optional<BlockNumberEntity> optionalBlockNumberEntity=blockNumberRepository.findTopByIdGreaterThanEqual(1);

        if (optionalBlockNumberEntity.isPresent()) {
            thread.start();
            entity = optionalBlockNumberEntity.get();
            log.info("Last block number from DB >>>> " +entity.getLastBlockNumber());

            web3j.replayPastAndFutureTransactionsFlowable(DefaultBlockParameter.valueOf(entity.getLastBlockNumber().subtract(BigInteger.ONE)))
                    .subscribe(tx -> {
                        entity.setLastBlockNumber(tx.getBlockNumber());
                        log.info("Block Number >>>> " + tx.getBlockNumber());
                        log.info("To Address >>>>> " + tx.getTo());
                        checkWalletAddress(tx.getHash(), tx.getTo());

                    }, exception -> {
                        log.info(exception.getMessage());
                        if (exception != null) {
                            blockNumberRepository.deleteAll();
                            blockNumberRepository.save(entity);
                            thread.interrupt();
                            getLatestBlock();
                        }
                    });
        }
        else{
            thread.start();
            entity=new BlockNumberEntity();
            web3j.transactionFlowable().subscribe(tx -> {
                        entity.setLastBlockNumber(tx.getBlockNumber());
                        log.info("Block Number >>>> " + tx.getBlockNumber());
                        log.info("To Address >>>>> " + tx.getTo());
                        checkWalletAddress(tx.getHash(), tx.getTo());
                    }, exception -> {
                        log.info(exception.getMessage());
                        if (exception != null) {
                            blockNumberRepository.deleteAll();
                            blockNumberRepository.save(entity);
                            thread.interrupt();
                            getLatestBlock();
                        }
                    });
        }

What this code does: 

Initiate on deployment, and it checks DB if there is any last block sync available. If not, it will start syncing with TransactionFlowable. When exception occurs, it stores the last successfully block sync number in DB, closes the threads, and restarts the method. This time, the last blocknumber is available in DB, so it will use replayPastTransaction API and start syncing from there. On Exception, it will again update the lastBlocknumber in DB, close thread, and start the method. 

Have been using it from last 72 hours, and achieved desired results.

**Comment by kunalbarchha** [comment]
Work Around for the issue mentioned above.
