### ISSUE TITLE
NPE from Filter.java inside getInitialFilterLogs() when ethLog.getLogs() == null 

### ISSUE THREAD

**Issue by AndreasLarssons** [web3j/web3j#1264]
# NPE from Filter.java inside getInitialFilterLogs() when ethLog.getLogs() == null 
Using web3j.ethLogFlowable(ethFilter).subscribe(log -> {}) will trigger a NPE when ethLog = maybeRequest.get().send(); returns empty result

## Steps To Reproduce
The below code will trigger the exception if the topic / contract you subscribe to makes the underlying call return a null result

`EthFilter ethFilter = new EthFilter(DefaultBlockParameter.valueOf(
DefaultBlockParameter.valueOf(SOMEBLOCK_HERE)),
DefaultBlockParameterName.LATEST,
"A CONTRACT ID").addSingleTopic(EventEncoder.encode(TRANSFER_EVENT));
web3j.ethLogFlowable(ethFilter).subscribe(log -> {});`

### Expected behavior
Do something like 
`Optional.ofNullable(ethLog.getLogs()).ifPresent(this::process);`
instead of throwing a NPE since that will trigger a RxJava exception and to me this case doesn't sound like an exceptional state and should instead be handled as no events triggered on the subscriber rather than an .onError() state.

### Actual behavior
When I am running this method `web3j.ethLogFlowable(ethFilter).subscribe(log -> {})`and the underlying method that get's called `getInitialFilterLogs()` and the `maybeRequest.get().send()` succeeds but with an empty result. `ethLog.getLogs()` will be null which will trigger an NPE inside LogFilter.java

`java.lang.NullPointerException: null`
`at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:46) ~[core-5.0.0.jar:na]`

## Environment
- Web3j version
- Java 11
- Mac

## Additional context
Stacktrace
```
java.lang.NullPointerException: null
	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:46) ~[core-5.0.0.jar:na]
	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:119) ~[core-5.0.0.jar:na]
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:69) ~[core-5.0.0.jar:na]
	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:89) ~[core-5.0.0.jar:na]
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogFlowable$2(JsonRpc2_0Rx.java:79) ~[core-5.0.0.jar:na]
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.Flowable.subscribe(Flowable.java:14882) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288) ~[rxjava-2.2.17.jar:na]
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253) ~[rxjava-2.2.17.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by mvp83** [comment]
same issue

**Comment by snakewarhead** [comment]
The `ethLog` maybe has error in response of  `eth_getFilterLogs`.

So need to add the codes before `process(ethLog.getLogs())`:

```java
if (ethLog.getError() != null) {
    throwException(ethLog.getError())
}
```

**Comment by CodingBen** [comment]
Nobody find this problem?  I just meet this.

**Comment by yukunyi** [comment]
同样的问题，（4.8.5）

**Comment by mohamedelshami** [comment]
Closing this due to inactivity, please reopen if the above issue is still valid
