### ISSUE TITLE
Error when using structs with multiple array-types

### ISSUE THREAD

**Issue by wolfposd** [web3j/web3j#1283]
# Error when using structs with multiple array-types

```
java.lang.RuntimeException: Error processing transaction request: VM Exception while processing transaction: revert
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:162)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:81)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:127)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:366)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:349)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:343)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:338)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:409)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
```

## Steps To Reproduce

- use a struct with multipe array types as stated smat contract code below
- use demo java code to execute
- running with ganache-cli

### Expected behavior
working transactions wiht multi-array-structs

### Actual behavior
only single-array structures work, see examples below

## Environment
_Describe the environment in which the issue occurs_
- Web3j version: 4.7.0
- Java version: all of them
- Ganache CLI v6.11.0 (ganache-core: 2.12.1)
- Operating System: osx

## Additional context
```
 pragma solidity >=0.6.0;
pragma experimental ABIEncoderV2;


contract web3jdemo {

    struct Good {
        uint32 something;
        string metadata;
    }
    struct GoodAlso {
        uint32 something;
        bytes metadata;
    }
    struct Bad {
        bytes pubkey;
        uint32 something;
        bytes metadata;
    }
    struct BadBad {
        bytes pubkey;
        bytes metadata;
    }

    Good[] goodEntries;
    GoodAlso[] goodAlsoEntries;
    Bad[] badEntries;
    BadBad[] badbadEntries;

    function addGood(Good memory _g) public {
        goodEntries.push(_g);
    }
    function addGoodAlso(GoodAlso memory _b) public {
        goodAlsoEntries.push(_b);
    }
    function addBad(Bad memory _b) public {
        badEntries.push(_b);
    }
    function addBadBad(BadBad memory _b) public {
        badbadEntries.push(_b);
    }

}
```

java code:
```
/ * standard web3j setup before here*/
Web3jdemo contract = Web3jdemo.deploy(web3j, credentials, contractgasprovider).send();

contract.addGood(new Good(new BigInteger("7"), "my string")).send(); // works
contract.addGoodAlso(new GoodAlso(new BigInteger("7"), "my string".getBytes())).send(); //works
contract.addBad(new Bad("my string".getBytes(), new BigInteger("7"), "my string".getBytes())).send(); // fails : "VM Exception while processing transaction: revert"
contract.addBadBad(new BadBad("my string".getBytes(), "my string".getBytes())).send(); // fails : "VM Exception while processing transaction: revert"
```

**Comment by esaulpaugh** [comment]
is it just that the ABI is malformed? maybe crosscheck it using https://github.com/esaulpaugh/headlong

**Comment by wolfposd** [comment]
here is two raw outputs for the function-call `contract.addBadBad("my string".bytes, "my string".bytes)`


truffle:
```
{
  "jsonrpc": "2.0",
  "id": 71,
  "method": "eth_sendTransaction",
  "params": [
    {
      "from": "0x9038156f749d5cfd5a89e0e5ac16808583e8594f",
      "gas": "0x6691b7",
      "gasPrice": "0x4a817c800",
      "to": "0x6e39beda1905ca39a65fe3ac9387a07cf81bac03",
      "data": "0xbafe1e3800000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000096d7920737472696e67000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000096d7920737472696e670000000000000000000000000000000000000000000000"
    }
  ]
}
```

and from web3j
```
{
  "jsonrpc": "2.0",
  "method": "eth_sendRawTransaction",
  "params": [
    "0xf901490784f461090083895440946e39beda1905ca39a65fe3ac9387a07cf81bac0380b8e4bafe1e3800000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000096d7920737472696e67000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000096d7920737472696e6700000000000000000000000000000000000000000000001ca070fa9f436423efca41d930280ff00c2e6aa549835657426d18a444b04216176ca006ad749f26418570e44d1c3d66880fff62f6b606d94d5e7569e1c79f6e916877"
  ],
  "id": 3
}
```

**Comment by SweeXordious** [comment]
There is a [PR](https://github.com/web3j/web3j/pull/1321) solving this and adding support for arrays of structs and also multiple structs/arrays of structs multiple returns. Please take a look on it and let us know your feedback.
Thank you and have a great day.

**Comment by SweeXordious** [comment]
Fixed and merged 🎉
