### ISSUE TITLE
TransactionTimeoutException when deploying Contract to private blockchain using Web3j (java client)

### ISSUE THREAD

**Issue by solartis** [web3j/web3j#129]
I am using Web3j for interacting with my private blockchain network created in Azure.

I have created contracts using Remix and Metamask and was able to view that Contract from Java.

However I was not able to deploy or create contract from Java. I followed the instructions from the link https://github.com/web3j/web3j.

I keep getting the error "Transaction receipt was not generated after 600 seconds for transaction" caused by "org.web3j.protocol.exceptions.TransactionTimeoutException"

Full stack-trace
```
Exception in thread "main" java.util.concurrent.ExecutionException: org.web3j.protocol.exceptions.TransactionTimeoutException: Transaction receipt was not generated after 600 seconds for transaction: 0x73b0feb7d982333542c01230083a12b8234d0bbaaeac20e44a11cd4eb83abf44
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.solartis.bc.Sample.main(Sample.java:41)
```

My main method:
```java
Web3j web3 = Web3j.build(new HttpService("http://xxxxxxx.westus.cloudapp.azure.com:8545/"));
Credentials credentials = WalletUtils.loadCredentials("MyPassword", "/Path/to/wallet");
System.out.println(credentials.getAddress());
Token contract = Token.deploy(web3,credentials,BigInteger.valueOf(3000000),BigInteger.valueOf(3000000),BigInteger.valueOf(0)).get();
System.out.println(contract.getContractAddress());
```

Token.sol
```javascript
pragma solidity ^0.4.0;

contract Token {
    mapping (address => uint) public balances;

    function Token() {
        balances[msg.sender] = 1000000;
    }

    function transfer(address _to, uint _amount) {
        if (balances[msg.sender] < _amount) {
            throw;
        }

        balances[msg.sender] -= _amount;
        balances[_to] += _amount;
    }
}
```

Token.java
```java
public final class Token extends Contract {
    private static final String BINARY = "6060604052341561000f57600080fd5b5b600160a060020a0333166000908152602081905260409020620f424090555b5b6101678061003f6000396000f300606060405263ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166327e235e38114610048578063a9059cbb14610086575b600080fd5b341561005357600080fd5b61007473ffffffffffffffffffffffffffffffffffffffff600435166100b7565b60405190815260200160405180910390f35b341561009157600080fd5b6100b573ffffffffffffffffffffffffffffffffffffffff600435166024356100c9565b005b60006020819052908152604090205481565b73ffffffffffffffffffffffffffffffffffffffff3316600090815260208190526040902054819010156100fc57600080fd5b73ffffffffffffffffffffffffffffffffffffffff338116600090815260208190526040808220805485900390559184168152208054820190555b50505600a165627a7a7230582081fd33c821a86127abf00c9fafe2e14e4db6279ab9dd788e3ad3597d2280b6cf0029";

    private Token(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    private Token(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }

    public Future<Uint256> balances(Address param0) {
        Function function = new Function("balances", 
                Arrays.<Type>asList(param0), 
                Arrays.<TypeReference<?>>asList(new TypeReference<Uint256>() {}));
        return executeCallSingleValueReturnAsync(function);
    }

    public Future<TransactionReceipt> transfer(Address _to, Uint256 _amount) {
        Function function = new Function("transfer", Arrays.<Type>asList(_to, _amount), Collections.<TypeReference<?>>emptyList());
        return executeTransactionAsync(function);
    }

    public static Future<Token> deploy(Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit, BigInteger initialWeiValue) {
        return deployAsync(Token.class, web3j, credentials, gasPrice, gasLimit, BINARY, "", initialWeiValue);
    }

    public static Future<Token> deploy(Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit, BigInteger initialWeiValue) {
        return deployAsync(Token.class, web3j, transactionManager, gasPrice, gasLimit, BINARY, "", initialWeiValue);
    }

    public static Token load(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return new Token(contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    public static Token load(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return new Token(contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }
}
```

**Comment by conor10** [comment]
The gas limit & gas price parameters shouldn't be the same. I'd expect the gas price to be much larger then 3,000,000, but this is dictated by the configuration of your private network.

web3j does provide default values which are in the Contract & ManagedTransaction classes.

**Comment by solartis** [comment]
Yes you were right, I was not giving a proper GAS_LIMIT and GAS_PRICE. As per your suggestion I updated my code to something like this and it worked. Thanks for your help
```java
			BigInteger GAS = Contract.GAS_LIMIT;
			BigInteger GAS_PRICE = Contract.GAS_PRICE;
			BigInteger ETH = BigInteger.valueOf(0);
                        Token contract = Token.deploy(web3,credentials,GAS_PRICE,GAS,ETH).get();
                        System.out.println("Deployed Contract at "+ contract.getContractAddress());
```
