### ISSUE TITLE
When dealing with tuple[], the method signature differs with web3 js generated

### ISSUE THREAD

**Issue by james-ray** [web3j/web3j#1293]
the related content in abi file :
```
 {
      "constant": true,
      "inputs": [
        {
          "components": [
            {
              "name": "x",
              "type": "bytes32"
            },
            {
              "name": "y",
              "type": "bytes32"
            }
          ],
          "name": "y",
          "type": "tuple[]"
        },
        {
          "name": "realtimeQuery",
          "type": "bool"
        }
      ],
      "name": "simulateAccounts",
      "outputs": [
        {
          "name": "ff",
          "type": "uint256"
        },
        {
          "name": "epoch",
          "type": "uint256"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    },
```

release-4.8.0 cannot handle this abi, the error is 
type == null

I modify the generated java wrapper code of the contract, I use the DynamicArray wrap the generated tuple class Struct0. But the call fails, I have a js project which can run the call successfully, so I debug the js signature message is 
```
simulateAccounts((bytes32,bytes32)[],bool)
```
while whatever I tried in web3j, the signature message is 
```
simulateAccounts(struct1[],bool)
```
I dig into the code, and find the reason is , in js,  the codes in web-utils
```
var _flattenTypes = function(includeTuple, puts)
{
    // console.log("entered _flattenTypes. inputs/outputs: " + puts)
    var types = [];

    puts.forEach(function(param) {
        if (typeof param.components === 'object') {
            if (param.type.substring(0, 5) !== 'tuple') {
                throw new Error('components found but type is not tuple; report on GitHub');
            }
            var suffix = '';
            var arrayBracket = param.type.indexOf('[');
            if (arrayBracket >= 0) { suffix = param.type.substring(arrayBracket); }
            var result = _flattenTypes(includeTuple, param.components);
            // console.log("result should have things: " + result)
            if(_.isArray(result) && includeTuple) {
                // console.log("include tuple word, and its an array. joining...: " + result.types)
                types.push('tuple(' + result.join(',') + ')' + suffix);
            }
            else if(!includeTuple) {
                // console.log("don't include tuple, but its an array. joining...: " + result)
                types.push('(' + result.join(',') + ')' + suffix);
            }
            else {
                // console.log("its a single type within a tuple: " + result.types)
                types.push('(' + result + ')');
            }
        } else {
            // console.log("its a type and not directly in a tuple: " + param.type)
            types.push(param.type);
        }
    });

    return types;
};
```
recursively flatten all structs into primitive types.
while in java, the codes in FunctionEncoder:
```
    protected static String buildMethodSignature(
            final String methodName, final List<Type> parameters) {

        final StringBuilder result = new StringBuilder();
        result.append(methodName);
        result.append("(");
        final String params =
                parameters.stream().map(Type::getTypeAsString).collect(Collectors.joining(","));
        result.append(params);
        result.append(")");
        return result.toString();
    }
```
call each parameter's getTypeAsString, 
if you set the parameter to DynamicStruct, the getTypeAsString will flatten the types into a list, 
```
simulateAccounts((bytes32,bytes32),(bytes32,bytes32),bool)
```
that is not what wanted.
But if you set the parameter to DynamicArray<Struct0>, the result is 
```
simulateAccounts(struct0[],bool)
```
the type inside does not get flattened, I find the reasons is, the codes in DynamicArray:
```
  @Override
    public String getTypeAsString() {
        return AbiTypes.getTypeAString(getComponentType()) + "[]";
    }
```
And the getComponentType() just return the type in the DynamicArray, and that is Struct0. 
To modify the type in DynamicArray, I try the style like this constuctor
```
 @Deprecated
    @SafeVarargs
    @SuppressWarnings({"unchecked"})
    public DynamicArray(T... values) {
        super((Class<T>) AbiTypes.getType(values[0].getTypeAsString()), values);
    }
```
It is Deprecated, so I cannot use it directly, I write the code 
```
 Tuple2<BigInteger, BigInteger> result = (Tuple2<BigInteger, BigInteger>) zsc.simulateAccounts(new DynamicArray((Class<ZSC.Struct1>) AbiTypes.getType(yArr[0].getTypeAsString()),yArr), false).send();
```
But the execution result is an error:
```
java.lang.UnsupportedOperationException: Unsupported type encountered: (bytes32,bytes32)
	at org.web3j.abi.datatypes.AbiTypes.getType(AbiTypes.java:366)
	at org.web3j.abi.datatypes.AbiTypes.getType(AbiTypes.java:136)
	at com.nenglian.infra.library.zether.Client.burn(Client.java:200)
	at com.nenglian.infra.library.zether.ClientTest.burn(ClientTest.java:91)
```

**Comment by james-ray** [comment]
I wrote a sub class DynamicStructArray extends DynamicArray, just to override the method getTypeAsString

```
package com.nenglian.infra.library.web3jext;

import org.web3j.abi.datatypes.DynamicArray;
import org.web3j.abi.datatypes.Type;

import java.util.List;

public class DynamicStructArray<T extends Type> extends DynamicArray<T> {

    public DynamicStructArray(Class<T> type, T... values) {
        super(type, values);
    }

    @Override
    public String getTypeAsString() {
        return value.get(0).getTypeAsString() + "[]";
    }
}
```
Now the call succeed.

**Comment by james-ray** [comment]
But now the decode fails, the actual response is 
```
"outputs": [
        {
          "components": [
            {
              "name": "x",
              "type": "bytes32"
            },
            {
              "name": "y",
              "type": "bytes32"
            }
          ],
          "name": "accounts",
          "type": "tuple[2][]"
        },
        {
          "name": "epoch",
          "type": "uint256"
        }
```
js can decode the result with type tuple[2][], while java can't.

**Comment by SweeXordious** [comment]
There is a [PR](https://github.com/web3j/web3j/pull/1321) solving this and adding support for arrays of structs and also multiple structs/arrays of structs multiple returns. Please take a look on it and let us know your feedback.
Thank you and have a great day.

**Comment by SweeXordious** [comment]
Fixed and merged 🎉
