### ISSUE TITLE
java.io.IOException: closed

### ISSUE THREAD

**Issue by fcorneli** [web3j/web3j#1342]
I have this very simple example:
```java
Web3jService service = new HttpService();
Web3j web3j = Web3j.build(service);
String clientVersion = web3j.web3ClientVersion().send().getWeb3ClientVersion();
```
that works as expected on web3j version 4.8.2, but fails on version 4.8.3 with:
```
java.io.IOException: closed
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:154)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:522)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:129)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:246)
	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1271)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:810)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2924)
	at org.web3j.protocol.Service.send(Service.java:50)
	at org.web3j.protocol.core.Request.send(Request.java:87)
```
Maybe related to https://github.com/web3j/web3j/commit/cd3ca7234ad1c45da422258494399226a2e10220 ?

**Comment by fcorneli** [comment]
This indeed happens against a `geth`client node.
https://github.com/web3j/web3j/pull/1344

**Comment by SweeXordious** [comment]
That was a change that broke this functionality in our latest release. This [PR](https://github.com/web3j/web3j/pull/1344) is fixing it and adding test for it so that it won't get broken again.
Let us know your input on the PR if we should be testing more stuff. 
Thank you and have a great day.

**Comment by fcorneli** [comment]
Would like to test this out. Unfortunately
```
./gradlew publishToMavenLocal
```
gives me another error:
```
Execution failed for task ':abi:signMavenPublication'.
> Cannot perform signing task ':abi:signMavenPublication' because it has no configured signatory
```

**Comment by SweeXordious** [comment]
try with `./gradlew publishToMavenLocal -x sign`

**Comment by fcorneli** [comment]
With the suggested PR, the issue seems to be solved.

**Comment by spolnik** [comment]
hey @SweeXordious  - seems this issue still happens for Besu Client. We used so far 4.6.3 web3j + okhttp 4.7.2, and now switched to:

* web3j 4.8.2 okhttp 4.9.0 works OK
* web3j 4.8.4 okhttp 4.9.0 fails with:
java.io.IOException: closed

There is no other changes, besu works all the time during tests (if that will help, we want to verify smart contract by using ethGetCode method and it fails on it during read from besu).

**Comment by ESchouten** [comment]
Same issue using Geth, last working version is 4.8.2
