### ISSUE TITLE
TransactionException: Cannot unmarshal invalid hex string when deploying contract

### ISSUE THREAD

**Issue by kinson603** [web3j/web3j#1373]
When I tried to deploy my contract on my private node on geth. I got this error:
```
org.web3j.protocol.exceptions.TransactionException: Transaction 0x70fed47c9d291f0818ff239be085b2dc3a87f436f56b9c0b6750e568a24dbdf1 has failed with status: 0x0. Gas used: 6721975. Revert reason: 'invalid argument 0: json: cannot unmarshal invalid hex string into Go struct field CallArgs.data of type hexutil.Bytes'.
	at org.web3j.tx.Contract.executeTransaction(Contract.java:377)
	at org.web3j.tx.Contract.create(Contract.java:422)
	at org.web3j.tx.Contract.deploy(Contract.java:456)
	at org.web3j.tx.Contract.deploy(Contract.java:506)
	at org.web3j.tx.Contract.lambda$deployRemoteCall$5(Contract.java:549)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at java_ethereum.ContractController.deployContract(ContractController.java:41)```
```
My java code looks something like this:
```
Web3j web3 = Web3j.build(new HttpService("http://localhost:8545"));
Credentials credentials = WalletUtils.loadCredentials("", "path/to/geth/keystore");
String contractAddress = deployContract(web3, credentials);
MyContract myContract = loadContract(contractAddress, web3, credentials);
@SuppressWarnings("deprecation")
	private String deployContract(Web3j web3, Credentials credentials) throws Exception{
	    return EthsyShipContract.deploy(web3, credentials, GAS_PRICE, GAS_LIMIT).send().getContractAddress();
	}
```

My web3j should be the latest version(4.8.4), I am not sure if I have missed anything. Any help would be appreciated.

**Comment by kinson603** [comment]
I have also posted a question on Ethereum Stack Exchange as well.
[https://ethereum.stackexchange.com/questions/94123/transactionexception-cannot-unmarshal-invalid-hex-string-when-deploying-contrac](url)

**Comment by kinson603** [comment]
The problem is solved now. It is because web3j CLI does not accept binary from remix-IDE.
