### ISSUE TITLE
Web3j run with exception after install

### ISSUE THREAD

**Issue by KunPengRen** [web3j/web3j#1413]
# _Bug_title_
Web3j run with exception after install

## Steps To Reproduce
Run web3j command in terminal

### Actual behavior
run with a exception

## Environment
_Describe the environment in which the issue occurs_
- Web3j lasted(1.4.1)
- Java: 1.8.0_275
- Operating System: macos bigsur

## Additional context
_Add any other context about the problem here._
output
```
 web3j
              _      _____ _
             | |    |____ (_)
__      _____| |__      / /_
\ \ /\ / / _ \ '_ \     \ \ |
 \ V  V /  __/ |_) |.___/ / |
  \_/\_/ \___|_.__/ \____/| |
                         _/ |
                        |__/
by Web3Labs
Exception in thread "main" Unexpected character 'EOI(null)' at position '3', expecting '[DOT]'
	at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
	at com.github.zafarkhaja.semver.VersionParser.parseVersionCore(VersionParser.java:288)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:255)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
	at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)
	at org.web3j.console.services.Updater.promptIfUpdateAvailable(Updater.java:35)
	at org.web3j.console.Web3jCommand.parse(Web3jCommand.java:108)
	at org.web3j.console.Web3j.main(Web3j.java:18)
```

**Comment by yasseralaa** [comment]
this should be reported in https://github.com/web3j/web3j-cli
