### ISSUE TITLE
java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC during wallet creation using DexGuard build

### ISSUE THREAD

**Issue by W3-Mimo** [web3j/web3j#1433]
# java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC during wallet creation using DexGuard build

## Issue_description
My application has a wallet creation feature So that I am using the following code

`WalletUtils.generateLightNewWalletFile("<Password>", destinationFile);`

This line is working fine in debug mode but when I am preparing the release app with **DexGuard** build then I am facing this exception `java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC` on the executing of the above line.

I am using `setupBouncyCastle()` in Application class

```
private void setupBouncyCastle() {
        final Provider provider = Security.getProvider(BouncyCastleProvider.PROVIDER_NAME);
        if (provider == null) {
            // Web3j will set up the provider lazily when it's first used.
            return;
        }
        if (provider.getClass().equals(BouncyCastleProvider.class)) {
            // BC with same package name, shouldn't happen in real life.
            return;
        }
        // Android registers its own BC provider. As it might be outdated and might not include
        // all needed ciphers, we substitute it with a known BC bundled in the app.
        // Android's BC has its package rewritten to "com.android.org.bouncycastle" and because
        // of that it's possible to have another BC implementation loaded in VM.
        Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME);
        Security.insertProviderAt(new BouncyCastleProvider(), 1);
    }
```

And my dexguard rule is

```
-dontwarn java8.util.**
-dontwarn jnr.posix.**
-dontwarn com.kenai.**

#-keep class org.bouncycastle.**
-dontwarn org.bouncycastle.jce.provider.X509LDAPCertStoreSpi
-dontwarn org.bouncycastle.x509.util.LDAPStoreHelper

# Web3j
#-keep class org.** { *; }

-keep class * extends org.web3j.abi.TypeReference
-keep class * extends org.web3j.abi.datatypes.Type
-keep class com.intermeshnetworks.service.MainActivity {*;}

#-dontwarn java.lang.SafeVarargs
-dontwarn org.slf4j.**

-dontwarn com.fasterxml.jackson.databind.**
#-keep class org.** { *; }
-keep class com.fasterxml.jackson.core.** { *; }
-keep interface com.fasterxml.jackson.core { *; }
-keep public class * extends com.fasterxml.jackson.core.*
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.
-keep class com.fasterxml.jackson.databind.ObjectMapper.
-keep class com.fasterxml.jackson.databind.** { *; }
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker${ *; }
-keep interface com.fasterxml.jackson.databind { *; }
-keep public class * extends com.fasterxml.jackson.databind.*
-keep class com.fasterxml.jackson.annotation.** { *; }
-keep interface com.fasterxml.jackson.annotation.** { *; }

-keep class org.** { *; }
-keep class org.bouncycastle.** { *; }
-keep class org.web3j.** { *; }
```

## Environment
- Web3j version - `implementation 'org.web3j:core:4.8.4'`
- Java or Android version - Using Java version - **4.8.4** because the last couple of updates are providing on Java.
- Operating System - Computer operating system is - **Ubuntu [20.04]** and the **Android studio version is - 4.2.1**

## I have added the crash log for better understanding 
```
W: java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC
W:     at sun.security.jca.GetInstance.getService(GetInstance.java:87)
W:     at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
W:     at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:286)
W:     at o.getTotalPaddingLeft.read(:2069)
W:     at o.getMeasuredHeight.RemoteActionCompatParcelizer(:1067)
W:     at o.getWidth.read(:45)
W:     at o.getHeight.setContentView(:63)
W:     at o.setScrollY.run(:1133)
W:     at java.lang.Thread.run(Thread.java:760)
```

**Comment by andrii-kl** [comment]
@W3-Mimo  Use web3j function to generate a keys `Keys.createEcKeyPair()`
In your situation KeyPairGenerator is java base class, your java implementation can override or change Security provider as they want. 
Let me know if you still have a problem.
