### ISSUE TITLE
Pending transaction filter stops listening after several minutes

### ISSUE THREAD

**Issue by assafY** [web3j/web3j#144]
I am listening for pending transactions as follows (code is in Kotlin):

```
fun start() {
        web3.pendingTransactionObservable().subscribe( { tx ->
            onTx(tx)
        })
    }

    fun onTx(tx: Transaction) {
        logger.debug("new tx " + tx.hash)
    }
```

After a few minutes, transactions stop coming through. This does not seem to happen when using `transactionOvservable()`.  I have spent several hours trying to figure out why this issue is happening with no luck. Has anyone experienced this before?

**Comment by clowdrgn** [comment]
I have experienced this and asked on gitter. Here is my exception message . 
`java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135) ~[na:1.8.0_131]
    at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$pendingTransactionObservable$13(JsonRpc2_0Rx.java:75) ~[core-2.1.0.jar!/:na]
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) [rxjava-1.2.4.jar!/:1.2.4]
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395) ~[rxjava-1.2.4.jar!/:1.2.4]
    at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355) ~[rxjava-1.2.4.jar!/:1.2.4]
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846) ~[rxjava-1.2.4.jar!/:1.2.4]
    at org.web3j.protocol.core.Request.lambda$observable$4(Request.java:82) ~[core-2.1.0.jar!/:na]
    at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar!/:1.2.4]
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) ~[rxjava-1.2.4.jar!/:1.2.4]
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) ~[rxjava-1.2.4.jar!/:1.2.4]
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.2.4.jar!/:1.2.4]
    at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$null$7(JsonRpc2_0Rx.java:42) ~[core-2.1.0.jar!/:na]
    at org.web3j.protocol.core.filters.PendingTransactionFilter.process(PendingTransactionFilter.java:29) ~[core-2.1.0.jar!/:na]
    at org.web3j.protocol.core.filters.Filter.run(Filter.java:45) ~[core-2.1.0.jar!/:na]
    at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$run$10(JsonRpc2_0Rx.java:62) ~[core-2.1.0.jar!/:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: org.web3j.protocol.core.methods.response.EthTransaction.class
    at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.2.4.jar!/:1.2.4]
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) [rxjava-1.2.4.jar!/:1.2.4]
    ... 17 common frames omitted`
If ethGetTransactionByHash return null, pendingTransactionObservable will exit and throw this exception. And I add retry() , onErrorResumeNext() ,these method can't recover observable from error.The only way to make observable continue is that add a for loop out of observal.
And @conor10 tell me ethGetTransactionByHash will return null if the transaction has not been mined and added to the blockchain (https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash)

**Comment by assafY** [comment]
Thanks for your answer! That explains it. Seems strange to me to call getTransactionByHash for pending transactions. @conor10 should I keep this issue open?

**Comment by clowdrgn** [comment]
![image](https://user-images.githubusercontent.com/9083547/28664046-aa5defe2-72f1-11e7-8d37-01b73ac99159.png)
But this method is obvservable pending transaction through a scheduled PendingTransactionFilter, Why ethTransaction.getTransaction().get() is must added to the blockchain so that it can be emit to obvservable? I don't understand

**Comment by clowdrgn** [comment]
![image](https://user-images.githubusercontent.com/9083547/28664630-a6227900-72f3-11e7-85c1-bfc7e8ccd87c.png)
Emmm....The exception is come from here. send() is called by getTransactionByHash,but return null.And pending transaction obvservable  exit...

**Comment by assafY** [comment]
I'm thinking ethPendingTransactionHashObservable provides tx hashes, which are then sent to getTransactionByHash to get the full transaction object, but that returns null if the tx hasn't been mined yet which must happen very often. In my manual tests the error would occur anywhere between 30 second to 10 minutes of running.

There should be a way to get transaction data for pending transactions, but perhaps that is not supported by the library.

**Comment by clowdrgn** [comment]
Yes,that's correct. the Observable use eth_newPendingTransactionFilter to get pending transaction hash.But it seems there is no way to find pending transaction data through tx hash.Or maybe there is a way but I have not find it

**Comment by clowdrgn** [comment]
There is a issue in https://github.com/ethereum/go-ethereum/issues/14893. It seems the root cause that we get null from a pending transaction hash.

**Comment by assafY** [comment]
Looks like this issue was fixed now, do you still experience this problem?

**Comment by jeremie-H** [comment]
Hello !
I pull the last geth client, and i have the same issue :(

**Comment by antikantian** [comment]
@jeremie-H I'm having the same issue.  I thought subscribing to the observable like this might help (Scala code):

`pendingTransactions
      .map(tx => EitherT(tx).bimap(logError, pushTx).value)
      .retry
      .subscribe()`

The observable still fails after some time.  As a workaround, I stick the subscription in its own process, and then monitor the number of pending transactions, and then check the count at certain intervals.  If the last count equals the current count, then I simply kill the thread and then restart it.  This is, of course, just a terrible hack to see if I can get some consistency.

Have you tried the pending transaction filter connected to a parity node, instead of geth?  I seem to recall that when connected via IPC to parity, the pending transaction observable is much more responsive.  I'm currently installing parity on a fresh system and I'll let you know in a few hours if that's indeed the case.

**Comment by jeremie-H** [comment]
@antikantian Hi ! what about your connection with parity, i've tried, but there is another issue that i related here : #197

**Comment by antikantian** [comment]
@jeremie-H Unfortunately, switching to parity didn't seem to help.  I've gotten the pending transaction filter working with geth to an extent that is acceptable for my use-case, but connected to IPC.  Polling via HTTP RPC seemed to be much more unreliable.  At any rate, I just went with refreshing a timer every time a new pending transaction is observed, and then checking this timer at regular intervals (i.e., average block time + n%).  If no transactions came across, I just refresh the observable.  It's been a few days, and this fix has been pretty stable.

I thought about other fixes.  For example, since I stream all data to Redis for processing, I was going to modify the geth source to just send all pending transactions to Redis directly; however, I figured that would 1) add to my workload, and 2) be a pain when dealing with geth updates.  I was also thinking about trying out some other web3 libraries in Python or C++ to see if they were more reliable (which would indicate that the problem lies with Web3j, and not geth itself.  However, since my solution seems to work for now, I put that on the back burner until I have more time to play around.

**Comment by conor10** [comment]
It would be useful to see the JSON-RPC logs for this issue - that will tell me definitively if the issue is in the ethereum client or web3j.

**Comment by conor10** [comment]
The following integration test [ObservableIT](https://github.com/web3j/web3j/blob/master/integration-tests/src/test/java/org/web3j/protocol/core/ObservableIT.java) provides a really easy mechanism to run different filters, and will log all JSON-RPC requests if you run it from the web3j project.

Just make sure you increase the event count and timeout parameters before you run it.

**Comment by antikantian** [comment]
@conor10 Thanks for letting us know.  I'll try to get some logs either tonight or tomorrow and post them here.

**Comment by jeremie-H** [comment]
Hi @conor10 and thanks for your integration test,
i've run it, and here's my logs :
```
01:12:23.593 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
01:12:23.594 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
01:12:23.594 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 66
01:12:23.594 [main] DEBUG org.web3j.protocol.http.HttpService - 
01:12:23.594 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":1}
01:12:23.595 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (66-byte body)
01:12:23.618 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (23ms)
01:12:23.618 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
01:12:23.618 [main] DEBUG org.web3j.protocol.http.HttpService - Transfer-Encoding: chunked
01:12:23.618 [main] DEBUG org.web3j.protocol.http.HttpService - Date: Mon, 23 Oct 2017 23:12:23 GMT
01:12:23.619 [main] DEBUG org.web3j.protocol.http.HttpService - 
01:12:23.619 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","result":"0xfa1","id":1}

01:12:23.619 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (42-byte body)
01:12:23.651 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
01:12:23.651 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
01:12:23.651 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 75
01:12:23.651 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
01:12:23.651 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xfa1"],"id":1}
01:12:23.651 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> END POST (75-byte body)
01:12:23.661 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (9ms)
01:12:23.661 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
01:12:23.661 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Transfer-Encoding: chunked
01:12:23.661 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Date: Mon, 23 Oct 2017 23:12:23 GMT
01:12:23.661 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
01:12:23.661 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","result":["0x0a77e2c12cc00c2bd3e6e3a0b042b43677734902eb5c484884e83f2df5538d57"],"id":1}

01:12:23.661 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (105-byte body)
01:12:23.673 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
01:12:23.673 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
01:12:23.673 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 139
01:12:23.673 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
01:12:23.673 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0x0a77e2c12cc00c2bd3e6e3a0b042b43677734902eb5c484884e83f2df5538d57",true],"id":1}
01:12:23.673 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> END POST (139-byte body)
01:12:33.675 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
01:12:33.676 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
01:12:33.676 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
01:12:33.676 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 74
01:12:33.676 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
01:12:33.676 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0xfa1"],"id":1}
01:12:33.676 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> END POST (74-byte body)
01:12:33.677 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (0ms)
01:12:33.677 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
01:12:33.677 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Transfer-Encoding: chunked
01:12:33.678 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - Date: Mon, 23 Oct 2017 23:12:33 GMT
01:12:33.678 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
01:12:33.678 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","result":true,"id":1}

01:12:33.678 [pool-2-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (39-byte body)
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:211)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:104)
	at org.web3j.protocol.Service.send(Service.java:30)
	at org.web3j.protocol.core.Request.send(Request.java:68)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at org.web3j.protocol.core.RemoteCall.lambda$observable$0(RemoteCall.java:51)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at org.web3j.protocol.core.filters.BlockFilter.process(BlockFilter.java:32)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:84)
	at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 41 more

```

**Comment by conor10** [comment]
So the underlying timeout issue should be addressed in the release I've just put out https://github.com/web3j/web3j/releases/tag/v3.2.0.

However, regarding the pending transactions, I can't see any way to request pending transactions explicitly from nodes. So we have two options:

1. Only return the transaction hash, and don't attempt to pull the transaction back
2. Attempt to pull the pending transaction back, returning an [EmptyTransactionReceipt](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/response/EmptyTransactionReceipt.java) if it cannot be found

Thoughts?

**Comment by antikantian** [comment]
Ok, so I realized there were a few issues with the the pending transaction filter that rendered it untenable for my use-case.  These issues, as far as I can tell, are related to geth and parity, and not specifically web3j related.  That is, whenever a transaction is in the queue, and it is replaced with a transaction with the same nonce, but a higher gas price, the new transaction hash doesn't appear in the filter.

The only way that I can see to get the actual and complete list of pending transactions is via Parity's `parity_pendingTransactions` method, and Geth's `txpool_content` method.  The obvious downside to this is that, especially recently, when the pending tx pool has 20k+ transactions, the data pulled is 20MB+.  Depending on how often you're pulling that data to construct a live list of pending transactions, that is incredibly resource-intensive.  

I didn't see any other options, so I ended up going this route.  I re-wrote the entire implementation from the ground-up in Scala to have more control over the fine-grained details, which I couldn't optimize quite enough.  I then re-implemented that logic in Rust, which is an order of magnitude faster, but it's still a massively wasteful way to go about it.

I know that Parity is working on a [re-implementation of their transaction pool](https://github.com/paritytech/parity/pull/6994), which might alleviate some of this difficulty.

**Comment by eepstein** [comment]
If this is still open, I'd personally go with #1: just returning the TX Hash.

Use case I have is finding any pending txs for an account - e.g., ones that might be "stuck" due to low gasPrice or similar - and then being able to "nix" those by resubmitting with effectively a no-op.

But, I'm flexy, either #1 or #2 will fit the bill, #1 just seems easier (do the simplest thing that will work ;-)   )

**Comment by joanesespanol** [comment]
I am experiencing the same behavior/exception when subscribing to the pending transaction observable:
<pre>
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$pendingTransactionObservable$12(JsonRpc2_0Rx.java:86)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
        at org.web3j.protocol.core.RemoteCall.lambda$observable$7(RemoteCall.java:51)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
        at org.web3j.protocol.core.filters.PendingTransactionFilter.process(PendingTransactionFilter.java:32)
        at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:84)
        at org.web3j.protocol.core.filters.Filter.lambda$run$18(Filter.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: org.web3j.protocol.core.methods.response.EthTransaction.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
        ... 18 common frames omitted
</pre>

Any idea when we could expect a fix?  Either proposed solution would work, as long as the process doesn't die, and we don't have to restart, re-create the filter, etc.

**Comment by joanesespanol** [comment]
Question for the group: when creating a pending transaction observable, how often do you pull (the default is 15 seconds if I remember correctly), and how fast can you pull before hitting limits?

**Comment by antikantian** [comment]
@joanesespanol Do you mean limits from the RPC host?  I don't have any numbers for geth, but with Parity I've tried times down to 50ms, and it wasn't a problem.  This observation isn't web3j specific, just my observations from implementations that we've written in Rust and Scala.

**Comment by joanesespanol** [comment]
@antikantian Thanks for the information, good to know :+1:
