### ISSUE TITLE
Contract method always encounter an ExecutionException

### ISSUE THREAD

**Issue by zeromem** [web3j/web3j#149]
I use web3j's Contract wrapper to control smart contract in a private ethereum blockchain.
here is my code:
this is my contract:
```
pragma solidity ^0.4.0;


contract SimpleStorage {
    uint storedData;

    function set(uint x) {
        storedData = x;
    }

    function get() constant returns (uint retVal) {
        return storedData;
    }
} 
```

then I deploy this contract on ethereum, and use contract wrapper to call `set()` and `get()` method.
```
SimpleStorage contract = SimpleStorage.load(...)
Future<TransactionReceipt> set = contract.set(new Uint256(BigInteger.valueOf(1000)));
// this is OK!
set.get();

Future<Uint256> result = contract.get();

// Boom! ExecutionException!
result.get();
```

here, I always encounter an ExecutionException when fetching value from result.get()!

Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.zeromem.lifecode.blockchain.contract.ContractHelloWorld.main(ContractHelloWorld.java:74)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:173)
	at org.web3j.tx.Contract.lambda$executeCallSingleValueReturnAsync$21(Contract.java:162)
	at org.web3j.utils.Async.lambda$run$28(Async.java:20)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by conor10** [comment]
Did you get to the bottom of this? I just ran up the following [test](https://github.com/web3j/web3j/blob/master/src/integration-test/java/org/web3j/protocol/scenarios/SimpleStorageContractIT.java) against Ropsten & didn't experience any issues.

**Comment by zeromem** [comment]
@conor10 after some test, I guess I didn't deploy contract correctly using web3j. Now I deploy contract in geth console, and I can use the contract without any problem.
Thanks.

**Comment by conor10** [comment]
Great - closing.
