### ISSUE TITLE
Error while listening to USDT token : org.web3j.protocol.core.filters.FilterException:

### ISSUE THREAD

**Issue by lalitkumar-tech** [web3j/web3j#1504]
Hi Team

I am subscribing to USDT token with parameter Latest block and initial blocks, like the below code:-
DefaultBlockParameter.valueOf(BigInteger.valueOf(web3jServiceUtils.getLatestInitialBlock().longValue())),
							DefaultBlockParameterName.LATEST).subscribe.......
						
							
I have created a listener for USDT token at the runtime, and listening all pending transactions of USDT token and match the transaction that has belong to my user's, but on production am getting this filterExcetion:-
org.web3j.protocol.core.filters.FilterException: Error sending request
	at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:156)
	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:101)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:53)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:73)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogObservable$2(JsonRpc2_0Rx.java:65)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	
	
I am using 3.4.0 version as mentioned below:
org.web3j:core:3.4.0
	
So can someone help me with this.
Should I need to use any other updated version of web3j library to avoid this Exception?

**Comment by mahima-manik** [comment]
@lalitkumar-tech Please try with the latest web3j release 4.8.7
