### ISSUE TITLE
how to connect bsc test network and localhost:8545

### ISSUE THREAD

**Issue by jianchengwang** [web3j/web3j#1519]
# _Issue_title_
how to connect bsc test network and localhost:8545

## _Issue_description_
here is my load contract code
```java
 PerformanceToken contract = PerformanceToken.load(
                this.contractAddress, web3j, transactionManager, new StaticGasProvider(this.gasPrice, DefaultGasProvider.GAS_LIMIT));
```
first i use hardhat start localhost node, my config is 
```yaml
web3j:
  enable: true
  nodeService: http://127.0.0.1:8545
  chainId: 31337
```
but it can't work throw 
```
Caused by: org.web3j.ens.EnsResolutionException: Unable to determine sync status of node
	at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:78)
	at org.web3j.ens.EnsResolver.resolve(EnsResolver.java:88)
	at org.web3j.tx.Contract.resolveContractAddress(Contract.java:720)
	at org.web3j.tx.Contract.<init>(Contract.java:102)
	at org.web3j.tx.Contract.<init>(Contract.java:84)
	at com.shangchain.web3j.contract.PerformanceToken.<init>(PerformanceToken.java:134)
	at com.shangchain.web3j.contract.PerformanceToken.load(PerformanceToken.java:561)
	at com.shangchain.web3j.client.Web3jClient.loadPerformanceToken(Web3jClient.java:58)
	at com.shangchain.web.controller.bsc.BscController.<init>(BscController.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 24 common frames omitted
Caused by: org.web3j.ens.EnsResolutionException: Node is not currently synced
	at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:73)
	... 37 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:58999', transport: 'socket'
```
```java
   boolean isSynced() throws Exception {
        EthSyncing ethSyncing = web3j.ethSyncing().send();
        if (ethSyncing.isSyncing()) {
            return false;
        } else {
            EthBlock ethBlock =
                    web3j.ethGetBlockByNumber(DefaultBlockParameterName.LATEST, false).send();
            long timestamp = ethBlock.getBlock().getTimestamp().longValueExact() * 1000;

            return System.currentTimeMillis() - syncThreshold < timestamp;
        }
    }
```
then i change to bsc network, here is my config
```yaml
web3j:
  enable: true
  nodeService: https://data-seed-prebsc-1-s1.binance.org:8545
  chainId: 97
```
but it also cant work, trow
```
Caused by: org.web3j.ens.EnsResolutionException: Unable to determine sync status of node
	at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:78)
	at org.web3j.ens.EnsResolver.resolve(EnsResolver.java:88)
	at org.web3j.tx.Contract.resolveContractAddress(Contract.java:720)
	at org.web3j.tx.Contract.<init>(Contract.java:102)
	at org.web3j.tx.Contract.<init>(Contract.java:84)
	at com.shangchain.web3j.contract.PerformanceToken.<init>(PerformanceToken.java:134)
	at com.shangchain.web3j.contract.PerformanceToken.load(PerformanceToken.java:561)
	at com.shangchain.web3j.client.Web3jClient.loadPerformanceToken(Web3jClient.java:58)
	at com.shangchain.web.controller.bsc.BscController.<init>(BscController.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 24 common frames omitted
Caused by: org.web3j.ens.EnsResolutionException: Unable to resolve ENS registry contract for network id: 97
	at org.web3j.ens.Contracts.resolveRegistryContract(Contracts.java:33)
	at org.web3j.ens.EnsResolver.lookupResolver(EnsResolver.java:140)
	at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:75)
	... 37 common frames omitted
```
```java
    public static String resolveRegistryContract(String chainId) {
        final Long chainIdLong = Long.parseLong(chainId);
        if (chainIdLong.equals(ChainIdLong.MAINNET)) {
            return MAINNET;
        } else if (chainIdLong.equals(ChainIdLong.ROPSTEN)) {
            return ROPSTEN;
        } else if (chainIdLong.equals(ChainIdLong.RINKEBY)) {
            return RINKEBY;
        } else {
            throw new EnsResolutionException(
                    "Unable to resolve ENS registry contract for network id: " + chainId);
        }
    }
```
## _Issue_context_
now i am confused and cant do any more, so help me pls.

**Comment by jianchengwang** [comment]
my fault, i use springboot yaml config, 0x start string will convert to be number, so it's my config error, it should be 
```yaml
web3j:
  contractAddress: "0x81cE80b17eAddB5A9938461C07fd9F45c87B97d2"
```
not
```yaml
web3j:
  contractAddress: 0x81cE80b17eAddB5A9938461C07fd9F45c87B97d2
```
