### ISSUE TITLE
Unable to use NoOpProcessor

### ISSUE THREAD

**Issue by dparmar** [web3j/web3j#1548]
# Error using NoOpProcessor
I would like to use [NoOpProcessor](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/response/NoOpProcessor.java), but it seems to fail with following exception.

## Stack trace
```java
java.lang.UnsupportedOperationException: Empty transaction receipt, only transaction hash is available
	at org.web3j.tx.response.EmptyTransactionReceipt.unsupportedOperation(EmptyTransactionReceipt.java:43)
	at org.web3j.tx.response.EmptyTransactionReceipt.getStatus(EmptyTransactionReceipt.java:139)
	at org.web3j.protocol.core.methods.response.TransactionReceipt.isStatusOK(TransactionReceipt.java:167)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:375)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:350)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:344)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:339)
```
## Possible Fix
I think overriding following method in [EmptyTransactionReceipt](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/response/EmptyTransactionReceipt.java) should fix this.
```java
@Override
public boolean isStatusOK() {
    return true;
}
```

**Comment by det-mark** [comment]
I think the underlying issue is the same or similar to the one described in #1207

**Comment by cauta** [comment]
i faced this issue too
