### ISSUE TITLE
Transfer.sendFunds() with invalid toAddress results in: "Node is not currently synced"

### ISSUE THREAD

**Issue by tingwongsom** [web3j/web3j#1564]
Code:

        TransactionReceipt transferReceipt = Transfer.sendFunds(
                web3j, credentials,
                "0x693a3D9278381B8EB2c6BEbd89880291E3a7E6b8\n",
                BigDecimal.ONE, Convert.Unit.WEI)  // 1 wei = 10^-18 Ether
                .send();

You see I paste address with newline backslash n by mistake. No good!

Stack trace:

```
Exception in thread "main" org.web3j.ens.EnsResolutionException: Unable to determine sync status of node
	at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:78)
	at org.web3j.ens.EnsResolver.resolve(EnsResolver.java:88)
	at org.web3j.tx.Transfer.send(Transfer.java:79)
	at org.web3j.tx.Transfer.send(Transfer.java:56)
	at org.web3j.tx.Transfer.lambda$sendFunds$0(Transfer.java:94)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at org.web3j.sample.Application.run(Application.java:81)
	at org.web3j.sample.Application.main(Application.java:50)
Caused by: org.web3j.ens.EnsResolutionException: Node is not currently synced
	at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:73)
	... 7 more
```

This error verry confuse. Node (Ganache) is sync!

Using latest version: 

        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.8.9</version>
        </dependency>

**Comment by andrii-kl** [comment]
@tingwongsom  The problem is that if you have not valid address, system try to work with it like with a ENS name. 
I have changed an exception message on "_ENS resolver exception, unable to execute request:_", so I think behavior should became more clear.
