### ISSUE TITLE
Smart Contract Wrapper Generation in error with functions with parameters without name

### ISSUE THREAD

**Issue by fraspadafora** [web3j/web3j#16]
Hi,
I was using web3j (0.5.1) to create the Smart Contract wrapper.
But I have this error:

> Exception in thread "main" java.lang.IllegalArgumentException: not a valid name: 
	at com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at com.squareup.javapoet.ParameterSpec.builder(ParameterSpec.java:83)
	at com.squareup.javapoet.MethodSpec$Builder.addParameter(MethodSpec.java:379)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.createFunctionDefinitions(SolidityFunctionWrapperGenerator.java:191)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.generateSolidityWrappers(SolidityFunctionWrapperGenerator.java:159)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.generate(SolidityFunctionWrapperGenerator.java:124)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.main(SolidityFunctionWrapperGenerator.java:66)
	at com.nttdata.ethereum.marketplace.Test.main(Test.java:26)

I debugged the code, and I noticed that in the ABI there was a function like this:

> {"constant":true,"inputs":[{"name":"","type":"address"}],"name":"insuranceWithdraw","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"}

This function is created by Solidity because of I'm using a public map

> mapping (address => unit) public insuranceWithdraw;

I think the best thing is to give a default name, with an increasing number.

**Comment by conor10** [comment]
I'm presuming you updated to the latest release?

**Comment by fraspadafora** [comment]
Yes, I was using an old version.

**Comment by RakeshSainiRk** [comment]
3.2 is the latest release ri8 ?
