### ISSUE TITLE
"eventValues" is null on ethLogFlowable

### ISSUE THREAD

**Issue by lmyslinski** [web3j/web3j#1611]
# "eventValues" is null on ethLogFlowable

## Steps To Reproduce
Compile smart contract available at https://github.com/PRHunter-io/bounty-contracts/blob/master/contracts/BountyFactory.sol
Export the ABI with `npx hardhat export-abi`
Compile the contract ABI with `web3j generate solidity -a abi/contracts/BountyFactory.sol/BountyFactory.json -p io.prhunter.api.contract -o .`
Try to get an event with `bountyFactory.bountyCreatedEventFlowable(EthFilter()).blockingFirst()`

The contract is deployed on Ropsten testnet at "0x5Ad2A671E49ebdc90C4c70f3d137a040aa6e1B99".
I've tried using both Infura and Alchemy nodes. 

### Expected behavior
A flowable of events is retrieved

### Actual behavior
```

java.lang.NullPointerException: Cannot invoke "org.web3j.tx.Contract$EventValuesWithLog.getNonIndexedValues()" because "eventValues" is null
	at io.prhunter.api.contract.BountyFactory$2.apply(BountyFactory.java:88) ~[main/:na]
	at io.prhunter.api.contract.BountyFactory$2.apply(BountyFactory.java:82) ~[main/:na]
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:547) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:471) ~[rxjava-2.2.21.jar:na]
	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:49) ~[core-4.8.9.jar:na]
	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:123) ~[core-4.8.9.jar:na]
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:69) ~[core-4.8.9.jar:na]
	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:89) ~[core-4.8.9.jar:na]
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogFlowable$2(JsonRpc2_0Rx.java:79) ~[core-4.8.9.jar:na]
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Flowable.blockingFirst(Flowable.java:5698) ~[rxjava-2.2.21.jar:na]
```

## Environment

Web3j 4.8.9
web3j CLI 1.4.1
openjdk version "17.0.1" 2021-10-19 LTS
aarch64 M1

## Additional context

Contract on etherscan:
https://ropsten.etherscan.io/address/0x5Ad2A671E49ebdc90C4c70f3d137a040aa6e1B99

I've tried getting to the bottom of this, apparently the null is returned here: 
Contract.java
```
   public static EventValues staticExtractEventParameters(Event event, Log log) {
        final List<String> topics = log.getTopics();
        String encodedEventSignature = EventEncoder.encode(event);
        if (topics == null || topics.size() == 0 || !topics.get(0).equals(encodedEventSignature)) {
            return null;
        }

        List<Type> indexedValues = new ArrayList<>();
        List<Type> nonIndexedValues =
                FunctionReturnDecoder.decode(log.getData(), event.getNonIndexedParameters());

        List<TypeReference<Type>> indexedParameters = event.getIndexedParameters();
        for (int i = 0; i < indexedParameters.size(); i++) {
            Type value =
                    FunctionReturnDecoder.decodeIndexedValue(
                            topics.get(i + 1), indexedParameters.get(i));
            indexedValues.add(value);
        }
        return new EventValues(indexedValues, nonIndexedValues);
    }
```
`!topics.get(0).equals(encodedEventSignature)` returns false, but I can't understand why that is. We do get a non-empty log from the node as far as I've seen in the debugger.

I also tried using the gradle plugin to generate the contract code but it doesn't work on ARM yet due to a node issue so I can't check that

**Comment by kutasms** [comment]
encodedEventSignature is the subject hash code processed by EventEncoder.It is recommended that you change the log level to debug, so that you can see more information about RPC requests and replies.
In the subscribe callback function of ethlogflowable, you usually need to use **address** and **topic[0]** as conditions to determine the ownership of the log

**Comment by lmyslinski** [comment]
@kutasms How would I get my hands on those? These seem to be web3j internals, the contract wrapper generated for me for this functions looks as follows:

```
public Flowable<BountyCreatedEventResponse> bountyCreatedEventFlowable(EthFilter filter) {
        return web3j.ethLogFlowable(filter).map(new Function<Log, BountyCreatedEventResponse>() {
            @Override
            public BountyCreatedEventResponse apply(Log log) {
                Contract.EventValuesWithLog eventValues = extractEventParametersWithLog(BOUNTYCREATED_EVENT, log);
                BountyCreatedEventResponse typedResponse = new BountyCreatedEventResponse();
                typedResponse.log = log;
                typedResponse.bounty = (String) eventValues.getNonIndexedValues().get(0).getValue();
                return typedResponse;
            }
        });
    }
 ```
 So the actual call on the application layer looks like this:
 `bountyFactory.bountyCreatedEventFlowable(EthFilter())`
 I've uplodaded the JSON RPC call log onto pastebin, it seems to be fine blockchain-wise `https://pastebin.com/nQKAnqkj`

**Comment by lmyslinski** [comment]
So I managed to work around this issue and later realized that I can't use events for my use case anyway. Sadly I got rid of the code already, but the solution is as simple as modifying the filter code in the generated contract to only parse events which don't have null in `getNonIndexedValues`
