### ISSUE TITLE
Empty transaction receipt, only transaction hash is available

### ISSUE THREAD

**Issue by efeint01** [web3j/web3j#1636]
I am getting this error when I try to send tokens.
But is the token still being sent? How does it both give an error and send the token?

Code:
```
TransactionReceiptProcessor transactionReceiptProcessor = new NoOpProcessor(web3j);
                    TransactionManager transactionManager = new RawTransactionManager(
                            web3j, credentials, isMainNet() ? (byte) 56 : (byte) 97, transactionReceiptProcessor);
                    Erc20TokenWrapper contract = Erc20TokenWrapper.load(tokenContractAddress, web3j, transactionManager, gasPrice, gasLimit);

                    String tokenName = contract.name().getValue();
                    String tokenSymbol = contract.symbol().getValue();
                    BigInteger decimalCount = contract.decimals().getValue();
                    BigDecimal formattedAmount = BalanceUtils.amountByDecimal(tokenAmount, new BigDecimal(decimalCount));
                    TransactionReceipt mReceipt = contract.transfer(new Address(to_Address), new Uint256(formattedAmount.toBigInteger()));
                    return Single.just(mReceipt.getTransactionHash());
```

**Comment by efeint01** [comment]
This issue was caught in the latest version of Web3j Android 4.8.7. Any possible solution?

**Comment by efeint01** [comment]
The issue is fixed.
How?

Use **PollingTransactionReceiptProcessor**


Changed:
`TransactionReceiptProcessor transactionReceiptProcessor = new PollingTransactionReceiptProcessor(web3j,3000,40);
`
To:
`TransactionReceiptProcessor transactionReceiptProcessor = new NoOpProcessor(web3j);
`

Detail:
We now use Polling Transaction Receipt Processor instead of NoOpProcesser.


```
long sleepDuration = 3000;
int attemps = 40
```
```
`new Polling Transaction Receipt Processor(web3j,sleepDuration,attemps)`
```

// The transaction will check until it receives the receipt. If unsuccessful, it will try again after 3000 Milliseconds, If the number of attempts exceeds 41, an exception will be raised.

It's that simple guys. Good work.

**Comment by Rabindra5** [comment]
@efeint01 , i am facing the empty transaction receipt issue while i am trying to transfer token using transaction manager  and if i use ERC20 contract , it always give the protocol exception error (Transaction receipt couldn't generate after 600 seconds) , is there anything wrong in my code ?
My code :
Web3j web3 = Web3j.build(new HttpService("https://ropsten.infura.io/v3/xxxxxxxxxxxx"));
            Credentials creds = Credentials.create(privateKey);
            String tokenAddress = "0x............."
            ERC20 contract = ERC20.load(tokenAddress, web3, creds, new StaticGasProvider(new BigInteger('25000000000'), new BigInteger('5500000')));
            String tokenName = contract.name().send()
            String tokenSymbol = contract.symbol().send()
            def balanceToken = contract.balanceOf(creds.address).send()
            resp = contract.transfer("0xXXXX", new BigInteger('100')).send()

Exception : 
org.web3j.protocol.exceptions.TransactionException: Transaction receipt was not generated after 600 seconds for transaction: 0x4e730fab8621396ef520d976b777db62ea79e30b7b402d6206dba47d59ccc2fc
at org.web3j.tx.response.PollingTransactionReceiptProcessor.getTransactionReceipt(PollingTransactionReceiptProcessor.java:61)
at org.web3j.tx.response.PollingTransactionReceiptProcessor.waitForTransactionReceipt(PollingTransactionReceiptProcessor.java:38)
at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:181)
at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:81)
at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:128)
at org.web3j.tx.Contract.executeTransaction(Contract.java:367)
at org.web3j.tx.Contract.executeTransaction(Contract.java:350)
at org.web3j.tx.Contract.executeTransaction(Contract.java:344)
at org.web3j.tx.Contract.executeTransaction(Contract.java:339)
at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:410)
at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
at org.web3j.protocol.core.RemoteCall$send.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
at com.elintegro.coinface.cft.BuyCftService.$tt__buyCFT(BuyCftService.groovy:246)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
