### ISSUE TITLE
Example App 'Main.java' Doesn't Work

### ISSUE THREAD

**Issue by timmolter** [web3j/web3j#1643]
# Example App 'Main.java' Doesn't Work
<https://github.com/web3j/examples/blob/6ae2d81d8b848f00ac555f7ce7a1bff415bf3bac/rx/src/main/java/org/web3j/examples/rx/Main.java>

## Example Failures
Using "**https://eth.nownodes.io**" as the HttpsService, I get:

```
2022-02-25 14:45:25,953 INFO com.coinomi.backend.coinapi.web3j.Main [] - Doing simpleFilterExample
org.web3j.exceptions.**MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0**
```
Using "**https://api.avax.network/ext/bc/C/rpc**" as the HttpsService, I get:

```
2022-02-25 14:49:35,273 INFO com.coinomi.backend.coinapi.web3j.Main [] - Doing simpleFilterExample
2022-02-25 14:49:35,665 WARN org.web3j.protocol.core.filters.Filter [] - **The filter has not been found. Filter id: 49354003257830227768111075816136767394**
2022-02-25 14:49:35,775 WARN org.web3j.protocol.core.filters.Filter [] - The filter has not been found. Filter id: 58243268776595416597073463598443545089
2022-02-25 14:49:35,871 WARN org.web3j.protocol.core.filters.Filter [] - The filter has not been found. Filter id: 230082338096681244438173512169597547534
2022-02-25 14:49:35,962 WARN org.web3j.protocol.core.filters.Filter [] - The filter has not been found. Filter id: 120970104462448088074131844047553706838
2022-02-25 14:49:36,061 WARN org.web3j.protocol.core.filters.Filter [] - The filter has not been found. Filter id: 235527725903109150397968557868519243076
.....
```
Using "**https://polygon-rpc.com**" as the HttpsService, I get:

```
2022-02-25 14:52:22,354 INFO com.coinomi.backend.coinapi.web3j.Main [] - Doing simpleFilterExample
2022-02-25 14:52:22,776 ERROR org.web3j.protocol.core.filters.Filter [] - Error sending request
org.web3j.protocol.core.filters.FilterException: Invalid request: **the method eth_getFilterChanges does not exist/**is not available
	at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:194)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:144)
	at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | org.web3j.protocol.core.filters.FilterException: Filter with id '224686026180904171065386732608669088168' failed to uninstall
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
......
```

## I'm a Newbie to Web3J
Maybe I am expecting the wrong things, but as I understand, all EVM chains (Eth, Polygon, Avalanche, etc) should provide a unified API and web3 is supposed to provide chain interchangeability and a unified API. Above, I tried 3 chains and got 3 different (disappointing) results. Is it my fault or is it a bug in Web3j or is there an issue with the Geth forks for AVAX and Polygon?

Thanks in advance.

**Comment by FangshuoCao** [comment]
Hi, I’ve tested the examples using Web3j v4.14.0 (the latest release) against multiple endpoints:

    Sepolia via Infura: https://sepolia.infura.io/v3/<API-KEY>
    Polygon Amoy via Infura: https://polygon-amoy.infura.io/v3/<API-KEY>
    Avalanche C-Chain: https://api.avax.network/ext/bc/C/rpc

All examples worked without issues. Please try using the latest release and it should work.
