### ISSUE TITLE
Error sending request

### ISSUE THREAD

**Issue by TaoZhengning** [web3j/web3j#1707]
# _Bug_title_
The filter has not been found. Filter id: 166682167469336393203912601347145251590
Error sending request

## Environment
_Describe the environment in which the issue occurs_
- Web3j 3.6.0
- Java 1.8
- OkHttpClient 3.14.9

## Additional context
2022-05-12 15:33:32 28869774 [pool-2-thread-2] WARN 
				o.w.protocol.core.filters.Filter - The filter has not been found. Filter id: 166682167469336393203912601347145251590 
2022-05-12 15:33:32 28869808 [pool-2-thread-2] ERROR
				o.w.protocol.core.filters.Filter - Error sending request 
org.web3j.protocol.core.filters.FilterException: Error sending request
	at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:176)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:92)
	at org.web3j.protocol.core.filters.Filter.reinstallFilter(Filter.java:140)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:123)
	at org.web3j.protocol.core.filters.Filter.lambda$run$25(Filter.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.InterruptedIOException: interrupted
	at okio.Timeout.throwIfReached(Timeout.java:146)
	at okio.Okio$1.write(Okio.java:76)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
	at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.java:190)
	at okhttp3.internal.connection.Exchange.finishRequest(Exchange.java:101)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:86)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:104)
	at org.web3j.protocol.Service.send(Service.java:34)
	at org.web3j.protocol.core.Request.send(Request.java:71)
	at org.web3j.protocol.core.filters.LogFilter.sendRequest(LogFilter.java:31)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:51)
	... 10 common frames omitted

**Comment by Vorh** [comment]
Hello!
I have the same bug:

org.web3j.core: 4.9.2
java: 1.8
com.squareup.okhttp3.okhttp: 4.9.3

Error log: 

org.web3j.protocol.core.filters.FilterException: Error sending request
        at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:198) ~[core-4.9.2.jar!/:na]
        at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:135) ~[core-4.9.2.jar!/:na]
        at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92) ~[core-4.9.2.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.io.IOException: Request with id 930 timed out
        at org.web3j.protocol.websocket.WebSocketService.lambda$setRequestTimeout$3(WebSocketService.java:252) ~[core-4.9.2.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        ... 4 common frames omitted

**Comment by SuperEdison** [comment]
Hello!
I have the same bug:

org.web3j.core: 4.9.2
java: 17
websocket

Error log:

[2022-06-06 15:13:01,944] [DEBUG] org.web3j.protocol.websocket.WebSocketClient [WebSocketConnectReadThread-33] [] edm bsc-wallet - Received message {"jsonrpc":"2.0","id":13,"error":{"code":-32000,"message":"filter not found"}} from server wss://host/testnet/ws
[2022-06-06 15:13:01,945] [WARN] org.web3j.protocol.core.filters.Filter [pool-4-thread-4] [] edm bsc-wallet - The filter has not been found. Filter id: 213413323863888855792690532216788381593
