### ISSUE TITLE
When pass a string array to contract, the first value of array is not correct.

### ISSUE THREAD

**Issue by regeawj** [web3j/web3j#1719]
When I try to pass a string array to solidity, there are 2 errors:
1) if the first value is too long, ex."abcfdsadsaddsadsadsadsassssssssssssssss",
    when I retrieve the this array from solidity contract, I will get below error:
 Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: Range [1280, -454759964) out of bounds for length 2432
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at realb.com.contract.App.main(App.java:61)
Caused by: java.lang.StringIndexOutOfBoundsException: Range [1280, -454759964) out of bounds for length 2432
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
        at java.base/java.lang.String.substring(String.java:2703)
        at org.web3j.abi.TypeDecoder.decodeDynamicBytes(TypeDecoder.java:303)
        at org.web3j.abi.TypeDecoder.decodeUtf8String(TypeDecoder.java:310)
        at org.web3j.abi.TypeDecoder.decode(TypeDecoder.java:101)
        at org.web3j.abi.TypeDecoder.decodeArrayElements(TypeDecoder.java:410)
        at org.web3j.abi.TypeDecoder.decodeDynamicArray(TypeDecoder.java:345)
        at org.web3j.abi.DefaultFunctionReturnDecoder.build(DefaultFunctionReturnDecoder.java:89)
        at org.web3j.abi.DefaultFunctionReturnDecoder.decodeFunctionResult(DefaultFunctionReturnDecoder.java:47)
        at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:49)
        at org.web3j.tx.Contract.executeCall(Contract.java:294)
        at org.web3j.tx.Contract.executeCallMultipleValueReturn(Contract.java:331)
        at realb.com.contractAbi.RealB.access$1(RealB.java:1)
        at realb.com.contractAbi.RealB$12.call(RealB.java:116)
        at realb.com.contractAbi.RealB$12.call(RealB.java:1)
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
        at org.web3j.utils.Async.lambda$run$1(Async.java:38)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2) if the the first value is short, it works, but when I trieve value from solidity contract, the the first value is not correct.
    this is the test data:
    List<String> addr = new ArrayList<String>();
     addr.add("abc");    
addr.add("1e0ewrewreqwreqwrwqrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr");
addr.add("789901eewrewreqwreqwrwqrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr");
addr.add("901eewrewreqwreqwrwqrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr");

3) I'm using web3j 5.0.0 version, using maven
 <dependency>
      <groupId>org.web3j</groupId>
      <artifactId>core</artifactId>
      <version>5.0.0</version>
    </dependency>

    <dependency>
      <groupId>org.web3j</groupId>
      <artifactId>codegen</artifactId>
      <version>5.0.0</version>
    </dependency>

I saw there is a similiar issue: issue number is 1251, you resolved similiar issue, but it doesn't work on 5.0.0 version?
https://github.com/web3j/web3j/issues/1251

Thank you so much!

Jian

**Comment by GiveMeTestEther** [comment]
@regeawj could you please check the version of web3j you are using?
Because you are writing that you are using version 5.0.0 but the current version is 4.9.4.
