### ISSUE TITLE
UnsupportedClassVersionError on running web3j

### ISSUE THREAD

**Issue by SergeyKodzha** [web3j/web3j#175]
I downloaded latest 2.3.1 version of web3j.When I run it throws following stacktrace:
D:\Desktop\web3\bin>web3j
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/web3j
sole/Runner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

Looks like my jdk version is incompatible with the one this tool was compiled.Could you reveal which jdk version I need to run it?

**Comment by conor10** [comment]
Java 8+. Use web3j-android if you want to work with prior version.
