### ISSUE TITLE
Support of custom type

### ISSUE THREAD

**Issue by Gelassen** [web3j/web3j#1776]
In my ERC721 contract implementation I use metadata with custom type like this:

```
struct Value {
    string _offer;
    uint256 _availableSince;
    uint256 _availabilityEnd;
    bool _isConsumed;
    uint256 _lockedUntil;
}
```

At this moment I trying to mint this token which consumes Value type instance as an input parameter:

```
        fun safeMint(to: String, value: Value, uri: String): Function {
            return Function(
                "safeMint",
                listOf<Type<*>>(Address(to), ValueType(value), Utf8String(uri)),
                Collections.emptyList()
            )
        } 
```
Web3j doesn't process it as is with error: 
```

    java.lang.UnsupportedOperationException: Type cannot be encoded: class com.example.wallet.DebugActivity$ValueType
        at org.web3j.abi.TypeEncoder.encode(TypeEncoder.java:87)
        at org.web3j.abi.DefaultFunctionEncoder.encodeParameters(DefaultFunctionEncoder.java:54)
        at org.web3j.abi.DefaultFunctionEncoder.encodeFunction(DefaultFunctionEncoder.java:39)
```

So the question is do you have example that show web3j use case of consuming struct data types? Is it possible at all? 

By exploring the issue I have found [this check of supported types](https://github.com/web3j/web3j/issues/1591) (which is lack of struct), but also source code of `DynamicStruct` which might fit my use case, but at very deep end of my day I am too sleepy to investigate more this direction. 

Thank you for any information on this topic.

**Comment by Gelassen** [comment]
Web3j provides such classes as `StaticStruct` and `DynamicStruct` which allows to implement your own struct as java class.
