### ISSUE TITLE
java.io.IOException: closed

### ISSUE THREAD

**Issue by mscongdon** [web3j/web3j#1777]
Issue [#1432](https://github.com/web3j/web3j/issues/1342) originally addressed this.  Geth client nodes were causing the `InputStream` to be closed, and you resolved this in this [PR](https://github.com/web3j/web3j/pull/1344)

However, the issue still remains in org.web3j core 4.9.4, but only when `includeRawResponses` is `true`.

```
boolean includeRawResponses = true;
Web3jService service = new HttpService("http://localhost:8454", includeRawResponses);
Web3j web3j = Web3j.build(service);
String clientVersion = web3j.web3ClientVersion().send().getWeb3ClientVersion();
```

```
java.io.IOException: closed
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:154)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:539)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:133)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:256)
	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1655)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1083)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
	at org.web3j.protocol.Service.send(Service.java:50)
	at org.web3j.protocol.core.Request.send(Request.java:87)
```

I see that [HttpService.java](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/http/HttpService.java) is handling the IO streams differently based on that boolean.  Is there possibly a bug in its `buildInputStream` method?

Thanks, and kind regards,
Michael

**Comment by mohamedelshami** [comment]
Hi @mscongdon I haven't seen this issue myself before, so unsure if I can reproduce it. Does this issue still persist?

**Comment by mscongdon** [comment]
I'll revisit this in the next week and get back to you with more details.  But from what I tested before - and haven't changed anything since, this was 100% reproducible based on that includeRawResponses flag.  I'll also reconfirm that my build is using version 4.9.4.

**Comment by mscongdon** [comment]
I confirmed I still see this same exception.  I've tried multiple EVM-based blockchains' RPC endpoints.  For example: https://bsc-dataseed.binance.org/

```
try {
  SimpleModule module = new SimpleModule();
  module.addSerializer(EthBlock.class, new BlockSerializer());
  ObjectMapper mapper = new ObjectMapper();
  mapper.registerModule(module);
  HttpService webSvc = new HttpService("https://bsc-dataseed.binance.org/", true);
  Web3j web3 = Web3j.build(webSvc);
  EthBlock block = web3.ethGetBlockByNumber(new DefaultBlockParameterNumber(blockNumber), true).send();
} catch (Throwable t) {
  t.printStackTrace();
}
```

Fails at `web3.ethGetBlockByNumber` with the aforementioned stack trace.  My version of Service.class in in JAR file named `core-4.9.4.jar`

**Comment by furkilic** [comment]
Hello everyone

Indeed we faced the same issue as well, when `includeRawResponses` is `true`.

### Good to know
It seems like the issue appeared since [v4.8.3](https://github.com/web3j/web3j/releases/tag/v4.8.3) with Fix leak in HttpService (https://github.com/web3j/web3j/pull/1325)
It also depends on how okhttp gonna wrap the responseBody when fetching the response (that's the reason why it still works in the tests and maybe with some RPC endpoints that are not chunking or gziping the response)

### Quick explanation 
1. When using `includeRawResponses` is `true` we build the `InputStream` that depends on the `responseBody`
https://github.com/web3j/web3j/blob/199914cfffda72f3233abd72d4141fdc62b873d5/core/src/main/java/org/web3j/protocol/http/HttpService.java#L204
Keep in mind that if something close the `responseBody` then it will also close the depending `inputStream`

2. Since the Leak Fix this line has been added 
https://github.com/web3j/web3j/blob/199914cfffda72f3233abd72d4141fdc62b873d5/core/src/main/java/org/web3j/protocol/http/HttpService.java#L165
Here we auto-close the `response` which will then close the `responseBody` then the `inputStream`
Keep in mind at this point the `inputStream` has not been consumed nor buffered.

3. Finally when we try to read in the `inputStream` at L50, it is already closed
https://github.com/web3j/web3j/blob/199914cfffda72f3233abd72d4141fdc62b873d5/core/src/main/java/org/web3j/protocol/Service.java#L48-L50

### Additional Info
As mentioned earlier, during the tests an interceptor which mock the response with an already buffered source (using `okio.Buffer`).
https://github.com/web3j/web3j/blob/199914cfffda72f3233abd72d4141fdc62b873d5/core/src/test/java/org/web3j/protocol/ResponseTester.java#L79
Because the `responseBody` is already buffered the close issue does not happen

### Quick external hack to avoid the problem
Forcefully consume the body before closing it so it buffers the response in memory.
If I take @mscongdon snippet here how to fix it 
```java
 try {
            OkHttpClient okHttpClient = new OkHttpClient.Builder().addInterceptor(chain -> {
                // Do the real call
                Response response = chain.proceed(chain.request());
                // Need to do the some checks like the response is successful and not null...
                return response
                        .newBuilder()
                        // Retrieve the full response: might have performance issue
                        .body(ResponseBody.create(response.body().bytes(), response.body().contentType()))
                        .build();
            }).build();
            HttpService webSvc = new HttpService("https://bsc-dataseed.binance.org/", okHttpClient, true);
            Web3j web3 = Web3j.build(webSvc);
            EthBlock block = web3.ethGetBlockByNumber(new DefaultBlockParameterNumber(21516217), true).send();
        } catch (Throwable t) {
            t.printStackTrace();
        }
```
