### ISSUE TITLE
NPE when return a struct with an array inside

### ISSUE THREAD

**Issue by pickles-good** [web3j/web3j#1888]
# NPE when return a struct with array inside

## Steps To Reproduce
my contract is like this:
```
//SPDX-License-Identifier:MIT
pragma solidity ^0.8.17;
contract Test{
	struct Token{
            uint8[] array;
            uint16 id;
	    string owner;
	}
        Token token;
	constructor(){
            token.array = [1,2];
            token.id = 1;
            token.owner = "zhangsan";
	}
	function getTransaction() public view returns (Token memory){
	    return token;
	}
}
```
And I generate java wrapper using codegen 4.9.7, the java class is like this:
```
import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import org.web3j.abi.TypeReference;
import org.web3j.abi.datatypes.DynamicArray;
import org.web3j.abi.datatypes.DynamicStruct;
import org.web3j.abi.datatypes.Function;
import org.web3j.abi.datatypes.Type;
import org.web3j.abi.datatypes.Utf8String;
import org.web3j.abi.datatypes.generated.Uint16;
import org.web3j.abi.datatypes.generated.Uint8;
import org.web3j.crypto.Credentials;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.RemoteCall;
import org.web3j.protocol.core.RemoteFunctionCall;
import org.web3j.tx.Contract;
import org.web3j.tx.TransactionManager;
import org.web3j.tx.gas.ContractGasProvider;

/**
 * <p>Auto generated code.
 * <p><strong>Do not modify!</strong>
 * <p>Please use the <a href="https://docs.web3j.io/command_line.html">web3j command line tools</a>,
 * or the org.web3j.codegen.SolidityFunctionWrapperGenerator in the 
 * <a href="https://github.com/web3j/web3j/tree/master/codegen">codegen module</a> to update.
 *
 * <p>Generated with web3j version 4.9.7.
 */
@SuppressWarnings("rawtypes")
public class Test extends Contract {
    public static final String BINARY = "60806040523480156200001157600080fd5b506040518060400160405280600160ff168152602001600260ff168152506000800190600262000043929190620000b5565b506001600060010160006101000a81548161ffff021916908361ffff1602179055506040518060400160405280600881526020017f7a68616e6773616e00000000000000000000000000000000000000000000000081525060006002019081620000ae9190620003fc565b50620004e3565b82805482825590600052602060002090601f01602090048101928215620001505791602002820160005b838211156200011f57835183826101000a81548160ff021916908360ff1602179055509260200192600101602081600001049283019260010302620000df565b80156200014e5782816101000a81549060ff02191690556001016020816000010492830192600103026200011f565b505b5090506200015f919062000163565b5090565b5b808211156200017e57600081600090555060010162000164565b5090565b600081519050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b600060028204905060018216806200020457607f821691505b6020821081036200021a5762000219620001bc565b5b50919050565b60008190508160005260206000209050919050565b60006020601f8301049050919050565b600082821b905092915050565b600060088302620002847fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8262000245565b62000290868362000245565b95508019841693508086168417925050509392505050565b6000819050919050565b6000819050919050565b6000620002dd620002d7620002d184620002a8565b620002b2565b620002a8565b9050919050565b6000819050919050565b620002f983620002bc565b620003116200030882620002e4565b84845462000252565b825550505050565b600090565b6200032862000319565b62000335818484620002ee565b505050565b5b818110156200035d57620003516000826200031e565b6001810190506200033b565b5050565b601f821115620003ac57620003768162000220565b620003818462000235565b8101602085101562000391578190505b620003a9620003a08562000235565b8301826200033a565b50505b505050565b600082821c905092915050565b6000620003d160001984600802620003b1565b1980831691505092915050565b6000620003ec8383620003be565b9150826002028217905092915050565b620004078262000182565b67ffffffffffffffff8111156200042357620004226200018d565b5b6200042f8254620001eb565b6200043c82828562000361565b600060209050601f8311600181146200047457600084156200045f578287015190505b6200046b8582620003de565b865550620004db565b601f198416620004848662000220565b60005b82811015620004ae5784890151825560018201915060208501945060208101905062000487565b86831015620004ce5784890151620004ca601f891682620003be565b8355505b6001600288020188555050505b505050505050565b61044480620004f36000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806359705f8114610030575b600080fd5b61003861004e565b604051610045919061038c565b60405180910390f35b610056610198565b6000604051806060016040529081600082018054806020026020016040519081016040528092919081815260200182805480156100d857602002820191906000526020600020906000905b82829054906101000a900460ff1660ff16815260200190600101906020826000010492830192600103820291508084116100a15790505b505050505081526020016001820160009054906101000a900461ffff1661ffff1661ffff168152602001600282018054610111906103dd565b80601f016020809104026020016040519081016040528092919081815260200182805461013d906103dd565b801561018a5780601f1061015f5761010080835404028352916020019161018a565b820191906000526020600020905b81548152906001019060200180831161016d57829003601f168201915b505050505081525050905090565b604051806060016040528060608152602001600061ffff168152602001606081525090565b600081519050919050565b600082825260208201905092915050565b6000819050602082019050919050565b600060ff82169050919050565b6101ff816101e9565b82525050565b600061021183836101f6565b60208301905092915050565b6000602082019050919050565b6000610235826101bd565b61023f81856101c8565b935061024a836101d9565b8060005b8381101561027b5781516102628882610205565b975061026d8361021d565b92505060018101905061024e565b5085935050505092915050565b600061ffff82169050919050565b61029f81610288565b82525050565b600081519050919050565b600082825260208201905092915050565b60005b838110156102df5780820151818401526020810190506102c4565b60008484015250505050565b6000601f19601f8301169050919050565b6000610307826102a5565b61031181856102b0565b93506103218185602086016102c1565b61032a816102eb565b840191505092915050565b60006060830160008301518482036000860152610352828261022a565b91505060208301516103676020860182610296565b506040830151848203604086015261037f82826102fc565b9150508091505092915050565b600060208201905081810360008301526103a68184610335565b905092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b600060028204905060018216806103f557607f821691505b602082108103610408576104076103ae565b5b5091905056fea264697066735822122056b91fff84093cea47b40b61aacd783733e8d03cd4f99ca4854958d97d4e236d64736f6c63430008110033";

    public static final String FUNC_GETTRANSACTION = "getTransaction";

    @Deprecated
    protected Test(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    protected Test(String contractAddress, Web3j web3j, Credentials credentials, ContractGasProvider contractGasProvider) {
        super(BINARY, contractAddress, web3j, credentials, contractGasProvider);
    }

    @Deprecated
    protected Test(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        super(BINARY, contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }

    protected Test(String contractAddress, Web3j web3j, TransactionManager transactionManager, ContractGasProvider contractGasProvider) {
        super(BINARY, contractAddress, web3j, transactionManager, contractGasProvider);
    }

    public RemoteFunctionCall<Token> getTransaction() {
        final Function function = new Function(FUNC_GETTRANSACTION, 
                Arrays.<Type>asList(), 
                Arrays.<TypeReference<?>>asList(new TypeReference<Token>() {}));
        return executeRemoteCallSingleValueReturn(function, Token.class);
    }

    @Deprecated
    public static Test load(String contractAddress, Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return new Test(contractAddress, web3j, credentials, gasPrice, gasLimit);
    }

    @Deprecated
    public static Test load(String contractAddress, Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return new Test(contractAddress, web3j, transactionManager, gasPrice, gasLimit);
    }

    public static Test load(String contractAddress, Web3j web3j, Credentials credentials, ContractGasProvider contractGasProvider) {
        return new Test(contractAddress, web3j, credentials, contractGasProvider);
    }

    public static Test load(String contractAddress, Web3j web3j, TransactionManager transactionManager, ContractGasProvider contractGasProvider) {
        return new Test(contractAddress, web3j, transactionManager, contractGasProvider);
    }

    public static RemoteCall<Test> deploy(Web3j web3j, Credentials credentials, ContractGasProvider contractGasProvider) {
        return deployRemoteCall(Test.class, web3j, credentials, contractGasProvider, BINARY, "");
    }

    public static RemoteCall<Test> deploy(Web3j web3j, TransactionManager transactionManager, ContractGasProvider contractGasProvider) {
        return deployRemoteCall(Test.class, web3j, transactionManager, contractGasProvider, BINARY, "");
    }

    @Deprecated
    public static RemoteCall<Test> deploy(Web3j web3j, Credentials credentials, BigInteger gasPrice, BigInteger gasLimit) {
        return deployRemoteCall(Test.class, web3j, credentials, gasPrice, gasLimit, BINARY, "");
    }

    @Deprecated
    public static RemoteCall<Test> deploy(Web3j web3j, TransactionManager transactionManager, BigInteger gasPrice, BigInteger gasLimit) {
        return deployRemoteCall(Test.class, web3j, transactionManager, gasPrice, gasLimit, BINARY, "");
    }

    public static class Token extends DynamicStruct {
        public List<BigInteger> array;

        public BigInteger id;

        public String owner;

        public Token(List<BigInteger> array, BigInteger id, String owner) {
            super(new DynamicArray<Uint8>(
                            Uint8.class,
                            org.web3j.abi.Utils.typeMap(array, Uint8.class)),
                    new Uint16(id),
                    new Utf8String(owner));
            this.array = array;
            this.id = id;
            this.owner = owner;
        }

        public Token(DynamicArray<Uint8> array, Uint16 id, Utf8String owner) {
            super(array, id, owner);
            this.array = array.getValue().stream().map(v -> v.getValue()).collect(Collectors.toList());
            this.id = id.getValue();
            this.owner = owner.getValue();
        }
    }
}
```
When I call the getTransaction function, I got a NPE:
```
 Token token = test.getTransaction().send();
```
The test field is the instance of contract class.
```
java.lang.NullPointerException
	at org.web3j.abi.Utils.getTypeName(Utils.java:286)
	at org.web3j.abi.TypeReference.getClassType(TypeReference.java:94)
	at org.web3j.abi.Utils.getParameterizedTypeFromArray(Utils.java:182)
	at org.web3j.abi.TypeDecoder.decodeArrayElements(TypeDecoder.java:638)
	at org.web3j.abi.TypeDecoder.decodeDynamicArray(TypeDecoder.java:442)
	at org.web3j.abi.TypeDecoder.decodeDynamicParameterFromStruct(TypeDecoder.java:569)
	at org.web3j.abi.TypeDecoder.decodeDynamicStructElements(TypeDecoder.java:522)
	at org.web3j.abi.TypeDecoder.decodeDynamicStruct(TypeDecoder.java:458)
	at org.web3j.abi.DefaultFunctionReturnDecoder.build(DefaultFunctionReturnDecoder.java:94)
	at org.web3j.abi.DefaultFunctionReturnDecoder.decodeFunctionResult(DefaultFunctionReturnDecoder.java:52)
	at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:57)
	at org.web3j.tx.Contract.executeCall(Contract.java:313)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:324)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:335)
	at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:457)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at MyTest.test35(MyTest.java:750)
```

## Environment
```
<dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.9.7</version>
</dependency>
<dependency>
            <groupId>org.web3j</groupId>
            <artifactId>codegen</artifactId>
            <version>4.9.7</version>
</dependency>
```
## Additional context
I also try using a contract without an array in the returned construct and it returned the right value.
New to github, the report may not be very professional. Thanks.

**Comment by pickles-good** [comment]
It seems that the java class generated from abi doesn't have annotation, but the TypeDecoder class use it. Does anyone know how to generate java file with annotation?

**Comment by pickles-good** [comment]
I solve this problem by adding annotation manually on the constructor of class Test like this:
```
public Token(@Parameterized(type = org.web3j.abi.datatypes.generated.Uint8.class)DynamicArray<Uint8> array, Uint16 id, Utf8String owner) {
            super(array, id, owner);
            this.array = array.getValue().stream().map(v -> v.getValue()).collect(Collectors.toList());
            this.id = id.getValue();
            this.owner = owner.getValue();
}
```
I think the problem maybe  the codegen I use.
