### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: No virtual method longValueExact()J in class Ljava/math/BigInteger;

### ISSUE THREAD

**Issue by JameWade** [web3j/web3j#1905]
# _Bug_title_
No virtual method longValueExact() on devices running Android 11 

## Steps To Reproduce
when i run this code
EthTransaction ethTransaction = web3j.ethGetTransactionByHash(transactionHash).send();
and this 
EthBlock block = web3j.ethGetBlockByNumber(
                DefaultBlockParameter.valueOf("latest"),
                true  //returnFullTransactionObjects
        ).sendAsync().get();
i got this problem,and then  I found again on the Issue ,the 35724dc678d3b2a6ccc0028157e580267b9a57d3 commit fix it .
### Expected behavior
_A clear and concise description of what you expected to happen._

### Actual behavior
com.fasterxml.jackson.databind.JsonMappingException: No virtual method longValueExact()J in class Ljava/math/BigInteger; or its super classes (declaration of 'java.math.BigInteger' appears in /apex/com.android.art/javalib/core-libart.jar)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at [Source: (ByteArrayInputStream); line: 1, column: 675] (through reference chain: org.web3j.protocol.core.methods.response.EthTransaction["result"]->org.web3j.protocol.core.methods.response.Transaction["v"])
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:611)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:599)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:143)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3242)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at org.web3j.protocol.Service.send(Service.java:50)
2023-05-08 15:44:32.955 25428-25428/com.crrc.eth W/System.err:     at org.web3j.protocol.core.Request.send(Request.java:87)

## Environment
_Describe the environment in which the issue occurs_
- Web3j 4.8.7
- Java11 and android11
- Operating System

## Additional context
_Add any other context about the problem here._
- Logs
- Sample code and/or code snippets
- Unit/integration tests to highlight the issue
- [etherscan](https://etherscan.io/) references

**Comment by JameWade** [comment]
i saw you fix this，but i got  'org.web3j:core:4.8.7-android'，，it doesn't ok
<img width="330" alt="1683539220602" src="https://user-images.githubusercontent.com/47301518/236792640-ad2bc16f-4b76-405d-aae4-e6a5403a32d7.png">

**Comment by Dev10-sys** [comment]
I checked the current codebase and the issue is already fixed in main.

In Transaction.java, the code now uses:
Numeric.toBigInt((String) v).longValue()

and there are no remaining usages of longValueExact() in the project.

So the crash described here is not present in the latest source.

From what I can see, this looks like a release mismatch rather than a code issue.

The android artifact (4.8.7-android) still contains the old implementation, which uses longValueExact() and crashes on Android 11 and below. That version appears to have been built before the fix was introduced.

So users depending on that specific artifact will continue to hit the crash even though the issue is already resolved in main.

It would help to clarify:

- whether a newer android-compatible artifact exists with this fix
- or if users are expected to move to a newer core version instead

For now, upgrading to a version built after the fix should resolve the issue.
