### ISSUE TITLE
web3j new generation failed

### ISSUE THREAD

**Issue by AndroidLoop** [web3j/web3j#1960]
# web3j new generation failed
Every time I try to generate a base project, it prompts "Project generation Failed. Check log file for more information."

## _Issue_description_
Just running `web3j new` in the command line. I have Java 17, that's the only requirement the tool indicates you to have already installed. I checked and the contrat that prompts is missing, is there, specifically at `Web3App\build\generated\sources\web3j\main\java\org\web3j\generated\contracts`.

## _Issue_context_
This is the log

```
java.lang.IllegalStateException: java.lang.ClassNotFoundException: org.web3j.generated.contracts.HelloWorld
	at org.web3j.codegen.unit.gen.ClassProvider.loadClass(ClassProvider.java:63)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.web3j.codegen.unit.gen.ClassProvider.getClasses(ClassProvider.java:44)
	at org.web3j.console.project.java.JavaTestCLIRunner.generateJava(JavaTestCLIRunner.java:91)
	at org.web3j.console.project.java.JavaProject.generateTests(JavaProject.java:39)
	at org.web3j.console.project.AbstractProject.createProject(AbstractProject.java:67)
	at org.web3j.console.project.java.JavaProjectRunner.generateJava(JavaProjectRunner.java:48)
	at org.web3j.console.project.java.JavaProjectCreatorRunner.createProject(JavaProjectCreatorRunner.java:26)
	at org.web3j.console.project.ProjectRunner.run(ProjectRunner.java:86)
	at org.web3j.console.project.NewProjectCommand.run(NewProjectCommand.java:67)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.web3j.console.Web3jCommand.parse(Web3jCommand.java:113)
	at org.web3j.console.Web3j.main(Web3j.java:18)
Caused by: java.lang.ClassNotFoundException: org.web3j.generated.contracts.HelloWorld
	at org.web3j.codegen.unit.gen.CompilerClassLoader.lambda$findClass$2(CompilerClassLoader.java:66)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.web3j.codegen.unit.gen.CompilerClassLoader.findClass(CompilerClassLoader.java:66)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.web3j.codegen.unit.gen.ClassProvider.loadClass(ClassProvider.java:61)
	... 29 more

```

**Comment by gtebrean** [comment]
what is web3j version?

**Comment by gtebrean** [comment]
@AndroidLoop I ran locally web3j-cli 1.5.0 and it builds correctly, also in Web3App generated project builds fine and HelloWord class can be find.
If your error persists run ./gradlew build, in your case maybe the HelloWorld wrapper wasn't generated.
Please let me know how it goes.

**Comment by AndroidLoop** [comment]
Thanks for your reply and sorry for the late response. But then Gradle is a requirement not listed in the documentation. I'll try and give and update.

**Comment by gtebrean** [comment]
Gradle comes out of the box with Web3j and maybe in your case only the build step wasn't run.

**Comment by gtebrean** [comment]
closing this due no further updates

**Comment by marcolafranca** [comment]
@gtebrean 
I run `./gradlew build`, this is the output:
```shell
PS C:\Users\lafmarcant\dev\projects\test\web3j\Test> .\gradlew build

> Task :npmInstall

up to date, audited 1 package in 1s

found 0 vulnerabilities

> Task :generateContractWrappers
Execution optimizations have been disabled for task ':generateContractWrappers' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'C:\Users\lafmarcant\dev\projects\test\web3j\Test\build\generated\sources\web3j\main\java'. Reason: Task ':compileKotlin' uses this output of task ':generateContractWrappers' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Generating org.web3j.generated.contracts.HelloWorld ... File written to C:\Users\lafmarcant\dev\projects\test\web3j\Test\build\generated\sources\web3j\main\java


Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 1m 4s
16 actionable tasks: 13 executed, 3 up-to-date
```

**Comment by marcolafranca** [comment]
The `HelloWorld.java` source is correctly in `\Test\build\generated\sources\web3j\main\java\org\web3j\generated\contracts\`
