### ISSUE TITLE
NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'

### ISSUE THREAD

**Issue by bofomike** [web3j/web3j#1990]
# NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'

## Steps To Reproduce
Run this:
```
        Web3j web3j = Web3j.build(new HttpService("YOUR_URL"));
        try {
            EthGasPrice ethGasPrice = web3j.ethGasPrice().send();
        } catch (Exception e) {
            ...
        }
```

### Expected behavior
Running normally

### Actual behavior
```
2023-12-12 14:23:03.730 ERROR 61504 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'] with root cause

java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:159) ~[core-4.9.7.jar!/:na]
	at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.9.7.jar!/:na]
	at org.web3j.protocol.core.Request.send(Request.java:87) ~[core-4.9.7.jar!/:na]
```

## Environment
- Web3j 4.9.7
- Java 17
- MacOS

## Additional context
I've already added dependency suggested in the other issues:
https://github.com/web3j/web3j/issues/1271
```
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.3</version>
        </dependency>
```

My whole pom.xml in case you see something wrong there:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.2</version>
    </parent>

    <groupId>io.theunbound</groupId>
    <artifactId>api</artifactId>
    <version>1.0.0</version>

    <properties>
        <java.version>17</java.version>
    </properties>

    <repositories>
        <repository>
            <id>my-local-repo</id>
            <url>file://${project.basedir}/libs</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-config</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
            <scope>provided</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.0</version>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.3</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.13.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10.1</version>
        </dependency>

        <!-- Bitmart SDK API -->
        <dependency>
            <groupId>com.bitmart</groupId>
            <artifactId>java.sdk.api</artifactId>
            <version>1.0</version>
        </dependency>

        <!-- Web3j - blockchain -->
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.9.7</version>
        </dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.3</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
```

Can anyone help me with this please?

**Comment by saugion** [comment]
I don't have the square dependency and it works. Which web3j version are you using? Could you paste the imports?

**Comment by bofomike** [comment]
> I don't have the square dependency and it works. Which web3j version are you using? Could you paste the imports?

Hey @saugion, it's in the desc of the issue, isn't it? 🤔
```       
        <!-- Web3j - blockchain -->
        <dependency>
            <groupId>org.web3j</groupId>
            <artifactId>core</artifactId>
            <version>4.9.7</version>
        </dependency>
```

**Comment by saugion** [comment]
I'm sorry @bofomike you're right, i didn't notice it. Could you try to use the last version, https://mvnrepository.com/artifact/org.web3j/core/4.10.3?

**Comment by bofomike** [comment]
> I'm sorry @bofomike you're right, i didn't notice it. Could you try to use the last version, https://mvnrepository.com/artifact/org.web3j/core/4.10.3?

I did and it's not working neither. 
```
2023-12-18 13:54:18.762 ERROR 14310 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'] with root cause

java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:153) ~[core-4.10.3.jar!/:na]
	at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.10.3.jar!/:na]
	at org.web3j.protocol.core.Request.send(Request.java:87) ~[core-4.10.3.jar!/:na]
```

**Comment by saugion** [comment]
the square dependency should not be needed as already included in the web3j library. I have the feeling that one of the other libraries declared in the pom have another dependency with a different version, and this causes the issue. Could you provide a reproducible example, a sample project that I can clone? Thanks

**Comment by bofomike** [comment]
Hey, I've updated spring version from 2.6.2 to 3.0.0 and it's all good 👍
That was tricky because it's an old micro-service I'm updating, but it's good in a long run anyway. 
No need for okhttp3 dependency at all now 👌
I'm closing this. 
Thanks!
