### ISSUE TITLE
[Android] Unsubscribing from Observable<Log> returned by Web3j.ethLogObservable() causes an Exception

### ISSUE THREAD

**Issue by mochalovv** [web3j/web3j#211]
When I unsubscribe from the `Observable<Log>` returned by `Web3j.ethLogObservable(new Filter(...))`, my app crashes with the following exception:
```
E/ActivityThread: Performing stop of activity that is not resumed: {ru.vmochalov.web3jtest/ru.vmochalov.web3jtest.MainActivity}
                  java.lang.RuntimeException: Performing stop of activity that is not resumed: {ru.vmochalov.web3jtest/ru.vmochalov.web3jtest.MainActivity}
                      at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3829)
                      at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3917)
                      at android.app.ActivityThread.access$1200(ActivityThread.java:177)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:5951)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-3
                  Process: ru.vmochalov.web3jtest, PID: 3217
                  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.web3j.protocol.core.Response$Error.getMessage()' on a null object reference
                      at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:90)
                      at org.web3j.protocol.core.filters.Filter.cancel(Filter.java:85)
                      at org.web3j.protocol.rx.JsonRpc2_0Rx$6.call(JsonRpc2_0Rx.java:120)
                      at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
                      at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                      at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                      at rx.Subscriber.unsubscribe(Subscriber.java:98)
                      at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                      at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                      at rx.Subscriber.unsubscribe(Subscriber.java:98)
                      at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                      at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                      at rx.Subscriber.unsubscribe(Subscriber.java:98)
                      at rx.internal.operators.OperatorUnsubscribeOn$2$1.call(OperatorUnsubscribeOn.java:66)
                      at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:818)
```
I am using the latest version of core-android lib in my `build.gradle`:
`implementation 'org.web3j:core-android:2.2.1'`

Code for reproducing the issue(the app crashes in onDestroy() method of MainActivity):
```
public class MainActivity extends AppCompatActivity {
    private static final String TAG = MainActivity.class.getSimpleName();

    private Subscription subscription;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        subscription = Web3jFactory.build(new HttpService(BuildConfig.NODE_URL)) // insert your url
                .ethLogObservable(new EthFilter(
                        DefaultBlockParameterName.EARLIEST,
                        DefaultBlockParameterName.LATEST,
                        BuildConfig.APP_CONTRACT_ADDRESS)) // insert your contract address
                .onBackpressureBuffer(10000)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .unsubscribeOn(Schedulers.io())
                .subscribe(new Subscriber<Log>() {
                               @Override
                               public void onStart() {
                                   android.util.Log.i(TAG, "onStart");
                               }

                               @Override
                               public void onCompleted() {
                                   android.util.Log.e(TAG, "onCompleted");
                               }

                               @Override
                               public void onError(Throwable e) {
                                   android.util.Log.e(TAG, "onError: " + e.getMessage());
                               }

                               @Override
                               public void onNext(Log log) {
                                   android.util.Log.i(TAG, "onNext: " + log.getData());
                               }
                           }
                );
    }

    @Override
    public void onDestroy() {
        subscription.unsubscribe();
        super.onDestroy();
    }
}
```

**Comment by conor10** [comment]
Thanks.
