### ISSUE TITLE
codegen generates .sol file error while return type is bool

### ISSUE THREAD

**Issue by LycrusHamster** [web3j/web3j#221]
Hi team
I find a certain situation that SolidityFunctionWrapper.generateJavaFiles() fails with useNativeJavaTypes set to true;
While a function of ABI is set to constant and has a bool return type, error occurs:
java.lang.IllegalArgumentException: invalid type parameter: boolean
        at com.squareup.javapoet.Util.checkArgument(Util.java:64)
        at com.squareup.javapoet.ParameterizedTypeName.<init>(ParameterizedTypeName.java:51)
        at com.squareup.javapoet.ParameterizedTypeName.<init>(ParameterizedTypeName.java:38)
        at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:111)
        at org.web3j.codegen.SolidityFunctionWrapper.buildRemoteCall(SolidityFunctionWrapper.java:479)
        at org.web3j.codegen.SolidityFunctionWrapper.buildConstantFunction(SolidityFunctionWrapper.java:442)
        at org.web3j.codegen.SolidityFunctionWrapper.buildFunction(SolidityFunctionWrapper.java:418)
        at org.web3j.codegen.SolidityFunctionWrapper.buildFunctionDefinitions(SolidityFunctionWrapper.java:143)
        at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:95)

ABI is some like

{
      "constant": true,
      "inputs": [
        {
          "name": "b",
          "type": "bool"
        },
        {
          "name": "value",
          "type": "uint64"
        }
      ],
      "name": "test",
      "outputs": [
        {
          "name": "ret",
          "type": "bool"                  HERE IS THE PLACE CAUSE ERROR
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function"
    },

I don't know if I break any rules of ABI but I DO SEE THAT BOOL IS EQUIVALENT TO UINT8 RESTRICTED TO 0 OR 1 in ABI doc.
Is this issue as designed? Or a bug?

**Comment by conor10** [comment]
Please try using web3j 3.0.2.

**Comment by 4ntoine** [comment]
Duplicate. Fixed and checked in 3.0.2

**Comment by LycrusHamster** [comment]
Hi team
thanks a lot  :+1:
