### ISSUE TITLE
Subscription code for listening to event is executing twice by two different threads

### ISSUE THREAD

**Issue by aleBiriri** [web3j/web3j#235]
I am developing an app with SpringBoot and Web3J, where i use a **contract wrapper for interacting with Smart contract**.  Here is the  **autogenerated code of a method for listening to an  event, called NewId**:
```
public Observable<NewIdEventResponse> newIdEventObservable(DefaultBlockParameter startBlock, DefaultBlockParameter endBlock) {
        final Event event = new Event("NewId", 
                Arrays.<TypeReference<?>>asList(),
                Arrays.<TypeReference<?>>asList(new TypeReference<Bytes32>() {}, new TypeReference<Address>() {}));
        EthFilter filter = new EthFilter(startBlock, endBlock, getContractAddress());
        filter.addSingleTopic(EventEncoder.encode(event));
        return web3j.ethLogObservable(filter).map(new Func1<Log, NewIdEventResponse>() {
            @Override
            public NewIdEventResponse call(Log log) {
                EventValues eventValues = extractEventParameters(event, log);
                NewIdEventResponse typedResponse = new NewIdEventResponse();
                typedResponse.key = (Bytes32) eventValues.getNonIndexedValues().get(0);
                typedResponse.contractId = (Address) eventValues.getNonIndexedValues().get(1);
                return typedResponse;
            }
        });
    }

```

I've created a **subscription  _s_ to the observable, where i print the executing thread name  AND increment a counter, initialized to 0.** Then "mian thread" (spring boot thread) sleeps for 5 seconds after doing subscription, and then prints counter value and invoke _s.unsubscribe_ . Here is code:

```
//Invoke transactional contract method...
				this.counter = 0;
				CountDownLatch latch = new CountDownLatch(1);
				log.warn("Counter value before subscription: "+counter);
				Subscription s = contractWrapper.newIdEventObservable(DefaultBlockParameterName.LATEST, DefaultBlockParameterName.LATEST)
						.subscribe(evento ->{
							log.warn("Event Received");
							log.warn("Thread Name "+Thread.currentThread().getName());
							latch.countDown();
							this.testIncCounter();
							},								
						Throwable::printStackTrace);
				
				latch.await();
				log.warn("Main Thread going to sleep for 5 seconds");
				Thread.sleep(5000);
				log.warn("Unsubscribing...");
				s.unsubscribe();
				log.warn("Counter value "+counter);
```
The testIncCounter method is  synchronized:

```
private synchronized void testIncCounter(){
		counter++;
	}
```

The problem is that **subscription code is executing twice by different threads**, as it can be seen in logs ,and counter's end value is 2, and should be 1. Here is the output:

```
2017-11-07 20:56:17.345  WARN 23533 --- [nio-8090-exec-4] com.ckgt.service.impl.CecaServiceImpl    : Counter value before subscription: 0
2017-11-07 20:56:17.433  WARN 23533 --- [nio-8090-exec-4] com.ckgt.service.impl.CecaServiceImpl    : Event Received
2017-11-07 20:56:17.433  WARN 23533 --- [nio-8090-exec-4] com.ckgt.service.impl.CecaServiceImpl    : Thread Name http-nio-8090-exec-4
2017-11-07 20:56:17.449  WARN 23533 --- [nio-8090-exec-4] com.ckgt.service.impl.CecaServiceImpl    : Main Thread going to sleep for 5 seconds
2017-11-07 20:56:17.491  WARN 23533 --- [ool-17-thread-1] com.ckgt.service.impl.CecaServiceImpl    : Event Received
2017-11-07 20:56:17.491  WARN 23533 --- [ool-17-thread-1] com.ckgt.service.impl.CecaServiceImpl    : Thread Name pool-17-thread-1
2017-11-07 20:56:22.450  WARN 23533 --- [nio-8090-exec-4] com.ckgt.service.impl.CecaServiceImpl    : Unsubscribing...
2017-11-07 20:56:22.459  WARN 23533 --- [nio-8090-exec-4] com.ckgt.service.impl.CecaServiceImpl    : Counter value 2
```

Maybe is this a bug, or am i doing something wrong?
Thank you very much in advance.

**Comment by conor10** [comment]
Which version of web3j are you using?

I presume this isn't Android - we did have a related issue, see https://github.com/web3j/web3j/pull/212/files.

**Comment by aleBiriri** [comment]
I am with 2.3.0.  I am developing an app with SpringBoot. Thanks in advance.

**Comment by conor10** [comment]
Please can you try using 3.0.2?

**Comment by aleBiriri** [comment]
Ok thank you, until monday i'll not be able to try 3.0.2 version. Give you feedback then. Thank you again.

**Comment by aleBiriri** [comment]
Hi again. I've updated my project in order to use Web3j verison 3.0.2, but **problem persist**.

Here is the **new  autogenerated method code**:
```
public Observable<NewIdEventResponse> newIdEventObservable(DefaultBlockParameter startBlock, DefaultBlockParameter endBlock) {
        final Event event = new Event("NewId", 
                Arrays.<TypeReference<?>>asList(),
                Arrays.<TypeReference<?>>asList(new TypeReference<Bytes32>() {}, new TypeReference<Address>() {}));
        EthFilter filter = new EthFilter(startBlock, endBlock, getContractAddress());
        filter.addSingleTopic(EventEncoder.encode(event));
        return web3j.ethLogObservable(filter).map(new Func1<Log, NewIdEventResponse>() {
            @Override
            public NewIdEventResponse call(Log log) {
                EventValues eventValues = extractEventParameters(event, log);
                NewIdEventResponse typedResponse = new NewIdEventResponse();
                typedResponse.key = (byte[]) eventValues.getNonIndexedValues().get(0).getValue();
                typedResponse.contractId = (String) eventValues.getNonIndexedValues().get(1).getValue();
                return typedResponse;
            }
        });
    }
```
And here is the **new output**:

```
2017-11-13 12:34:03.269  WARN 14651 --- [nio-8090-exec-6] com.ckgt.service.impl.CecaServiceImpl    : Counter value before subscription: 0
2017-11-13 12:34:03.329  WARN 14651 --- [pool-2-thread-2] com.ckgt.service.impl.CecaServiceImpl    : Event Received
2017-11-13 12:34:03.342  WARN 14651 --- [pool-2-thread-2] com.ckgt.service.impl.CecaServiceImpl    : Thread Name pool-2-thread-2
2017-11-13 12:34:03.347  WARN 14651 --- [nio-8090-exec-6] com.ckgt.service.impl.CecaServiceImpl    : Main Thread going to sleep for 5 seconds
2017-11-13 12:34:03.363  WARN 14651 --- [pool-2-thread-1] com.ckgt.service.impl.CecaServiceImpl    : Event Received
2017-11-13 12:34:03.363  WARN 14651 --- [pool-2-thread-1] com.ckgt.service.impl.CecaServiceImpl    : Thread Name pool-2-thread-1
2017-11-13 12:34:08.347  WARN 14651 --- [nio-8090-exec-6] com.ckgt.service.impl.CecaServiceImpl    : Unsubscribing...
2017-11-13 12:34:08.352  WARN 14651 --- [nio-8090-exec-6] com.ckgt.service.impl.CecaServiceImpl    : Counter value 2
```
As you can see, both code and output are quite similar to first output. Minor differences are the return type of event's attributes and thread's names, respectively.

Thank you very much in advance,
Alejandro

**Comment by aleBiriri** [comment]
I've been deeping in Web3J code, and found that method **org.web3j.protocol.core.filters.LogFilter.process() is invoked twice**, both in methods inhereted from org.web3j.protocol.core.filters.Filter<T>:  **getInitialFilterLogs** and **pollFilter**.
Those are called in following lines of method Filter<T>.run():
```
scheduledExecutorService.submit(this::getInitialFilterLogs);

            schedule = scheduledExecutorService.scheduleAtFixedRate(
                    () -> this.pollFilter(ethFilter),
                    0, blockTime, TimeUnit.MILLISECONDS);
```
**It seems that pollFilter catch the event so, my why is getInitialFilterLogs invoked?** Sorry if my questions are too obvius, but im new at the ethereum environment.

**Comment by eepstein** [comment]
I think I'm seeing this too in the stack traces when the system exits.  

	at org.web3j.protocol.core.filters.Filter.cancel(Filter.java:106)
	at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
	at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
	at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
	at rx.Subscriber.unsubscribe(Subscriber.java:98)
	at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
	at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
	at rx.Subscriber.unsubscribe(Subscriber.java:98)

**Comment by dtco-kimi** [comment]
Hello guys, 
I have the same issue. I'm using v.3.1.1 Has it been fixed? Or do you have plan to fix it? 
Thanks.
