### ISSUE TITLE
Truffle wrapper generator fails on some Contracts with an NPE

### ISSUE THREAD

**Issue by guardiande** [web3j/web3j#251]
Some of Truffle's JSON files contain a network attribute like this

```
  "networks": {
    "12762": {
      "links": {},
      "events": {},
      "updated_at": 1511268134254
    }
```

Note that it does not contain an address property which is required for this code (to run TruffleJsonFunctionWrapperGenerator line 122 and following)

```
String className = Strings.capitaliseFirstLetter(contractName);
System.out.printf("Generating " + basePackageName + "." + className + " ... ");
Map<String, String> addresses;
if (c.networks != null && !c.networks.isEmpty()) {
         addresses = c.networks.entrySet().stream().collect(
          Collectors.toMap(Map.Entry::getKey, e -> e.getValue().getAddress()
));
```

This is the runtime error (e.getValue().getAddress() yields a null value)

```
Exception in thread "main" java.lang.NullPointerException
        at java.util.HashMap.merge(HashMap.java:1224)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.web3j.codegen.TruffleJsonFunctionWrapperGenerator.generate(TruffleJsonFunctionWrapperGenerator.java:126)
        at org.web3j.codegen.TruffleJsonFunctionWrapperGenerator.main(TruffleJsonFunctionWrapperGenerator.java:98)
```

**Comment by eepstein** [comment]
i’ll take a look

**Comment by guardiande** [comment]
Great! Would mind pushing a PR?

**Comment by eepstein** [comment]
it’s bundled in an existing PR that’s being reviewed.
