### ISSUE TITLE
Can't generate wrapper from NettingChannelLibrary

### ISSUE THREAD

**Issue by CosminNechifor** [web3j/web3j#272]
Hello everyone, I was wondering if someone might be able to help me with this one. (If you consider the question as being useless, I would ask you to delete it)

### The problem

 I can't generate the wrapper of NettingChannelLibrary using web3j I have compiled the smart contracts using solc and generated the. bin and .abi: 

### NettingChannelLibrary.abi
```json
[
    {
        "constant": false,
        "inputs": [
            {
                "name": "self",
                "type": "NettingChannelLibrary.Data storage"
            },
            {
                "name": "amount",
                "type": "uint256"
            }
        ],
        "name": "deposit",
        "outputs": [
            {
                "name": "success",
                "type": "bool"
            },
            {
                "name": "balance",
                "type": "uint256"
            }
        ],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [],
        "name": "contract_version",
        "outputs": [
            {
                "name": "",
                "type": "string"
            }
        ],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "self",
                "type": "NettingChannelLibrary.Data storage"
            },
            {
                "name": "locked_encoded",
                "type": "bytes"
            },
            {
                "name": "merkle_proof",
                "type": "bytes"
            },
            {
                "name": "secret",
                "type": "bytes32"
            }
        ],
        "name": "withdraw",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "self",
                "type": "NettingChannelLibrary.Data storage"
            },
            {
                "name": "nonce",
                "type": "uint64"
            },
            {
                "name": "transferred_amount",
                "type": "uint256"
            },
            {
                "name": "locksroot",
                "type": "bytes32"
            },
            {
                "name": "extra_hash",
                "type": "bytes32"
            },
            {
                "name": "signature",
                "type": "bytes"
            }
        ],
        "name": "close",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "self",
                "type": "NettingChannelLibrary.Data storage"
            }
        ],
        "name": "settle",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "self",
                "type": "NettingChannelLibrary.Data storage"
            },
            {
                "name": "nonce",
                "type": "uint64"
            },
            {
                "name": "transferred_amount",
                "type": "uint256"
            },
            {
                "name": "locksroot",
                "type": "bytes32"
            },
            {
                "name": "extra_hash",
                "type": "bytes32"
            },
            {
                "name": "signature",
                "type": "bytes"
            }
        ],
        "name": "updateTransfer",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    }
]
```

### Exception 

```bash
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported type encountered
	at org.web3j.abi.datatypes.generated.AbiTypes.getType(AbiTypes.java:221)
	at org.web3j.codegen.SolidityFunctionWrapper.buildTypeName(SolidityFunctionWrapper.java:766)
	at org.web3j.codegen.SolidityFunctionWrapper.buildParameterTypes(SolidityFunctionWrapper.java:450)
	at org.web3j.codegen.SolidityFunctionWrapper.addParameters(SolidityFunctionWrapper.java:330)
	at org.web3j.codegen.SolidityFunctionWrapper.buildFunction(SolidityFunctionWrapper.java:487)
	at org.web3j.codegen.SolidityFunctionWrapper.buildFunctionDefinitions(SolidityFunctionWrapper.java:195)
	at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:108)
	at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:91)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.generate(SolidityFunctionWrapperGenerator.java:123)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.main(SolidityFunctionWrapperGenerator.java:87)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.run(SolidityFunctionWrapperGenerator.java:48)
	at org.web3j.console.Runner.main(Runner.java:38)
```

### System Description

Ubuntu 16.04
solc Version: 0.4.18+commit.9cf6e910.Linux.g++
Web3j Version: 3.1.1

**Comment by conor10** [comment]
Please can you provide a link to the smart contract source code? Definitely keen to ensure interop with Raiden.

**Comment by CosminNechifor** [comment]
[NettingChannelLibrary.zip](https://github.com/web3j/web3j/files/1556080/NettingChannelLibrary.zip)

**Comment by CosminNechifor** [comment]
[NettingChannelLibrary.zip](https://github.com/web3j/web3j/files/1556083/NettingChannelLibrary.zip)

Here it is.

**Comment by conor10** [comment]
It's strange that the struct types are present in the ABI, which was added in [Solidity 0.4.19](https://github.com/ethereum/solidity/issues/595). However, you're using Solidity 0.4.18.

If the struct types are present would expect to see the `NettingChannelLibrary.Data storage` to be encoded as a [tuple](http://solidity.readthedocs.io/en/develop/abi-spec.html#handling-tuple-types).

**Comment by Aghorb** [comment]
Same problem. Is there any solution to fix it?
