### ISSUE TITLE
OutOfMemoryError after 3.0.1 and 3.1.1 android. 2.2.1 is ok ,idon know why.

### ISSUE THREAD

**Issue by youkpan** [web3j/web3j#308]
01-11 05:17:38.790 9091-9592/com.hayoou.HayoouETH E/AndroidRuntime: FATAL EXCEPTION: IntentService[Transaction Service]
                                                                    Process: com.hayoou.HayoouETH, PID: 9091
                                                                    java.lang.OutOfMemoryError: Failed to allocate a 1036 byte allocation with 11472992 free bytes and 10MB until OOM; failed due to fragmentation (required continguous free 16384 bytes for a new buffer where largest contiguous free 8192 bytes)
                                                                        at org.spongycastle.util.Arrays.clone(Arrays.java:602)
                                                                        at org.spongycastle.crypto.generators.SCrypt.SMix(SCrypt.java:126)
                                                                        at org.spongycastle.crypto.generators.SCrypt.MFcrypt(SCrypt.java:87)
                                                                        at org.spongycastle.crypto.generators.SCrypt.generate(SCrypt.java:66)
                                                                        at org.web3j.crypto.Wallet.generateDerivedScryptKey(Wallet.java:136)
                                                                        at org.web3j.crypto.Wallet.decrypt(Wallet.java:214)
                                                                        at org.web3j.crypto.WalletUtils.loadCredentials(WalletUtils.java:82)
                                                                        at rehanced.com.simpleetherwallet.utils.WalletStorage.getFullWallet(WalletStorage.java:249)
                                                                        at rehanced.com.simpleetherwallet.services.TransactionService.onHandleIntent(TransactionService.java:57)
                                                                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:163)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

and also i want to change char chainId to long chainId

**Comment by youkpan** [comment]
ok same problem OOM
