### ISSUE TITLE
muti thread request Transaction Problem

### ISSUE THREAD

**Issue by bigstar119** [web3j/web3j#31]
hi , i try use muti thread send Transaction to geth rpc use web3j  like follow:
Thread1    Account1 send 1 ether to Account2
Thread2    Account1 send 1 ether to Account2
when these finished i want Account2`s balance increase 2 ether 

but  real is sometimes i got a error
java.lang.RuntimeException: Error processing transaction request: Known transaction: 2c3868f5
	at org.web3j.abi.ManagedTransaction.signAndSend(ManagedTransaction.java:86)
	at org.web3j.abi.Transfer.send(Transfer.java:75)
	at org.web3j.abi.Transfer.sendFunds(Transfer.java:106)
	at com.neusoft.ethereum.client.testcase.TransferThread.transfer(TransferTestCase.java:112)
	at com.neusoft.ethereum.client.testcase.TransferThread.call(TransferTestCase.java:134)
	at com.neusoft.ethereum.client.testcase.TransferThread.call(TransferTestCase.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

,and sometime Account2`s balance increase only 1 ether 
i find when you start 2 thread in a few seconds the Transaction`s nonce is same,this may case error or Transaction Overriding!!
what can i do with this problem?
is that means Transaction must  ecuted serially?
[testcase.zip](https://github.com/web3j/web3j/files/647843/testcase.zip)

**Comment by conor10** [comment]
Safest to execute sequentially. With multiple threads there's an obvious race condition where if both threads request the next nonce over JSON-RPC before either has sent a transaction, they will both send their subsequent transactions using the same nonce.

**Comment by bigstar119** [comment]
Thank you.. I understand..
but how Ethereum deal with the Execution efficiency problem?? because of ecuted serially..
in other words how can i Parallel execution Transaction in Ethereum

**Comment by ADifferentChenYun** [comment]
do you know how to parallel execution Transaction in Ethereum ? I encountered the same problem.
thank you.
@bigstar119
