### ISSUE TITLE
unsubscribe() from pendingTransactionObservable() throws NullPointerException

### ISSUE THREAD

**Issue by Emberice86** [web3j/web3j#313]
Faced with problem when I tried to unsubscribe from pendingTransactionObservable()
Here is the stack: 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.web3j.protocol.core.Response$Error.getMessage()' on a null object reference
                                                       at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:90)
                                                       at org.web3j.protocol.core.filters.Filter.cancel(Filter.java:85)
                                                       at org.web3j.protocol.rx.JsonRpc2_0Rx$6.call(JsonRpc2_0Rx.java:120)
                                                       at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
                                                       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                       at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                       at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                       at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                       at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                       at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                       at rx.Subscriber.unsubscribe(Subscriber.java:98)

**Comment by eepstein** [comment]
Which version of web3j are you using?
