### ISSUE TITLE
Can't generate java code for tuple type

### ISSUE THREAD

**Issue by mtessler-fmcc** [web3j/web3j#315]
When I generate the code for my contract, I see the following stack trace.
````
Generating com.ford.fc.blockchain.beta.Transportation ... Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported type encountered
        at org.web3j.abi.datatypes.generated.AbiTypes.getType(AbiTypes.java:221)
        at org.web3j.codegen.SolidityFunctionWrapper.buildTypeName(SolidityFunctionWrapper.java:780)
        at org.web3j.codegen.SolidityFunctionWrapper.buildEventFunctions(SolidityFunctionWrapper.java:719)
        at org.web3j.codegen.SolidityFunctionWrapper.buildFunctionDefinitions(SolidityFunctionWrapper.java:212)
        at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:108)
        at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:91)
        at org.web3j.codegen.SolidityFunctionWrapperGenerator.generate(SolidityFunctionWrapperGenerator.java:123)
        at org.web3j.codegen.SolidityFunctionWrapperGenerator.main(SolidityFunctionWrapperGenerator.java:87)
        at org.web3j.codegen.SolidityFunctionWrapperGenerator.run(SolidityFunctionWrapperGenerator.java:48)
        at org.web3j.console.Runner.main(Runner.java:38)
````
I recompiled AbiTypes to have it dump the offending type in the exception on line 221, and my error came from the type "tuple"
web3 command line version: 3.2.0
[Transportation.sol.txt](https://github.com/web3j/web3j/files/1627615/Transportation.sol.txt)
Contract attached.

**Comment by eepstein** [comment]
There is no type named "tuple" in the contract you attached.

I do see a struct named "Vehicle" and a mapping named "vehicles".

**Comment by mtessler-fmcc** [comment]
I tracked down the problem.  My Event had a struct as one of the fields.
```
    event newPosition(
        string vin,
        Position position
    );
    
    struct Position {
        int lat; //in millionths of a degree.  so 1.5 north is 1500000
        int lon; // in millionths of a degree
    }
```
That doesn't seem to be supported.  Once I changed the event to have all of the fields, it worked fine.
```
    event newPosition(
        string vin,
        int lat; //in millionths of a degree.  so 1.5 north is 1500000
        int lon; // in millionths of a degree
    }
```
The enhancement that would help is if there was a way to give a more meaningful error message.
Also, the addition of the unsupported data type name to the exception thrown by AbiTypes

**Comment by eepstein** [comment]
Adding the type name is doable.  Not sure if the rest of the context is available at that point in the call chain.
