### ISSUE TITLE
Only transactional methods should have void return types

### ISSUE THREAD

**Issue by berlinguyinca** [web3j/web3j#324]
Dear all,

using the latest version of the generator (3.2.0, I think), I keep encountering this error:

Only transactional methods should have void return types
        at org.web3j.codegen.SolidityFunctionWrapper.buildConstantFunction(SolidityFunctionWrapper.java:524)
        at org.web3j.codegen.SolidityFunctionWrapper.buildFunction(SolidityFunctionWrapper.java:505)
        at org.web3j.codegen.SolidityFunctionWrapper.buildFunctionDefinitions(SolidityFunctionWrapper.java:209)
        at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:108)
        at org.web3j.codegen.TruffleJsonFunctionWrapperGenerator.generate(TruffleJsonFunctionWrapperGenerator.java:134)
        at org.web3j.codegen.TruffleJsonFunctionWrapperGenerator.main(TruffleJsonFunctionWrapperGenerator.java:98)

I provide a really simple json file, generate by truffle, which is based on open zeppelins mintable token. 

Anybody has any idea for this error?

kind regards

**Comment by berlinguyinca** [comment]
**example code:**

pragma solidity ^0.4.18;

import 'zeppelin-solidity/contracts/token/MintableToken.sol';

import 'zeppelin-solidity/contracts/ownership/rbac/RBAC.sol';

contract ABCToken is MintableToken, RBAC{

  string public name = "ABC";
  string public symbol = "ABC";
  uint8 public decimals = 18;

  function ABCToken() public {

  }
  /**
   * @dev Throws if called by any user, who is not a ROLE_ADMIN
   */
  modifier onlyOwner() {
    checkRole(msg.sender, ROLE_ADMIN);
    _;
  }

}

**Comment by perlboy** [comment]
+1 on this, having the same issue, investigating now. @berlinguyinca this appears to be to do with the zeppelin-solidity RBAC import in particular. Unfortunately web3j doesn't provide much info on specific logging. Will update once I have more info.

**Comment by perlboy** [comment]
@berlinguyinca Proposed change submitted to zeppelin-solidity.

If you wish to avoid waiting for the change to be released you can use our fork here: https://github.com/ecaustralia/zeppelin-solidity

**Comment by frangio** [comment]
@perlboy Please do not encourage using a fork with commits that have not been released yet!

**Comment by perlboy** [comment]
Apologies, stripped suggestion from prior comment..

**Comment by iikirilov** [comment]
This is a web3j limitation, we encourage the community to pick up corner cases such as this by submitting a PR with a fix.
