### ISSUE TITLE
OOM   3.0.1 and 3.1.1 android. 2.2.1 all has the error ,idon know why.

### ISSUE THREAD

**Issue by Jevis** [web3j/web3j#356]
`String filename= WalletUtils.generateFullNewWalletFile("123154635",new File(getFilesDir(),""));`
```
 java.lang.OutOfMemoryError: Failed to allocate a 268435468 byte allocation with 6210868 free bytes and 183MB until OOM
                                                       at com.lambdaworks.crypto.SCrypt.scryptJ(SCrypt.java:93)
                                                       at com.lambdaworks.crypto.SCrypt.scrypt(SCrypt.java:48)
                                                       at org.web3j.crypto.Wallet.generateDerivedScryptKey(Wallet.java:135)
                                                       at org.web3j.crypto.Wallet.create(Wallet.java:72)
                                                       at org.web3j.crypto.Wallet.createStandard(Wallet.java:91)
                                                       at org.web3j.crypto.WalletUtils.generateWalletFile(WalletUtils.java:53)
                                                       at org.web3j.crypto.WalletUtils.generateNewWalletFile(WalletUtils.java:44)
                                                       at org.web3j.crypto.WalletUtils.generateFullNewWalletFile(WalletUtils.java:28)
                                                       at com.example.user.mywallet.MyTask.onHandleIntent(MyTask.java:50)
                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by Jevis** [comment]
ok  I change 3.1.1 to 2.2.1  and #193 I tried to copy "libscrypt.so" file from "wg/scrypt" library to my 'src/main/java/jniLibs/armeabi' folder ,and i work

**Comment by fishwjy** [comment]
I'm calling WalletUtils.loadCredentials, and out of memory. How to go back to 2.2.1?
I use " compile 'org.web3j:core:2.2.1-android' " in gradle. It failed
And where to get the libscrypt.so file?
Thanks for your reply.
