### ISSUE TITLE
error in blockObservable():  okhttp3.internal.http.RealResponseBody

### ISSUE THREAD

**Issue by alexprut** [web3j/web3j#366]
1. Using `Kotlin`, `web3j 3.2.0`, `Gradle`
2. Following the official documentation
```
override fun doWork() {
        val serviceLink = "https://mainnet.infura.io/${settings.getString("INFURA_IO_TOKEN")}"
        val web3 = Web3j.build(HttpService(serviceLink))
        logger.debug("Connected to Ethereum client version: " + web3.web3ClientVersion().send().getWeb3ClientVersion())

        val blockNumber = web3.ethBlockNumber().send()
        logger.debug(blockNumber.blockNumber.toString())

        val subscription = web3.blockObservable(false).subscribe({ block ->
            logger.debug("good job")
        }, {
            logger.debug(it.message)
            logger.debug(it.printStackTrace().toString())
        })
        logger.debug("ETH")
    }
```
Getting the following output and errors
```
Connected to Ethereum client version: Geth/v1.7.3-stable-dc78cb61/linux-amd64/go1.9.2
5100826
Invalid response received: okhttp3.internal.http.RealResponseBody@408f9b7d
org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: okhttp3.internal.http.RealResponseBody@408f9b7d
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:114)
	at org.web3j.protocol.Service.send(Service.java:31)
	at org.web3j.protocol.core.Request.send(Request.java:71)
	at org.web3j.protocol.core.filters.BlockFilter.sendRequest(BlockFilter.java:24)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:45)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:73)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethBlockHashObservable$8(JsonRpc2_0Rx.java:46)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.Observable.subscribe(Observable.java:10086)
```

It successfully connects to the `Geth` node, successfully gets the last block number, but, ..., the `blockObservable` subscription does not work, am I doing something wrong or there is an issue?

**Comment by alexprut** [comment]
I've tested with a private client endpoint and everything works, I think the problem is with `https://mainnet.infura.io`. It seems that they do not support the rpc call `blockObservable()` i.e. `eth_newBlockFilter`   

Source: https://github.com/INFURA/infura/blob/master/docs/source/index.html.md

**Comment by WilliamLann** [comment]
got it

**Comment by rayeaster** [comment]
any update on this issue? could we use block subscription if connecting to infura?
