### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 64

### ISSUE THREAD

**Issue by k06a** [web3j/web3j#376]
```
function info(string publicKey, uint256 hash, uint index) public constant returns(bytes32);
```
```
val item = contract.info(publicKey, hash, i)
                    .send()
                    .toString(Charset.defaultCharset())
                    .trim(Character.MIN_VALUE);
```
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 64
	at java.lang.String.substring(String.java:1963)
	at org.web3j.abi.TypeDecoder.decodeBytes(TypeDecoder.java:168)
	at org.web3j.abi.TypeDecoder.decode(TypeDecoder.java:61)
	at org.web3j.abi.FunctionReturnDecoder.build(FunctionReturnDecoder.java:120)
	at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:42)
	at org.web3j.tx.Contract.executeCall(Contract.java:159)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:165)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:176)
	at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:232)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at com.bitclave.node.repository.data.EthClientDataRepositoryImpl.readValueForKey(EthClientDataRepositoryImpl.kt:73)
	at com.bitclave.node.repository.data.EthClientDataRepositoryImpl.updateData(EthClientDataRepositoryImpl.kt:53)
	at com.bitclave.node.repository.data.ClientDataRepositoryStrategy.updateData(ClientDataRepositoryStrategy.kt:33)
	at com.bitclave.node.services.ClientProfileService$updateData$1.get(ClientProfileService.kt:33)
	at com.bitclave.node.services.ClientProfileService$updateData$1.get(ClientProfileService.kt:9)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by k06a** [comment]
Looks like `bytes32` zero value is not of length 64, but only 1:
<img width="1009" alt="2018-02-22 17 54 06" src="https://user-images.githubusercontent.com/702124/36545179-702804fe-17f9-11e8-8c63-6f4aac8177f4.png">

**Comment by k06a** [comment]
I am using `Ganache CLI v6.0.3 (ganache-core: 2.0.2)`

**Comment by k06a** [comment]
When I return `bytes32(1)` instead of `bytes32(0)` all works fine:
<img width="1193" alt="6373822773827327832" src="https://user-images.githubusercontent.com/702124/36546782-557e2076-17fd-11e8-8b0d-7859779a7254.png">

**Comment by k06a** [comment]
Temporarily avoided this issue by using deprecated `ethereumjs-testrpc` instead of `ganache-cli`, so will report issue to `ganache-cli`

**Comment by k06a** [comment]
Looks like contract address was wrong, thats was an error.

**Comment by iikirilov** [comment]
Is this resolved? Please close issue if it is.
