### ISSUE TITLE
UnsupportedOperationException: Invalid type provided (please help)

### ISSUE THREAD

**Issue by lectricas** [web3j/web3j#377]
```
Caused by: java.lang.UnsupportedOperationException: Invalid type provided org.web3j.abi.datatypes.generated.StaticArray6
02-22 14:19:31.540 11704-11704/ W/System.err:     at org.web3j.abi.Utils.getParameterizedTypeName(Utils.java:73)
02-22 14:19:31.540 11704-11704/ W/System.err:     at org.web3j.abi.Utils.getTypeName(Utils.java:32)
02-22 14:19:31.540 11704-11704/ W/System.err:     at org.web3j.abi.EventEncoder.buildMethodSignature(EventEncoder.java:45)
02-22 14:19:31.540 11704-11704/ W/System.err:     at org.web3j.abi.EventEncoder.encode(EventEncoder.java:25)
```

```
final Event event = new Event("Ticket", 
                Arrays.<TypeReference<?>>asList(),
                Arrays.<TypeReference<?>>asList(new TypeReference<Uint256>() {}, new TypeReference<Uint256>() {}, new TypeReference<Uint256>() {}, new TypeReference<Uint256>() {}, new TypeReference<Address>() {}, new TypeReference<StaticArray6<Uint256>>() {}, new TypeReference<StaticArray6<Uint256>>() {}));
        EthFilter filter = new EthFilter(startBlock, endBlock, getContractAddress());
        filter.addSingleTopic(EventEncoder.encode(event));
```

this is the part of generated contract file. Changing to` <StaticArray<Uint256>>` produces another error

**Comment by AlexandrouR** [comment]
Is this still an issue with the latest web3j version ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.

**Comment by fextr** [comment]
Hey, @AlexandrouR! I have the same exception when I try to encode event, that has been generated with the help of Web3j CLI
Exception:
```
Caused by: java.lang.UnsupportedOperationException: Invalid type provided org.web3j.abi.datatypes.generated.StaticArray3
	at org.web3j.abi.Utils.getParameterizedTypeName(Utils.java:95) ~[abi-4.8.8.jar:na]
	at org.web3j.abi.Utils.getTypeName(Utils.java:50) ~[abi-4.8.8.jar:na]
	at org.web3j.abi.EventEncoder.lambda$buildMethodSignature$0(EventEncoder.java:45) ~[abi-4.8.8.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at org.web3j.abi.EventEncoder.buildMethodSignature(EventEncoder.java:45) ~[abi-4.8.8.jar:na]
	at org.web3j.abi.EventEncoder.encode(EventEncoder.java:33) ~[abi-4.8.8.jar:na]

```
Example:
```
public static final Event BADDEPOSIT_EVENT = new Event("BadDeposit", 
            Arrays.<TypeReference<?>>asList(new TypeReference<Address>() {}, new TypeReference<StaticArray3<Uint256>>() {}, new TypeReference<Uint256>() {}));

EventEncoder.encode(BADDEPOSIT_EVENT);
```
Version of web3j is 4.8.8
