### ISSUE TITLE
NPE at org.web3j.utils.Numeric.containsHexPrefix(Numeric.java:80)

### ISSUE THREAD

**Issue by asoldano** [web3j/web3j#402]
Hi,
I'm getting a NPE when calling a view function in a contract that returns an out-of-gas error. Using v. 3.3.1 and ganache-cli locally.
It looks like FunctionReturnDecoder/Numeric need to return null in such case, so that at least the client gets a decent error message.

java.lang.NullPointerException
	at org.web3j.utils.Numeric.containsHexPrefix(Numeric.java:80)
	at org.web3j.utils.Numeric.cleanHexPrefix(Numeric.java:64)
	at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:37)
	at org.web3j.tx.Contract.executeCall(Contract.java:178)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:184)
	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:195)
	at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:251)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
        [...]

**Comment by VanLuong1996** [comment]
do you fix it

**Comment by AlexandrouR** [comment]
Looks like this issue was resolved and merged.
