### ISSUE TITLE
Event history exception only for my contract with many events (100k+)

### ISSUE THREAD

**Issue by axcrest** [web3j/web3j#415]
I am using Web3J 3.3.1.  Here are the main snippets of my subscribe code...

```
this.event = new Event("RewardedUser",
                Arrays.asList(),
                Arrays.asList(new TypeReference<Address>() {},
                              new TypeReference<Uint256>() {},
                              new TypeReference<Utf8String>() {}));

String encodedEventSignature = EventEncoder.encode(event);
EthFilter filter = new EthFilter(DefaultBlockParameterName.EARLIEST, DefaultBlockParameterName.LATEST, "0x1b31d19b6a9a942bbf3c197ca1e5efede3ff8ff2");
filter.addSingleTopic(encodedEventSignature);

web3j.ethLogObservable(filter).subscribe(rewardedEventProcessor);
```
// rewardedEventProcessor then implements this
```
    @Override
    public void onNext(Log log) {
        try {
            process(log);
        }
        catch (Exception ex) {
            logger.error("exception during reward user", ex);
        }
    }
```

I get the following error everytime:

```
org.web3j.protocol.core.filters.FilterException: Error sending request
	at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:156)
	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:101)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:53)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:73)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogObservable$2(JsonRpc2_0Rx.java:65)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at com.radicalapp.gmteventsubscriber.EventSubscriber.launch(EventSubscriber.java:46)
	at com.radicalapp.gmteventsubscriber.GmtEventSubscriberApplication.run(GmtEventSubscriberApplication.java:27)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.radicalapp.gmteventsubscriber.GmtEventSubscriberApplication.main(GmtEventSubscriberApplication.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:104)
	at org.web3j.protocol.Service.send(Service.java:31)
	at org.web3j.protocol.core.Request.send(Request.java:71)
	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:93)
	... 22 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 45 more
```

NOTE1: I was using Web3J 3.1.1 and would get no error, but the code would just hang after letting it run for several hours.  
NOTE2: I wrote Javascript code to do the exact same thing and that one works fine.  I get all the events.  It takes about 30 minutes though.
NOTE3: I am running a Rinkeby "full" node

**Comment by axcrest** [comment]
Can someone see if they can replicate the above error?

**Comment by LoganYuan** [comment]
I also encountered this problem. Is there a solution?

**Comment by axcrest** [comment]
Unfortunately there is no solution using Web3J yet.  I'm still waiting for someone at Web3J to address it.  My work around was to write an event listener using web3.js.

**Comment by oakcookies** [comment]
I met the same issue and I plan to address it in a dumb but safer way. 
1. createFilter(startBlkNum, EndBlkNum, topic)
2. getFilterLogs -> get all events within that range (and with error handling and retry )
3. uninstallFilter
4. update startBlkNum and EndBlkNum and go back to step one.

If there are better methods, I would love to hear that. Thanks !

**Comment by zhjgit** [comment]
I also encountered this problem. Is there a solution?

**Comment by axcrest** [comment]
@zhjgit I wrote a script using web3.js to do it.  I can share with you a code snippet if you like.

**Comment by xiaods** [comment]
I also encountered this problem.

**Comment by AlexandrouR** [comment]
is this still an issue with the latest version of web3j?

**Comment by developer1-belfrics** [comment]
Same issue is occurring to me also, but when I restart the server it working fine, but after some time same issue retained in the server. Anyone give a better solution to solve the issue
