### ISSUE TITLE
eth_uninstallFilter invoked after a while

### ISSUE THREAD

**Issue by fcorneli** [web3j/web3j#429]
I have a simple test:
```
Web3j web3 = Web3j.build(new HttpService("http://localhost:8545"));
web3.pendingTransactionObservable().subscribe(tx -> {
            LOGGER.debug("incoming pending transactions...");
});
web3.blockObservable(true).subscribe(ethBlock -> {
            LOGGER.debug("incoming block...");
});
```
Watching the `HttpService` debug logs, the `eth_newPendingTransactionFilter` gets canceled automatically after receiving a first batch via an `eth_uninstallFilter` call. Is this normal, or a bug? I don't see any exception popping up.

**Comment by fcorneli** [comment]
Issue boils down to:
```
Web3j pendingWeb3 = Web3j.build(new HttpService("http://localhost:8545"));
pendingWeb3.pendingTransactionObservable().subscribe(tx -> {
            LOGGER.debug("incoming pending transactions...");
});
```

After a while, "something" seems to invoke `eth_uninstallFilter` while I never explicitly `cancel` the filter.

**Comment by fcorneli** [comment]
This `eth_uninstallFilter`seems to be invoked right after a `eth_getTransactionByHash` returns `null` as `result`.

**Comment by fcorneli** [comment]
Corresponding debug logs:
```
DEBUG [HttpService] <-- END HTTP (728-byte body)
DEBUG [EthereumTest] incoming pending transactions...
DEBUG [HttpService] --> POST http://localhost:8545/ http/1.1
DEBUG [HttpService] Content-Type: application/json; charset=utf-8
DEBUG [HttpService] Content-Length: 141
DEBUG [HttpService] 
DEBUG [HttpService] {"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0xd611470fec928b445a97cdc6800f246e9ef49b5c56926c2388306814535d850a"],"id":72}
DEBUG [HttpService] --> END POST (141-byte body)
DEBUG [HttpService] <-- 200 OK http://localhost:8545/ (3ms)
DEBUG [HttpService] Content-Type: application/json
DEBUG [HttpService] Date: Fri, 16 Mar 2018 08:01:40 GMT
DEBUG [HttpService] Content-Length: 40
DEBUG [HttpService] 
DEBUG [HttpService] {"jsonrpc":"2.0","id":72,"result":null}

DEBUG [HttpService] <-- END HTTP (40-byte body)
DEBUG [HttpService] --> POST http://localhost:8545/ http/1.1
DEBUG [HttpService] Content-Type: application/json; charset=utf-8
DEBUG [HttpService] Content-Length: 104
DEBUG [HttpService] 
DEBUG [HttpService] {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x3ceef159e5bff8e0dfbe3551cd37b56f"],"id":73}
DEBUG [HttpService] --> END POST (104-byte body)
DEBUG [HttpService] <-- 200 OK http://localhost:8545/ (1ms)
DEBUG [HttpService] Content-Type: application/json
DEBUG [HttpService] Date: Fri, 16 Mar 2018 08:01:40 GMT
DEBUG [HttpService] Content-Length: 40
DEBUG [HttpService] 
DEBUG [HttpService] {"jsonrpc":"2.0","id":73,"result":true}
```

**Comment by fcorneli** [comment]
Changing the test to:
```
Web3j pendingWeb3 = Web3j.build(new HttpService("http://localhost:8545"));
pendingWeb3.pendingTransactionObservable().subscribe(tx -> {
            LOGGER.debug("incoming pending transactions...");
}, error -> {
            error.printStackTrace();
});
```
Given me indeed an exception:
```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$pendingTransactionObservable$4(JsonRpc2_0Rx.java:86)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at org.web3j.protocol.core.RemoteCall.lambda$observable$0(RemoteCall.java:51)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at org.web3j.protocol.core.filters.PendingTransactionFilter.process(PendingTransactionFilter.java:32)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:115)
	at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: org.web3j.protocol.core.methods.response.EthTransaction.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
```

**Comment by fcorneli** [comment]
Same issue here: #144

**Comment by fcorneli** [comment]
Problem seems to be with `JsonRpc2_0Rx.pendingTransactionObservable` that should be capable of handling a null element.

**Comment by fcorneli** [comment]
Quick and dirty patch fixes the issue:
```
public Observable<Transaction> pendingTransactionObservable(long pollingInterval) {
        return ethPendingTransactionHashObservable(pollingInterval)
                .filter(transactionHash -> {
                    try {
                        return web3j.ethGetTransactionByHash(transactionHash).send().getTransaction().isPresent();
                    } catch (Exception ex) {
                        return false;
                    }
                })
                .flatMap(transactionHash -> web3j.ethGetTransactionByHash(transactionHash).observable())
                .map(ethTransaction -> ethTransaction.getTransaction().get());
    }
```
Of course we should not `ethGetTransactionByHash`twice...

**Comment by fcorneli** [comment]
PR available at: https://github.com/web3j/web3j/pull/430
