### ISSUE TITLE
Writing operations on a contract always throw "java.lang.ArrayIndexOutOfBoundsException"

### ISSUE THREAD

**Issue by 12alex21** [web3j/web3j#431]
Read operations are successfull. Writing returns the following error:
`java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.bouncycastle.crypto.signers.HMacDSAKCalculator.init(Unknown Source)
	at org.bouncycastle.crypto.signers.ECDSASigner.generateSignature(Unknown Source)
	at org.web3j.crypto.ECKeyPair.sign(ECKeyPair.java:46)
	at org.web3j.crypto.Sign.signMessage(Sign.java:52)
	at org.web3j.crypto.Sign.signMessage(Sign.java:40)
	at org.web3j.crypto.TransactionEncoder.signMessage(TransactionEncoder.java:21)
	at org.web3j.tx.RawTransactionManager.signAndSend(RawTransactionManager.java:102)
	at org.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:91)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:49)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:83)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:242)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:226)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:220)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:259)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at com.enablingu.api.v1.contract.ContractDocumentPayload.postDocumentPayload(ContractDocumentPayload.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:409)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)`

I am using the following code:

String hexPrivateKey = String.format("%040x", new BigInteger(1, Config.privateKey.getBytes()));
String hexPublicKey = String.format("%040x", new BigInteger(1, Config.publicKey.getBytes()));
Credentials credentials = Credentials.create(hexPrivateKey, hexPublicKey);
DataSaver contract = DataSaver.load(
address, web3j, credentials, Contract.GAS_PRICE, Contract.GAS_LIMIT);

RemoteCall transaction2 = contract.updateDocumentPayload(
BigInteger.valueOf(1), "Test");
transaction2.send();

Can you tell me, what I am doing wrong? Is there a bug?

Thanks alot in advance

Alex

**Comment by italobb** [comment]
https://stackoverflow.com/a/49367520/439171

**Comment by 12alex21** [comment]
That was it 👍  Thank you so much 😄
