### ISSUE TITLE
Integration tests fail locally

### ISSUE THREAD

**Issue by mushketyk** [web3j/web3j#441]
When I run the following command to run integration tests on my dev machine:

```
./gradlew  -Pintegration-tests=true :integration-tests:test
```

I get lots of test failures like:

```
org.web3j.protocol.core.CoreIT > testEthProtocolVersion STANDARD_OUT
    22:06:58.263 [Test worker] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
    22:06:58.263 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
    22:06:58.263 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 67
    22:06:58.263 [Test worker] DEBUG org.web3j.protocol.http.HttpService -
    22:06:58.263 [Test worker] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_protocolVersion","params":[],"id":2}
    22:06:58.263 [Test worker] DEBUG org.web3j.protocol.http.HttpService - --> END POST (67-byte body)
    22:06:58.265 [Test worker] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (1ms)
    22:06:58.265 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
    22:06:58.266 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Date: Wed, 21 Mar 2018 22:06:58 GMT
    22:06:58.266 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 43
    22:06:58.266 [Test worker] DEBUG org.web3j.protocol.http.HttpService -
    22:06:58.266 [Test worker] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":2,"result":"0x2712"}

    22:06:58.266 [Test worker] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (43-byte body)

org.web3j.protocol.core.CoreIT > testEthGetBlockTransactionCountByHash STANDARD_OUT
    22:06:58.276 [Test worker] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
    22:06:58.276 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
    22:06:58.276 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 150
    22:06:58.276 [Test worker] DEBUG org.web3j.protocol.http.HttpService -
    22:06:58.277 [Test worker] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_getBlockTransactionCountByHash","params":["0xd67e59db999c3bd78bd4c2ba54689dba0c372ebcad09c8b9677970f37d64ca46"],"id":3}
    22:06:58.277 [Test worker] DEBUG org.web3j.protocol.http.HttpService - --> END POST (150-byte body)
    22:06:58.278 [Test worker] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (1ms)
    22:06:58.279 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
    22:06:58.279 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Date: Wed, 21 Mar 2018 22:06:58 GMT
    22:06:58.279 [Test worker] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 39
    22:06:58.279 [Test worker] DEBUG org.web3j.protocol.http.HttpService -
    22:06:58.279 [Test worker] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":3,"result":null}

    22:06:58.280 [Test worker] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (39-byte body)

org.web3j.protocol.core.CoreIT > testEthGetBlockTransactionCountByHash FAILED
    org.web3j.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
        at org.web3j.utils.Numeric.decodeQuantity(Numeric.java:32)
        at org.web3j.protocol.core.methods.response.EthGetBlockTransactionCountByHash.getTransactionCount(EthGetBlockTransactionCountByHash.java:13)
        at org.web3j.protocol.core.CoreIT.testEthGetBlockTransactionCountByHash(CoreIT.java:185)
```

I guess that I need to correctly set up a `geth` instance, but I didn't find any documentation about how to do this.

Is this assumption correct? How can I configure my development environment to run integration tests?

**Comment by ricmoo** [comment]
I cannot get the integration test cases to work. Did you ever figure out your issue? I have a local node running.

```
> ./gradlew  -Pintegration-tests=true :integration-tests:test

[ ... Lots of warnings ... ]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integration-tests:test'.
> failed to read class file /home/ricmoo/dev/web3j/integration-tests/build/classes/java/test/org/web3j/generated/Arrays.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
20 actionable tasks: 5 executed, 15 up-to-date
```

**Comment by franz-see** [comment]
I've been able to run the tests locally, but I believe the tests need to be updated to make them to pass.

You need to install geth and run `geth --rpcapi personal,db,eth,net,web3 --rpc --testnet`, and then run the integration test `./gradlew  -Pintegration-tests=true :integration-tests:test` (in another terminal while geth is still running). 

However, even after you do that, there would still be a lot of failing tests - partly because some test data have not yet been updated and partly because geth is still syncing and is still not fully available. 

Alternatively, you can use [Infura](https://web3j.github.io/web3j/infura.html) so that it's fully synced immediately, but then there would still be failing tests because there are methods that Infura does not support.

**Comment by franz-see** [comment]
I've created a pull request to fix this - https://github.com/web3j/web3j/pull/661

**Comment by franz-see** [comment]
FYI, I just updated the PR so that it works on actual geth and parity as well. 

<img width="1323" alt="integration tests results" src="https://user-images.githubusercontent.com/499668/43928302-f6cb39b6-9c62-11e8-99d7-0e07d5a97b4d.png">

**Comment by AlexandrouR** [comment]
is this still an issue ?

**Comment by franz-see** [comment]
I dont know. I submitted a PR last year and it was working as of last year. Not sure if it got reviewed :) The code has probably greatly diverged as well making my PR outdated :)

**Comment by franz-see** [comment]
Integration tests are still failing

**Comment by franz-see** [comment]
.

**Comment by meijiesky** [comment]
Still can't pass the tests locally. Anyone?
