### ISSUE TITLE
java.lang.OutOfMemoryError on android

### ISSUE THREAD

**Issue by Giudici-a** [web3j/web3j#448]
Hi,

I try to use your library to create my own wallet app just to learn how it work on android, but i get a strange exception when i tried to loadCredentials like this:
`private Boolean getWallet(String password, File dir) throws Exception {
        this.myWallet = WalletUtils.loadCredentials(password, dir);
        this.address = this.myWallet.getAddress();
        Log.d(TAG, this.address);
        //a tester
        return this.address == null;
    }`

I get this exception : java.lang.OutOfMemoryError, i'am sure my wallet file is valid because i select it from a FileDialog that i made and it always worked before. (and i did some test today to be sure it was not that, and the exception should be different if it was the problem).

i saw other issues about this subject but the solution doesn't work for me.

So if someone can help me it could be wonderful.

Thanks for your reading.

**Comment by iikirilov** [comment]
@Giudici-a could you tag the possibly related issue and post a full stacktrace

**Comment by Giudici-a** [comment]
Hi, of course:

`3-26 17:35:10.796 14444-14444/com.example.aureliengiudici.ethrade E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     java.lang.OutOfMemoryError
                                                                                         at org.spongycastle.util.Arrays.clone(Arrays.java:602)
                                                                                         at org.spongycastle.crypto.generators.SCrypt.SMix(SCrypt.java:126)
                                                                                         at org.spongycastle.crypto.generators.SCrypt.MFcrypt(SCrypt.java:87)
                                                                                         at org.spongycastle.crypto.generators.SCrypt.generate(SCrypt.java:66)
                                                                                         at org.web3j.crypto.Wallet.generateDerivedScryptKey(Wallet.java:136)
                                                                                         at org.web3j.crypto.Wallet.decrypt(Wallet.java:214)
                                                                                         at org.web3j.crypto.WalletUtils.loadCredentials(WalletUtils.java:82)
                                                                                         at com.example.aureliengiudici.ethrade.Contracts.WalletConfiguration.getWallet(WalletConfiguration.java:108)
                                                                                         at com.example.aureliengiudici.ethrade.Contracts.WalletConfiguration.start(WalletConfiguration.java:56)
                                                                                         at com.example.aureliengiudici.ethrade.MainActivity.openWalletFile(MainActivity.java:135)
                                                                                         at com.example.aureliengiudici.ethrade.MainActivity.access$100(MainActivity.java:32)
                                                                                         at com.example.aureliengiudici.ethrade.MainActivity$1.fileSelected(MainActivity.java:70)
                                                                                         at com.example.aureliengiudici.ethrade.Utils.FileDialog$3.fireEvent(FileDialog.java:116)
                                                                                         at com.example.aureliengiudici.ethrade.Utils.FileDialog$3.fireEvent(FileDialog.java:114)
                                                                                         at com.example.aureliengiudici.ethrade.Utils.ListenerList.fireEvent(FileDialog.java:177)
                                                                                         at com.example.aureliengiudici.ethrade.Utils.FileDialog.fireFileSelectedEvent(FileDialog.java:114)
                                                                                         at com.example.aureliengiudici.ethrade.Utils.FileDialog.access$600(FileDialog.java:19)
                                                                                         at com.example.aureliengiudici.ethrade.Utils.FileDialog$2.onClick(FileDialog.java:77)
                                                                                         at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:963)
                                                                                         at android.widget.AdapterView.performItemClick(AdapterView.java:298)
                                                                                         at android.widget.AbsListView.performItemClick(AbsListView.java:1128)
                                                                                         at android.widget.AbsListView$PerformClick.run(AbsListView.java:2812)
                                                                                         at android.widget.AbsListView$1.run(AbsListView.java:3571)
                                                                                         at android.os.Handler.handleCallback(Handler.java:725)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                         at android.os.Looper.loop(Looper.java:153)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5297)
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                                         at dalvik.system.NativeStart.main(Native Method)`

the function where i do the loadCredentials is the getWallet.

**Comment by kagile** [comment]
Still happening with 
    `api ('org.web3j:core:4.1.0-android')
`

**Comment by kagile** [comment]
Stacktrace:

**Comment by kagile** [comment]
Using [Conceal](https://github.com/facebook/conceal/) an Android instead of bouncycastle may solve the problem

**Comment by kagile** [comment]
Can anyone please provide a temporary solution to this?

**Comment by alexroan** [comment]
> Can anyone please provide a temporary solution to this?

Try this: https://github.com/web3j/web3j/issues/299#issuecomment-395941914
