### ISSUE TITLE
IPC Request/Response threading issue

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#471]
I can see response JSON is forwarded to wrong thread (see request with id=623 is sent from main thread, but response to main thread came for request with id=625, obviously it can't be parsed because another response structure is expected):
```
00:45:18.603 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x30e2c248a5a44ace8519e1b4a0dc36c2"],"id":609}
00:45:18.614 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":609,"result":true}

00:45:18.615 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0xfc8e6a163d3a360bc4507ba3d2303ab8"],"id":610}
00:45:18.626 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":610,"result":true}

00:45:18.626 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x3808d1194aed334244c1b2aed48b758e"],"id":611}
00:45:18.638 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":611,"result":true}

00:45:18.639 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x9db806819162cb62f6c737efd53bb2a9"],"id":612}
00:45:18.673 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":612,"result":true}

00:45:18.674 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x6bc4c429ba320a2ed9eb45ec5de549a7"],"id":613}
00:45:18.696 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":613,"result":true}

00:45:18.696 [pool-2-thread-1] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xa93bcf648afbea2332b3f2895992b960"],"id":614}
00:45:18.711 [pool-2-thread-1] DEBUG IpcService - << {"jsonrpc":"2.0","id":614,"result":[]}

00:45:18.711 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0xd01645ecf1d7cb9332f5528041025bb5"],"id":615}
00:45:18.718 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":615,"result":true}

00:45:18.718 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x85e72f706b654ae30efcbf7484877537"],"id":616}
00:45:18.730 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":616,"result":true}

00:45:18.730 [pool-2-thread-3] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xf305b11b9f27b8a9facc24aa83b8f9dc"],"id":617}
00:45:18.741 [pool-2-thread-3] DEBUG IpcService - << {"jsonrpc":"2.0","id":617,"result":[]}

00:45:18.741 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0xb900f86edbbae1bfb5ad41bfadcb8303"],"id":618}
00:45:18.752 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":618,"result":true}

00:45:18.752 [pool-2-thread-2] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xfffd59f6ddb75f77432c79bcbd2376a6"],"id":619}
00:45:18.763 [pool-2-thread-2] DEBUG IpcService - << {"jsonrpc":"2.0","id":619,"result":[]}

00:45:18.763 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0xfed84d7b4e82ac278d15841480a3bc57"],"id":620}
00:45:18.773 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":620,"result":true}

00:45:18.773 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0xa8f486d3eb332552ad56cd3ad8d384f1"],"id":621}
00:45:18.808 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":621,"result":true}

00:45:18.809 [pool-2-thread-4] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x17c89e8f89b83fb5ea9deafa50f55810"],"id":622}
00:45:18.830 [pool-2-thread-4] DEBUG IpcService - << {"jsonrpc":"2.0","id":622,"result":[]}

00:45:18.830 [pool-2-thread-1] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x4d21482ed83c9915d0da8aedd0d9b98a"],"id":624}
00:45:18.830 [pool-2-thread-3] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xb47d1d02f4cb33d994d203ad12d4e15a"],"id":625}
00:45:18.830 [main] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x3d841592387edc31829c68bf6837a17"],"id":623}
Exception in thread "main" org.web3j.protocol.core.filters.FilterException: Error sending request
	at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:156)
	at org.web3j.protocol.core.filters.Filter.cancel(Filter.java:136)
	at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
	at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
	at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
	at rx.Subscriber.unsubscribe(Subscriber.java:98)
	at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
	at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
	at rx.Subscriber.unsubscribe(Subscriber.java:98)
	at name.antonsmirnov.apptogether.ethereum.EthereumProcessorImpl.unsubscribe(EthereumProcessorImpl.java:502)
	at name.antonsmirnov.apptogether.ethereum.EthereumProcessorImpl.stop(EthereumProcessorImpl.java:494)
	at name.antonsmirnov.apptogether.Backend.doStop(Backend.java:327)
	at name.antonsmirnov.apptogether.Backend.stop(Backend.java:318)
	at name.antonsmirnov.apptogether.BackendApp.main(BackendApp.java:171)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.Boolean out of START_ARRAY token
 at [Source: java.io.ByteArrayInputStream@ea9e141; line: 1, column: 36] (through reference chain: org.web3j.protocol.core.methods.response.EthUninstallFilter["result"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseBoolean(StdDeserializer.java:220)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BooleanDeserializer.deserialize(NumberDeserializers.java:178)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$BooleanDeserializer.deserialize(NumberDeserializers.java:161)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
	at org.web3j.protocol.Service.send(Service.java:33)
	at org.web3j.protocol.core.Request.send(Request.java:71)
	at org.web3j.protocol.core.filters.Filter.cancel(Filter.java:127)
	... 12 more
00:45:18.853 [pool-2-thread-1] DEBUG IpcService - << {"jsonrpc":"2.0","id":624,"result":[]}

00:45:18.854 [main] DEBUG IpcService - << {"jsonrpc":"2.0","id":625,"result":[]}

00:45:18.866 [pool-2-thread-3] DEBUG IpcService - << {"jsonrpc":"2.0","id":623,"result":true}

00:45:18.888 [pool-2-thread-2] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x6820fd340ae0292ba62decc06d59ff59"],"id":626}
00:45:18.898 [pool-2-thread-2] DEBUG IpcService - << {"jsonrpc":"2.0","id":626,"result":[]}

00:45:18.930 [pool-2-thread-4] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x8975313fa1c80a733880d0535e30e5bd"],"id":627}
00:45:18.932 [pool-2-thread-4] DEBUG IpcService - << {"jsonrpc":"2.0","id":627,"result":[]}

00:45:19.194 [threadDeathWatcher-1-1] DEBUG Slf4JLogger - Freed 4 thread-local buffer(s) from thread: threadDeathWatcher-1-1
00:45:19.520 [grpc-default-worker-ELG-4-1] DEBUG Slf4JLogger - Freed 15 thread-local buffer(s) from thread: grpc-default-worker-ELG-4-1
00:45:24.456 [pool-2-thread-1] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x7d747a96e07feec1361852354150105"],"id":628}
00:45:24.467 [pool-2-threa
```

**Comment by 4ntoine** [comment]
same here (id=970):
```
0:55:27.863 [pool-2-thread-4] DEBUG EthereumProcessorImpl - Block processed: org.web3j.protocol.core.methods.response.EthBlock@2a4d1f6e with number 855
00:55:27.863 [pool-2-thread-4] INFO  Backend$1 - Saving eth block 855 ...
00:55:27.864 [pool-2-thread-4] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x358",false],"id":965}
00:55:27.873 [pool-2-thread-4] DEBUG IpcService - << {"jsonrpc":"2.0","id":965,"result":{"difficulty":"0x306c3","extraData":"0xd883010703846765746887676f312e392e328664617277696e","gasLimit":"0xe4ff1c","gasUsed":"0x0","hash":"0x615f727bd6bf72155eb1dcc864ab0d83e7427e2f13b91d78da1cf67a11319c42","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x00770642bdd7cc3057e16569320cfb2e778c1c99","mixHash":"0x826f7fa5428abf8adcbfb9616e3393bffd0468a8daa49aef909f3774ac224460","nonce":"0x712c7a46beb023c3","number":"0x358","parentHash":"0x6553d92384cee0b5a1c7c742896e6ca0a9c106e7785995eb0e02816d8b8c449b","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x21a","stateRoot":"0x754872da6b09154a0fa5d5d41924e34ba439e250b818f0446f2445dd3c1b0204","timestamp":"0x5ac3dc19","totalDifficulty":"0x8497b20","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}

00:55:27.873 [pool-2-thread-4] DEBUG EthereumProcessorImpl - Block processed: org.web3j.protocol.core.methods.response.EthBlock@84e0b7b with number 856
00:55:27.874 [pool-2-thread-4] INFO  Backend$1 - Saving eth block 856 ...
00:55:27.874 [pool-2-thread-4] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x359",false],"id":966}
00:55:27.883 [pool-2-thread-4] DEBUG IpcService - << {"jsonrpc":"2.0","id":966,"result":{"difficulty":"0x30723","extraData":"0xd883010703846765746887676f312e392e328664617277696e","gasLimit":"0xe4c5de","gasUsed":"0x0","hash":"0x5d06710c8cd00a574b1222ca13cbb9ef691f0de503c318bce47b3aa84595e6f2","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x00770642bdd7cc3057e16569320cfb2e778c1c99","mixHash":"0x7ed34de578eb3c31b5d2210ac59e90fc348f32abe64b1e9dd3b11436420c501f","nonce":"0x4ee22dc364d2beac","number":"0x359","parentHash":"0x615f727bd6bf72155eb1dcc864ab0d83e7427e2f13b91d78da1cf67a11319c42","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x21a","stateRoot":"0xd6a23b1293140d86ed7fa7ff188838a3cef0fa9aa1828702070d93704a18a1fa","timestamp":"0x5ac3dc1a","totalDifficulty":"0x84c8243","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}

00:55:27.884 [pool-2-thread-4] DEBUG EthereumProcessorImpl - Block processed: org.web3j.protocol.core.methods.response.EthBlock@44f39281 with number 857
00:55:27.885 [pool-2-thread-4] INFO  Backend$1 - Saving eth block 857 ...
00:55:27.885 [pool-2-thread-4] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x35a",false],"id":967}
00:55:27.894 [pool-2-thread-4] DEBUG IpcService - << {"jsonrpc":"2.0","id":967,"result":{"difficulty":"0x30783","extraData":"0xd883010703846765746887676f312e392e328664617277696e","gasLimit":"0xe48cae","gasUsed":"0x0","hash":"0x233a9cd754c15209c9ba7b385f6a11aa29ac159e1411255b8a38353ff040b02b","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x00770642bdd7cc3057e16569320cfb2e778c1c99","mixHash":"0x973dec257feaf5618ac59702154dde8986276cd6c73b45a809ce73107567c858","nonce":"0x68ecc6b8fbd47f28","number":"0x35a","parentHash":"0x5d06710c8cd00a574b1222ca13cbb9ef691f0de503c318bce47b3aa84595e6f2","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x21a","stateRoot":"0xd659951f061c8dbaf6cba1b85e884636dec7de52a136caa803e571af508e43d1","timestamp":"0x5ac3dc1b","totalDifficulty":"0x84f89c6","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}

00:55:27.894 [pool-2-thread-4] DEBUG EthereumProcessorImpl - Block processed: org.web3j.protocol.core.methods.response.EthBlock@11c1cc7f with number 858
00:55:27.894 [pool-2-thread-4] INFO  Backend$1 - Saving eth block 858 ...
00:55:27.894 [pool-2-thread-4] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x35b",false],"id":968}
00:55:27.907 [pool-2-thread-4] DEBUG IpcService - << {"jsonrpc":"2.0","id":968,"result":{"difficulty":"0x307e3","extraData":"0xd883010703846765746887676f312e392e328664617277696e","gasLimit":"0xe4538c","gasUsed":"0x580c48","hash":"0xec4bb857b1f35d44fccb00ab5c4e1846be99ed56acc691252723d97dc2e7e75e","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x00770642bdd7cc3057e16569320cfb2e778c1c99","mixHash":"0xf002b6294549d6471fab2b2e40737b06d3a7fd8b71da84c9dbffa0de1563a01e","nonce":"0x6bb78c9813d47e27","number":"0x35b","parentHash":"0x233a9cd754c15209c9ba7b385f6a11aa29ac159e1411255b8a38353ff040b02b","receiptsRoot":"0x122208faa5ea3a8005dc29bd52e0aeefa5cbc807ba216e007cd04f53fa089b31","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x55ed","stateRoot":"0x869b567c66745b9c4d56e9efaaa401d72fb0e17516af87884b9d743f01580fad","timestamp":"0x5ac3dc20","totalDifficulty":"0x85291a9","transactions":["0x53dd400eb179266cecb8080b9aaa40da8b472426cb267641f661066ac96424e8"],"transactionsRoot":"0x78963014ee670db378de136e714d6693e2cebc1a5267c47edcff42297c7bf4c5","uncles":[]}}

00:55:27.907 [pool-2-thread-4] DEBUG EthereumProcessorImpl - Block processed: org.web3j.protocol.core.methods.response.EthBlock@751f20e3 with number 859
00:55:27.907 [pool-2-thread-4] INFO  Backend$1 - Saving eth block 859 ...
00:55:27.909 [pool-2-thread-4] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false],"id":969}
00:55:27.909 [pool-2-thread-2] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xcecd3f718f81136f4ad51eb81fe242ab"],"id":970}
00:55:27.915 [pool-2-thread-4] DEBUG IpcService - << {"jsonrpc":"2.0","id":970,"result":[]}

00:55:27.916 [pool-2-thread-2] DEBUG IpcService - << {"jsonrpc":"2.0","id":969,"result":{"difficulty":"0x30966","extraData":"0xd883010703846765746887676f312e392e328664617277696e","gasLimit":"0xe39080","gasUsed":"0x0","hash":"0xbd8bebef7a65cc6ddd242d6db4e61ba8b42398163af9b3ea24351a5fddd49f03","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x00770642bdd7cc3057e16569320cfb2e778c1c99","mixHash":"0x60afab0f496d57c84e02f3f72714fecd887756a4852d9af9773aa196fb709f05","nonce":"0x682da357931d602c","number":"0x35f","parentHash":"0xb2959e2d23ea27167a2999fdd1e402a93d0df333918012d41218fcfb4f31837f","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x21a","stateRoot":"0x4824537d907eb0a15cb2a889a08f6a69b8af13924bde72af2bab04d0f8737b1d","timestamp":"0x5ac3dc2f","totalDifficulty":"0x85eb4fb","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}

Exception in thread "pool-2-thread-4" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: Can not deserialize instance of org.web3j.protocol.core.methods.response.EthBlock$Block out of START_ARRAY token
 at [Source: java.io.ByteArrayInputStream@7fedbb82; line: 1, column: 36] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"])
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:152)
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerError(OnSubscribeConcatMap.java:192)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onError(OnSubscribeConcatMap.java:340)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.slowPath(OnSubscribeFromArray.java:100)
	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:63)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 8 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.web3j.protocol.core.methods.response.EthBlock$Block out of START_ARRAY token
 at [Source: java.io.ByteArrayInputStream@7fedbb82; line: 1, column: 36] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1370)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:981)
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:561)
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:552)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
	at org.web3j.protocol.Service.send(Service.java:33)
	at org.web3j.protocol.core.Request.send(Request.java:71)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.getBlockNumber(JsonRpc2_0Rx.java:226)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.getLatestBlockNumber(JsonRpc2_0Rx.java:217)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.catchUpToLatestBlockObservableSync(JsonRpc2_0Rx.java:173)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$catchUpToLatestBlockObservableSync$8(JsonRpc2_0Rx.java:186)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	... 23 more
00:55:28.007 [pool-2-thread-1] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x3ae968bdc252f5e1af5c891f77fe0ff2"],"id":971}
00:55:28.051 [pool-2-thread-1] DEBUG IpcService - << {"jsonrpc":"2.0","id":971,"result":[]}

00:55:28.051 [pool-2-thread-3] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x65ef39913a40f711b8ae0448b7135706"],"id":972}
00:55:28.070 [pool-2-thread-3] DEBUG IpcService - << {"jsonrpc":"2.0","id":972,"result":[]}

00:55:28.150 [pool-2-thread-2] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x901618417dfa6fe86c5b402baf1466bb"],"id":973}
00:55:28.158 [pool-2-thread-2] DEBUG IpcService - << {"jsonrpc":"2.0","id":973,"result":[]}

00:55:28.210 [pool-2-thread-4] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x4ce079fbe58ec03fa3473b5d407adfc2"],"id":974}
00:55:28.216 [pool-2-thread-4] DEBUG IpcService - << {"jsonrpc":"2.0","id":974,"result":[]}

00:55:28.261 [pool-2-thread-1] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x15dd19e3078f91850e5d4214c0cdfb99"],"id":975}
00:55:28.288 [pool-2-thread-1] DEBUG IpcService - << {"jsonrpc":"2.0","id":975,"result":[]}

00:55:28.327 [pool-2-thread-3] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xa8b8b4159b3dc87ac62f4461f10be9fc"],"id":976}
00:55:28.331 [pool-2-thread-3] DEBUG IpcService - << {"jsonrpc":"2.0","id":976,"result":[]}

00:55:28.421 [pool-2-thread-2] DEBUG IpcService - >> {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xcabd5e9701d493473dae4f6e05305f1b"],"id":977}
00:55:28.431 [pool-2-thread-2] 
```

**Comment by fcorneli** [comment]
Yep... see also my comment on https://github.com/web3j/web3j/pull/245

**Comment by 4ntoine** [comment]
Thanks for the link, i think that's exactly it.

**Comment by AlexandrouR** [comment]
Is this still an issue after the PR merge ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
