### ISSUE TITLE
executeTransaction is using explicit string match on status check

### ISSUE THREAD

**Issue by perlboy** [web3j/web3j#481]
Hi there,

On or around line 259 the following code is executed:
```
        if (!SUCCESSFUL_TRANSACTION_STATUS.equals(receipt.getStatus())) {
```
This constant is set to a final String of "0x1".

Ganache +/- CLI returns a Transaction status of 0x01. While this is equivalent in hex since this evaluation is a String it results in the following:
```
org.web3j.protocol.exceptions.TransactionException: Transaction has failed with status: 0x01. Gas used: 310277. (not-enough gas?)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:259)
	at org.web3j.tx.Contract.create(Contract.java:295)
	at org.web3j.tx.Contract.deploy(Contract.java:324)
	at org.web3j.tx.Contract.lambda$deployRemoteCall$5(Contract.java:362)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
```
I suggest TRANSACTION_STATUS comparison is conducted as a parsed hex match rather than explicit string.

**Comment by AlexandrouR** [comment]
This issue was fixed
