### ISSUE TITLE
Subscription throwing error

### ISSUE THREAD

**Issue by thotheolh** [web3j/web3j#556]
I am using the following code to listen into block events via subscription and hitting an exception:

```
private Web3j web3 = null;
private Subscription subscription = null;

web3 = EthereumWeb3JInterface.getInstance().getWeb3J();
subscription = web3.blockObservable(true).subscribe(
    block -> {
                Block b = block.getBlock();
                System.out.println("Found block #: " + b.getNumber() + " [" + b.getNumberRaw() + "]");
              }
);
```

This is simply a modification of the example shown in [https://docs.web3j.io/filters.html](https://docs.web3j.io/filters.html) to test out the Subscription and filtering functions.

The error it throws is:

```
rx.exceptions.OnErrorNotImplementedException: Invalid response received: okhttp3.internal.http.RealResponseBody@9203af4
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.Observable.unsafeSubscribe(Observable.java:10149)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.Observable.subscribe(Observable.java:10010)
```

**Comment by haldhar** [comment]
Hi thotheolh,

please use below code and check it will give result like  : Found block #: 4153 [0x1039].make sure mining process should be in progress.
Web3j web3j = Web3j.build(new HttpService("http://localhost:22000"));
Subscription subscription = null;
subscription = web3j.blockObservable(true).subscribe(
        block -> {
            EthBlock.Block b = block.getBlock();
            System.out.println("Found block #: " + b.getNumber() + " [" + b.getNumberRaw() + "]");
        }
);

**Comment by AlexandrouR** [comment]
Is this still an issue ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
