### ISSUE TITLE
WalletUtils.generateLightNewWalletFile OOM on Android

### ISSUE THREAD

**Issue by myeveryheart** [web3j/web3j#564]
version: 'org.web3j:core:3.3.1-android'

java.lang.OutOfMemoryError: Failed to allocate a 1036 byte allocation with 4194304 free bytes and 5MB until OOM; failed due to fragmentation (required continguous free 131072 bytes for a new buffer where largest contiguous free 16384 bytes)
        at org.spongycastle.util.Arrays.clone(Arrays.java:602)
        at org.spongycastle.crypto.generators.SCrypt.SMix(SCrypt.java:126)
        at org.spongycastle.crypto.generators.SCrypt.MFcrypt(SCrypt.java:87)
        at org.spongycastle.crypto.generators.SCrypt.generate(SCrypt.java:66)

**Comment by lhalcyon** [comment]
see https://lhalcyon.com/blockchain-eth-unlock-android/
