### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by pencilso** [web3j/web3j#578]
Credentials credentials = loadCredentials(privateKey);
 RemoteCall<DappTest_sol_Ballot> deploy = DappTest_sol_Ballot.deploy(web3j, credentials,BigInteger.valueOf(10), BigInteger.valueOf(300000));
DappTest_sol_Ballot send = deploy.send();

// this is error
deploy.send();

//Error Info
java.lang.RuntimeException: org.web3j.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
	at org.web3j.tx.Contract.deploy(Contract.java:350)
	at org.web3j.tx.Contract.lambda$deployRemoteCall$5(Contract.java:384)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)

**Comment by pencilso** [comment]
Caused by: org.web3j.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
	at org.web3j.utils.Numeric.decodeQuantity(Numeric.java:32)
	at org.web3j.protocol.core.methods.response.TransactionReceipt.isStatusOK(TransactionReceipt.java:143)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:279)
	at org.web3j.tx.Contract.create(Contract.java:317)
	at org.web3j.tx.Contract.deploy(Contract.java:346)

**Comment by pencilso** [comment]
Seek help

**Comment by haldhar** [comment]
Hi pencilso,

you can you below code to deploy your contract.
Web3j web3j = Web3j.build(new HttpService("http://localhost:22000"));
 Credentials credentials = Credentials.create("0x7ca02fe4a8c5f81784805d908f3b0a81a1bd1c79");
DappTest_sol_Ballot dappTest_sol_Ballot = DappTest_sol_Ballot.deploy(web3j,credentials,Contract.GAS_PRICE,Contract.GAS_LIMIT).send();
System.out.println("HALDHAR SETH GET CONTRACT ADDRESS"+set.getContractAddress());
