### ISSUE TITLE
ERROR with infura & web3j on Android 4.x : javax.net.ssl.SSLException: Connection closed by peer

### ISSUE THREAD

**Issue by zoeleesss** [web3j/web3j#583]
My Java code:

```java
     * @return BigInteger
     */

    public static BigInteger getTotalSupply(){
        try {
            BigInteger totalSupply = fishCore.totalSupply().send();
            return totalSupply;
        }
        catch (Exception e){
            System.err.println(" error in getTotalSupply ");
            e.printStackTrace();
            return null;
        }
    }

```

Error Info:

``` java
Caused by: javax.net.ssl.SSLException: Connection closed by peer
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at okhttp3.RealCall.execute(RealCall.java:69)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at org.web3j.protocol.http.HttpService.performIO(HttpService.java:110)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at org.web3j.protocol.Service.send(Service.java:32)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at org.web3j.protocol.Service$1.call(Service.java:46)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at org.web3j.protocol.Service$1.call(Service.java:43)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-07 18:11:46.162 2239-2239/com.cyrptokindom.fish.fishdapp W/System.err:     at java.lang.Thread.run(Thread.java:841)

```

I am using Android 4.4.2 and 4.3 devices, and there are errors of
`javax.net.ssl.SSLException: Connection closed by peer`

I googled this, somone says https (TLS) via okhttp is not supported on Android 4.x devices. And can be solved with some extra codes. 
The solution can be found here: [javax-net-ssl-sslexception-connection-closed-by-peer-on-4-4-2-device-works-on](https://stackoverflow.com/questions/36888852/javax-net-ssl-sslexception-connection-closed-by-peer-on-4-4-2-device-works-on)

Can you guys solve that problem?  
Thanks very much !!

**Comment by zoeleesss** [comment]
I tried the same code on Android 7.0 and it does not work. 
But when i alerted the code to sendAsync instead of send:
```java

...
            BigInteger totalSupply = fishCore.totalSupply().sendAsync().get();
         
...

```
It works on Android 7.0 but does not work on Android 4.x 
(same error as i mentioned `javax.net.ssl.SSLException: Connection closed by peer `)

Anyone knows why we can't use synchronized method , `send()`  on Android ?

**Comment by Norphy** [comment]
Hello, I have been getting the same exact error for about a week ago on Android 4.x but exactly the same code was working about 2-3 weeks ago without changing any of the code on also the same device Android 4.x. Has anything changed within the past 2-3 weeks.

**Comment by zoeleesss** [comment]
Hey @Norphy 

I haven't tried the solution i linked. But when i use Android 6.0+ devices , and it works perfectly.

Hope it helps.

**Comment by Norphy** [comment]
Thank you @zoeleesss for the reply, I haven't tried that solution either but also I tried on an API 24 android device and the issue is not present as well. 
Thank you.

**Comment by AlexandrouR** [comment]
Hey is this still an issue with the latest version of web3j ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
