### ISSUE TITLE
Error: "Could not construct a recoverable key. This should never happen."

### ISSUE THREAD

**Issue by psylinse** [web3j/web3j#622]
Hello, thanks for the library, it's been working great so far!

I ran into one issue with a specific contract's function via a generated web3j contract interface. Whenever I try to invoke this specific function (`bulkMint`) it throws:
```
java.lang.RuntimeException: Could not construct a recoverable key. This should never happen.
	at org.web3j.crypto.Sign.signMessage(Sign.java:63) ~[crypto-3.4.0.jar:na]
	at org.web3j.crypto.Sign.signMessage(Sign.java:40) ~[crypto-3.4.0.jar:na]
	at org.web3j.crypto.TransactionEncoder.signMessage(TransactionEncoder.java:21) ~[crypto-3.4.0.jar:na]
	at org.web3j.tx.RawTransactionManager.signAndSend(RawTransactionManager.java:102) ~[core-3.4.0.jar:na]
	at org.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:91) ~[core-3.4.0.jar:na]
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:49) ~[core-3.4.0.jar:na]
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:87) ~[core-3.4.0.jar:na]
	at org.web3j.tx.Contract.executeTransaction(Contract.java:275) ~[core-3.4.0.jar:na]
	at org.web3j.tx.Contract.executeTransaction(Contract.java:259) ~[core-3.4.0.jar:na]
	at org.web3j.tx.Contract.executeTransaction(Contract.java:253) ~[core-3.4.0.jar:na]
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:305) ~[core-3.4.0.jar:na]
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30) ~[core-3.4.0.jar:na]
```

The contract's function looks like this:
```
function bulkMint(address[] _addresses, uint256[] _tokenIds) public onlyOwner
```

The kotlin code I'm using is:
```
val credentials = Credentials.create("0x26233cc7a13c19a3a970b924f7b5e7dc940f3b15", PRIVATE_KEY)
val smartContract = LyraCollectibleTemplateV0.load("0x7e17f9d1ed4c73891708bdaa032ade3cade17ff8", web3, credentials, BigInteger.valueOf(1), BigInteger.valueOf(210000))
val result = smartContract.bulkMint(listOf("0x698fd98d722bc425C4381bD6FD4df221b4117032"), listOf(BigInteger.valueOf(3))).send()
println(result) // never gets here
// throws "Could not construct a recoverable key. This should never happen"
```

Interestingly, I can call other functions on this same contract just fine:
```
val credentials = Credentials.create("0x26233cc7a13c19a3a970b924f7b5e7dc940f3b15", "e40ae2b1581b046853ac51b4b1320eb0ccbb937a82d4f0daa410805ee9423508")
val smartContract = LyraCollectibleTemplateV0.load("0x7e17f9d1ed4c73891708bdaa032ade3cade17ff8", web3, credentials, BigInteger.valueOf(1), BigInteger.valueOf(210000))
val result = smartContract.balanceOf("0x26233cc7a13c19a3a970b924f7b5e7dc940f3b15").send()
println(result)
// 4
```
This is using an `infura` node on the `kovan` network. Any ideas?

* ERC721 token on kovan: https://kovan.etherscan.io/token/0x7e17f9d1ed4c73891708bdaa032ade3cade17ff8
* Truffle generated abi: https://gist.github.com/psylinse/1bf06fd5b465a8ea9a99a4729320c477
* Truffle generated bin: bytecode is null (not sure why)
* Web3j generated java file: https://gist.github.com/psylinse/fd9f899ef494d21f49551c4c0748b06f

**Comment by psylinse** [comment]
I figured this out, it was my fault. I am creating my `Credentials` incorrectly (`publicKey` and `privateKey` parameters are swapped). I fixed this and it works. I'll add a PR that might help someone figure this out faster since a message that says `This should never happen` makes me think it's not something I did wrong. If that's not useful, go ahead and close this!

Thanks!

**Comment by psylinse** [comment]
Thanks!
