### ISSUE TITLE
Crashes with NPE if having no peers

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#627]
Running geth 1.8.10 with `light` sync on docker on **testnet**:
```
 -rpc --ipcdisable --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcvhosts=* --syncmode "light"  --rpcapi="db,personal,eth,net,web3,admin" --cache=${CACHE_SIZE:-512} --testnet
```

```
my-app | 12:57:45.585 [main] DEBUG EthereumProcessorImpl$Builder - Loading contract from address 0xb63550b69a502d579e5406e59f5e7b4079810b44 ...
my-app | 12:57:45.678 [main] DEBUG EthereumProcessorImpl$Builder - Loaded contract from 0xb63550b69a502d579e5406e59f5e7b4079810b44
my-app | 12:57:45.693 [main] WARN  Backend - No saved last processed eth block value
my-app | 12:57:45.708 [main] DEBUG Engine - 0 pending tasks loaded from the storage
my-app | 12:57:45.857 [main] DEBUG HttpLoggingInterceptor - --> POST http://ethereum:8545/ http/1.1
my-app | 12:57:45.858 [main] DEBUG HttpLoggingInterceptor - Content-Type: application/json; charset=utf-8
my-app | 12:57:45.858 [main] DEBUG HttpLoggingInterceptor - Content-Length: 241
my-app | 12:57:45.860 [main] DEBUG HttpLoggingInterceptor - 
my-app | 12:57:45.861 [main] DEBUG HttpLoggingInterceptor - {"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":["0xad3951f0f00299510ad490be94b4454a1c51e978bf9e1c3e0c166b5cb4c21afd"],"fromBlock":"earliest","toBlock":"latest","address":["0xb63550b69a502d579e5406e59f5e7b4079810b44"]}],"id":0}
my-app | 12:57:45.862 [main] DEBUG HttpLoggingInterceptor - --> END POST (241-byte body)
my-app | 12:57:45.900 [main] DEBUG HttpLoggingInterceptor - <-- 200 OK http://ethereum:8545/ (37ms)
my-app | 12:57:45.901 [main] DEBUG HttpLoggingInterceptor - Content-Type: application/json
my-app | 12:57:45.901 [main] DEBUG HttpLoggingInterceptor - Vary: Origin
my-app | 12:57:45.901 [main] DEBUG HttpLoggingInterceptor - Date: Wed, 11 Jul 2018 12:57:45 GMT
my-app | 12:57:45.903 [main] DEBUG HttpLoggingInterceptor - Content-Length: 71
my-app | 12:57:45.904 [main] DEBUG HttpLoggingInterceptor - 
my-app | 12:57:45.905 [main] DEBUG HttpLoggingInterceptor - {"jsonrpc":"2.0","id":0,"result":"0xf65629622cb03efb3a5abe2f6ee96176"}
my-app | 
my-app | 12:57:45.905 [main] DEBUG HttpLoggingInterceptor - <-- END HTTP (71-byte body)
my-app | 12:57:45.930 [main] DEBUG HttpLoggingInterceptor - --> POST http://ethereum:8545/ http/1.1
my-app | 12:57:45.930 [main] DEBUG HttpLoggingInterceptor - Content-Type: application/json; charset=utf-8
my-app | 12:57:45.931 [main] DEBUG HttpLoggingInterceptor - Content-Length: 101
my-app | 12:57:45.931 [main] DEBUG HttpLoggingInterceptor - 
my-app | 12:57:45.932 [main] DEBUG HttpLoggingInterceptor - {"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0xf65629622cb03efb3a5abe2f6ee96176"],"id":1}
my-app | 12:57:45.932 [main] DEBUG HttpLoggingInterceptor - --> END POST (101-byte body)
my-app | 12:57:47.060 [main] DEBUG HttpLoggingInterceptor - <-- 200 OK http://ethereum:8545/ (1128ms)
my-app | 12:57:47.061 [main] DEBUG HttpLoggingInterceptor - Content-Type: application/json
my-app | 12:57:47.061 [main] DEBUG HttpLoggingInterceptor - Vary: Origin
my-app | 12:57:47.062 [main] DEBUG HttpLoggingInterceptor - Date: Wed, 11 Jul 2018 12:57:47 GMT
my-app | 12:57:47.063 [main] DEBUG HttpLoggingInterceptor - Content-Length: 89
my-app | 12:57:47.064 [main] DEBUG HttpLoggingInterceptor - 
my-app | 12:57:47.064 [main] DEBUG HttpLoggingInterceptor - {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"no suitable peers available"}}
my-app | 
my-app | 12:57:47.064 [main] DEBUG HttpLoggingInterceptor - <-- END HTTP (89-byte body)
my-app | Exception in thread "main" rx.exceptions.OnErrorNotImplementedException
my-app | 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
my-app | 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
my-app | 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
my-app | 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
my-app | 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
my-app | 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
my-app | 	at rx.Observable.unsafeSubscribe(Observable.java:10149)
my-app | 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
my-app | 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
my-app | 	at rx.Observable.subscribe(Observable.java:10238)
my-app | 	at rx.Observable.subscribe(Observable.java:10205)
my-app | 	at rx.Observable.subscribe(Observable.java:10010)
 ...
my-app | 	at com.company.project.ethereum.EthereumProcessorImpl.subscribe(EthereumProcessorImpl.java:347)
my-app | 	at com.company.project.ethereum.EthereumProcessorImpl.start(EthereumProcessorImpl.java:334)
my-app | 	at com.company.project.Backend.initEthereum(Backend.java:661)
my-app | 	at com.company.project.Backend.doStart(Backend.java:721)
my-app | 	at com.company.project.Backend.start(Backend.java:398)
my-app | 	at com.company.project.BackendApp.main(BackendApp.java:240)
my-app | Caused by: java.lang.NullPointerException
my-app | 	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:36)
my-app | 	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:98)
my-app | 	at org.web3j.protocol.core.filters.Filter.run(Filter.java:53)
my-app | 	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:73)
my-app | 	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogObservable$2(JsonRpc2_0Rx.java:65)
my-app | 	at rx.Observable.unsafeSubscribe(Observable.java:10142)
my-app | 	... 11 more
my-app exited with code 1
```

web3j 3.4.0, generated smart contract wrapper with web3j-maven-plugin 0.3.1

**Comment by 4ntoine** [comment]
It can happen in literally any request:

```
my-app | 22:39:14.740 [main] DEBUG HttpLoggingInterceptor - --> POST http://ethereum:8545/ http/1.1
my-app | 22:39:14.740 [main] DEBUG HttpLoggingInterceptor - Content-Type: application/json; charset=utf-8
my-app | 22:39:14.740 [main] DEBUG HttpLoggingInterceptor - Content-Length: 127
my-app | 22:39:14.740 [main] DEBUG HttpLoggingInterceptor - 
my-app | 22:39:14.740 [main] DEBUG HttpLoggingInterceptor - {"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0x2fe90fe5e4f90cc07c00512888a4ced120154c64","pending"],"id":103}
my-app | 22:39:14.741 [main] DEBUG HttpLoggingInterceptor - --> END POST (127-byte body)
my-app | 22:39:14.754 [main] DEBUG HttpLoggingInterceptor - <-- 200 OK http://ethereum:8545/ (12ms)
my-app | 22:39:14.754 [main] DEBUG HttpLoggingInterceptor - Content-Type: application/json
my-app | 22:39:14.754 [main] DEBUG HttpLoggingInterceptor - Vary: Origin
my-app | 22:39:14.754 [main] DEBUG HttpLoggingInterceptor - Date: Wed, 11 Jul 2018 22:39:14 GMT
my-app | 22:39:14.754 [main] DEBUG HttpLoggingInterceptor - Content-Length: 91
my-app | 22:39:14.754 [main] DEBUG HttpLoggingInterceptor - 
my-app | 22:39:14.754 [main] DEBUG HttpLoggingInterceptor - {"jsonrpc":"2.0","id":103,"error":{"code":-32000,"message":"no suitable peers available"}}
my-app | 
my-app | 22:39:14.755 [main] DEBUG HttpLoggingInterceptor - <-- END HTTP (91-byte body)
my-app | Exception in thread "main" org.web3j.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
my-app | 	at org.web3j.utils.Numeric.decodeQuantity(Numeric.java:32)
my-app | 	at org.web3j.protocol.core.methods.response.EthGetTransactionCount.getTransactionCount(EthGetTransactionCount.java:13)
my-app | 	at org.web3j.tx.RawTransactionManager.getNonce(RawTransactionManager.java:73)
my-app | 	at org.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:81)
my-app | 	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:49)
my-app | 	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:87)
my-app | 	at org.web3j.tx.Contract.executeTransaction(Contract.java:275)
my-app | 	at org.web3j.tx.Contract.executeTransaction(Contract.java:259)
my-app | 	at org.web3j.tx.Contract.executeTransaction(Contract.java:253)
my-app | 	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:305)
my-app | 	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
my-app | 	at com.company.project.ethereum.EthereumProcessorImpl.send(EthereumProcessorImpl.java:61)
my-app | 	at com.company.project.ethereum.EthereumProcessorImpl.setServiceFee(EthereumProcessorImpl.java:323)
my-app | 	at com.company.project.service.system.SystemService.setServiceFee(SystemService.java:137)
my-app | 	at com.company.project.Backend.checkAndSetServiceFee(Backend.java:738)
my-app | 	at com.company.project.Backend.doStart(Backend.java:723)
my-app | 	at com.company.project.Backend.start(Backend.java:398)
my-app | 	at com.company.project.BackendApp.main(BackendApp.java:240)
```

**Comment by AlexandrouR** [comment]
Is this still an issue ?
