### ISSUE TITLE
getNonce returning null after write operation

### ISSUE THREAD

**Issue by Thotol** [web3j/web3j#654]
Hello everyone;
I'm getting a strange result when trying to write on the blockchain using my contract wrapper (in Java Spring Boot API):

```
[dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
        at org.web3j.tx.RawTransactionManager.getNonce(RawTransactionManager.java:75) ~[core-3.5.0.jar:na]
        at org.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:94) ~[core-3.5.0.jar:na]
        at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:49) ~[core-3.5.0.jar:na]
        at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:87) ~[core-3.5.0.jar:na]
        at org.web3j.tx.Contract.executeTransaction(Contract.java:275) ~[core-3.5.0.jar:na]
        at org.web3j.tx.Contract.executeTransaction(Contract.java:259) ~[core-3.5.0.jar:na]
        at org.web3j.tx.Contract.executeTransaction(Contract.java:253) ~[core-3.5.0.jar:na]
        at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:305) ~[core-3.5.0.jar:na]
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30) ~[core-3.5.0.jar:na]
```

Does anyone had the same issue and managed to fix it ?

**Comment by Thotol** [comment]
Ok, the issue is due to total negligence.
I had two contract wrapper constructor, one worked perfectly, but I forgot to initiatlize the web3j object in the other, hence the really strange error of only half my requests working.
