### ISSUE TITLE
[Android]How to set the proguard-rules?

### ISSUE THREAD

**Issue by monkey1992** [web3j/web3j#675]
If I make minifyEnable true, the crash happened:
15:28:11.451 10619-10785/? E/CrashHandler: In thread: Thread[ForkJoinPool.commonPool-worker-1,5,main]
    UncaughtException detected: java.lang.NoSuchFieldError: No static field PUBLIC_ONLY of type Lcom/fasterxml/jackson/a/e$a; in class Lcom/fasterxml/jackson/a/e$a; or its superclasses (declaration of 'com.fasterxml.jackson.a.e$a' appears in /data/app/com.finogeeks.finochatapp-1/base.apk)
        at java.lang.Class.getDeclaredAnnotation(Native Method)
        at java.lang.Class.getAnnotation(Class.java:2352)
        at com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.<clinit>(Unknown Source)
        at com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.defaultInstance(Unknown Source)
        at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(Unknown Source)
        at org.web3j.b.n.<clinit>(Unknown Source)
        at org.web3j.b.n.a(Unknown Source)
        at com.finogeeks.finowallet.e.a.a(Unknown Source)
        at com.finogeeks.finowallet.e.a.a(Unknown Source)
        at com.finogeeks.finowallet.e.a$d.doResume(Unknown Source)
        at e.d.a.b.a.a.resumeWithException(Unknown Source)
        at e.d.a.b.a.a.resumeWithException(Unknown Source)
        at f.a.a.ae.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1383)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:256)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1123)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1961)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1909)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:128)

I have already configured the proguard rules:
-dontwarn com.fasterxml.jackson.databind.**
-keep class com.fasterxml.jackson.core.** {*;}
-keep interface com.fasterxml.jackson.core { *; }
-keep public class * extends com.fasterxml.jackson.core.**
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.<clinit>
-keep class com.fasterxml.jackson.databind.ObjectMapper.<clinit>
-keep class com.fasterxml.jackson.databind.** {*;}
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker$*{*;}
-keep interface com.fasterxml.jackson.databind { *; }
-keep public class * extends com.fasterxml.jackson.databind.**
But the problem still exists! Please help me, Thanks!

**Comment by monkey1992** [comment]
The problem was solved, The proguard rules:

-dontwarn com.fasterxml.jackson.databind.**
-keep class org.** {*;}
-keep class com.fasterxml.jackson.core.** {*;}
-keep interface com.fasterxml.jackson.core { *; }
-keep public class * extends com.fasterxml.jackson.core.**
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.<clinit>
-keep class com.fasterxml.jackson.databind.ObjectMapper.<clinit>
-keep class com.fasterxml.jackson.databind.** {*;}
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker$*{*;}
-keep interface com.fasterxml.jackson.databind { *; }
-keep public class * extends com.fasterxml.jackson.databind.**
-keep class com.fasterxml.jackson.annotation.** {*;}
-keep interface com.fasterxml.jackson.annotation.** {*;}

**Comment by fy5220** [comment]
@monkey1992 thanks

**Comment by tentenponce** [comment]
this `{;}` gives an error, instead it should be: `{*;}`

```
-dontwarn com.fasterxml.jackson.databind.**
-keep class org.** { *; }
-keep class com.fasterxml.jackson.core.** { *; }
-keep interface com.fasterxml.jackson.core { *; }
-keep public class * extends com.fasterxml.jackson.core.*
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.
-keep class com.fasterxml.jackson.databind.ObjectMapper.
-keep class com.fasterxml.jackson.databind.** { *; }
-keep class com.fasterxml.jackson.databind.introspect.VisibilityChecker${ *; }
-keep interface com.fasterxml.jackson.databind { *; }
-keep public class * extends com.fasterxml.jackson.databind.*
-keep class com.fasterxml.jackson.annotation.** { *; }
-keep interface com.fasterxml.jackson.annotation.** { *; }
```

**Comment by tentenponce** [comment]
I've clean it up a bit, it works and it produces much small apk:

```
-dontwarn com.fasterxml.jackson.databind.**
-keep class com.fasterxml.jackson.core.** { *; }
-keep interface com.fasterxml.jackson.core { *; }
-keep class com.fasterxml.jackson.databind.** { *; }
-keep interface com.fasterxml.jackson.databind { *; }
-keep class com.fasterxml.jackson.annotation.** { *; }
-keep interface com.fasterxml.jackson.annotation.** { *; }
```
