### ISSUE TITLE
Error deploying contracts using contract wrapper in version 3.5

### ISSUE THREAD

**Issue by Himanshu-Pandey** [web3j/web3j#676]
When using Contract wrapper's deploy method I am getting `java.lang.NoSuchMethodException` exception.

Stack trace : 
    java.lang.NoSuchMethodException: dynamic.contracts.contracts.Cargo.<init>(java.lang.String, org.web3j.protocol.Web3j, org.web3j.tx.TransactionManager, org.web3j.tx.gas.ContractGasProvider)
	at java.base/java.lang.Class.getConstructor0(Class.java:3302) ~[na:na]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2512) ~[na:na]
	at org.web3j.tx.Contract.deploy(Contract.java:362) ~[core-3.5.0.jar:na]
	at org.web3j.tx.Contract.lambda$deployRemoteCall$6(Contract.java:404) ~[core-3.5.0.jar:na]
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30) ~[core-3.5.0.jar:na]
	at dynamic.contracts.service.CargoService.deployCargoContract(CargoService.java:50) ~[classes/:na]

**It is working fine in web3j 3.4**

**Comment by iikirilov** [comment]
Please us web3j 3.6.0 or greater
