### ISSUE TITLE
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by monkey1992** [web3j/web3j#687]
On my Android 4.4 device，the IllegalAccessError occurred:
```
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
        at java.lang.reflect.Method.getDeclaredAnnotations(Native Method)
        at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:258)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._constructMethod(AnnotatedClass.java:883)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._addMemberMethods(AnnotatedClass.java:729)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveMemberMethods(AnnotatedClass.java:534)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods(AnnotatedClass.java:322)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:510)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:302)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:172)
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:224)
        at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:350)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:219)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:168)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1308)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1258)
        at com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:653)
        at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:64)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:874)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:682)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2997)
        at org.web3j.crypto.WalletUtils.generateWalletFile(WalletUtils.java:72)
        at org.web3j.crypto.WalletUtils.generateNewWalletFile(WalletUtils.java:55)
```
I searched some solutions, Some people said that it was caused by repeated additions of dependencies, but I did not add dependencies repeatedly, so I want to know what the reason is, please help me, Thanks!

**Comment by iikirilov** [comment]
@monkey1992 is this still an issue?

**Comment by monkey1992** [comment]
> @monkey1992 is this still an issue?

No, I have solved the issue by adding a multidex-config file in my application just like this:
```
-keep class org.web3j.crypto.WalletFile{*;}
-keep class org.web3j.tx.Contract{*;}
```
The cause of the problem is that I added some codes in the build.gradle of the application to solved the multidex problem:
```
    dexOptions {
        preDexLibraries = false
        keepRuntimeAnnotatedClasses false
    }
```
So some annotations in web3j were packed outside of the main.dex file during the compilation phase, but these annotations should be kept in the main.dex file, otherwise this problem will occur.
