### ISSUE TITLE
rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: org.web3j.protocol.core.methods.response.EthLog$LogObject.class

### ISSUE THREAD

**Issue by helderribeirosousa** [web3j/web3j#712]
Hello,

Whenever i subscribe to my smart contract's events i get this exception:
```
java.lang.NullPointerException
	at my.package.smartcontracts.MySmartContract$55.call(MySmartContract.java:355)
	at my.package.smartcontracts.MySmartContract$55.call(MySmartContract.java:349)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:39)
	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:106)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:61)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:73)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogObservable$2(JsonRpc2_0Rx.java:65)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeDetach.call(OnSubscribeDetach.java:45)
	at rx.internal.operators.OnSubscribeDetach.call(OnSubscribeDetach.java:29)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.Observable.subscribe(Observable.java:10045)
	at my.package.MyDapp.run(MyDapp.java:114)
	at pt.ipp.estg.mei.MyDapp.main(MyDapp.java:30)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: org.web3j.protocol.core.methods.response.EthLog$LogObject.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 16 more
```

I'm running web3j 3.5.0 (both the library and the command-line utility) and connecting to a Rinkeby (Archive mode) node.
Everything else works flawlessy except operations involving event logging.
I'm chasing the cause of this behaviour for the last 15 days and i've ran out of ideas.

Here's the code i'm executing:

```
        String nodeUrl = "MY_NODE";
	OkHttpClient.Builder builder = new OkHttpClient.Builder();
	Long tos = 300L;
	builder.connectTimeout(tos, TimeUnit.SECONDS);
	builder.readTimeout(tos, TimeUnit.SECONDS);
	builder.writeTimeout(tos, TimeUnit.SECONDS);
	Web3j web3j = Web3j.build(new HttpService(nodeUrl,builder.build(),false));
	System.out.println("Connected to Ethereum client version: "+web3j.web3ClientVersion().send().getWeb3ClientVersion());

	Credentials credentials = WalletUtils.loadCredentials("WALLET_SECRET","/path/to/my/wallet.json");

	String smartContractAddress = "0x_MY_SMART_CONTRACT_ADDRESS";

	BigInteger LATEST_BLOCK = web3j.ethGetBlockByNumber(DefaultBlockParameterName.LATEST,true).send().getBlock().getNumber();
	EthFilter filter = new EthFilter(DefaultBlockParameterName.EARLIEST,DefaultBlockParameterName.LATEST,smartContractAddress);
		    
	Subscription sub = contract.myEventEventObservable(filter).onTerminateDetach().subscribe(x -> {
		System.out.println(x.message);
	}, Throwable::printStackTrace);
```

Is this by any chance a known issue?

**Comment by iikirilov** [comment]
Please try with web3j 3.6.0

**Comment by iikirilov** [comment]
You can also try with web3j 4.0.0-alpha-1 which is using Rx2 Flowable API

**Comment by helderribeirosousa** [comment]
Will try it during the next week. I'll leave feedback once i do.

**Comment by helderribeirosousa** [comment]
Installed Web3j 3.6.0, created new smart contract wraps and it's working now with 3.6.0. Thank you!
