### ISSUE TITLE
Create walletFile report errors-->java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by maxiao124** [web3j/web3j#759]
when I use
```
File destDir = new File("D:/Develop/blockchain/Geth/tmpPrivate/keystore");
String generateWalletFile = WalletUtils.generateNewWalletFile("123", destDir, true);
```
to create a walletFile，the console error reporting
```
java.lang.OutOfMemoryError: Java heap space
	at org.bouncycastle.util.Arrays.clone(Unknown Source)
	at org.bouncycastle.crypto.generators.SCrypt.SMix(Unknown Source)
	at org.bouncycastle.crypto.generators.SCrypt.MFcrypt(Unknown Source)
	at org.bouncycastle.crypto.generators.SCrypt.generate(Unknown Source)
	at org.web3j.crypto.Wallet.generateDerivedScryptKey(Wallet.java:132)
	at org.web3j.crypto.Wallet.create(Wallet.java:70)
	at org.web3j.crypto.Wallet.createStandard(Wallet.java:89)
	at org.web3j.crypto.WalletUtils.generateWalletFile(WalletUtils.java:65)
	at org.web3j.crypto.WalletUtils.generateNewWalletFile(WalletUtils.java:56)
	at com.huagu.coa.wallet.ETHUtils.getNewAddress(ETHUtils.java:98)
	at com.huagu.coa.wallet.UtilsTest.main(UtilsTest.java:29)
```
what happened，and how to fix it.

**Comment by snazha-blkio** [comment]
@maxiao124 , can you please provide more information? 
What version of web3j are you using? Environment/setup?

**Comment by maxiao124** [comment]
ok；web3j version--->3.3.1、geth version--->1.8.15-stable、jdk version--->1.8.0_181，and I use eclipse，Do you have any other information you need to know? @snazha-blkio

**Comment by snazha-blkio** [comment]
Hi @maxiao124 ,

I have tried to reproduce your issue with the versions as you specified, I was unable to produce an OOM error.
There may be other aspects of your program that are consuming significant resources, and it just so happens that a call to this function tips the scale and results in an OOM error.

I would suggest increasing the memory parameters to your JVM, perhaps??

**Comment by maxiao124** [comment]
ok，I'll try，thank you so much.

**Comment by chenzhijun45** [comment]
@maxiao124 I had the same problem.
How did you solve it?
