### ISSUE TITLE
ethSendTransaction via Parity to an Ethereum Harmony Client Can't Deserialize Response

### ISSUE THREAD

**Issue by BHSDuncan** [web3j/web3j#76]
(Note: If there is another location I should put this, or if I'm doing something really stupid, please let me know.)

Whenever I make a call to "ethSendTransction" (sync call), I get the following:

`com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: org.apache.http.conn.EofSensorInputStream@144440f5; line: 1, column: 93] (through reference chain: org.web3j.protocol.core.methods.response.EthSendTransaction["error"]->org.web3j.protocol.core.Response$Error["data"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:60)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
	at org.web3j.protocol.http.HttpService.lambda$getResponseHandler$16(HttpService.java:85)
	at org.web3j.protocol.http.HttpService$$Lambda$7/257495665.handleResponse(Unknown Source)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at org.web3j.protocol.http.HttpService.send(HttpService.java:63)
	at org.web3j.protocol.core.Request.send(Request.java:71)
	at com.foo.service.Web3jTest.testCreateWallet(Web3jTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
`

Now while I appreciate that I might be doing something wrong in my sequence of calls, I can't even view the error coming back.

Here's my calling code against a running Ethereum Harmony instance (note that the calls preceding the one in question all work just fine):

`    Parity parity = Parity.build(new HttpService("http://localhost:8080/"));
    NewAccountIdentifier newAccount = parity.personalNewAccount(this.PASSWORD).send();
    
    PersonalUnlockAccount unlockAccount = parity.personalUnlockAccount(newAccount.getAccountId(), this.PASSWORD).send();
    
    BigInteger value = Convert.toWei("7.5", Unit.ETHER).toBigInteger();
    
    EthGetTransactionCount ethGetTransactionCount = parity.ethGetTransactionCount(
        this.COINBASE, DefaultBlockParameterName.LATEST).send();

    BigInteger nonce = ethGetTransactionCount.getTransactionCount();
    
    Transaction transaction = Transaction.createEtherTransaction(this.COINBASE, nonce, this.GAS_PRICE, this.GAS_LIMIT, newAccount.getAccountId(), value);

    EthSendTransaction sendTx = parity.ethSendTransaction(transaction).send();
`

Any thoughts/comments welcome, and again, apologies if it's something fairly obvious (still finding my footing with Web3j and Harmony).

Thanks.

**Comment by BHSDuncan** [comment]
Dug a little deeper.  What it looks like is that the "data" field contains JSON information specific to an exception that likely isn't handled in Web3j, namely "com.ethercamp.harmony.util.exception.HarmonyException".  And so it's likely that the JSON deserializer doesn't have a known POJO in the Web3j project to target.

So it looks like that while calls can succeed from Web3j -> Harmony, it appears that errors/exceptions still have issues.

**Comment by BHSDuncan** [comment]
For now, I've written a new ErrorResolver for my Harmony client and plugged it in there. It avoids assigning the "data" field to anything but a string, and that seems to have resolved the issue (at least I get responses back now when there's a problem and I can parse said errors now).

Not sure if this is the way forward but I thought I'd let people know in case they run into something similar.

**Comment by conor10** [comment]
Are you able to provide the json messages being sent? See https://docs.web3j.io/trouble.html#i-want-to-see-details-of-the-json-rpc-requests-and-responses for how to do this.

**Comment by BHSDuncan** [comment]
The requests are easy enough to see. The responses are (were) the issue as it crashes on deserialization while still holding onto the input stream. 

Being on a Mac using localhost with neither Fiddler nor Charles providing any luck, I resorted to using Wireshark and confirmed the format of the response.

I've filed a PR with the Harmony project that should address this, hopefully in a manner that makes a bit of sense.  I confirmed that it boils down to what I found while digging deeper (above). Harmony's "data" field is, in fact, an object with two fields/keys: "exceptionTypeName" (I believe) and "message".

**Comment by conor10** [comment]
Fine, closing as addressed by https://github.com/ether-camp/ethereum-harmony/pull/36.

**Comment by YYwishp** [comment]
I have the same problem too

**Comment by YYwishp** [comment]
the error response:
{"id":7,"jsonrpc":"2.0","error":{"message":"sender doesn't have enough funds to send tx. The upfront cost is: 250000000000000 and the sender's account only has: 145000000000000","code":-32000,"data":{"stack":"Error: sender doesn't have enough funds to send tx. The upfront cost is: 250000000000000 and the sender's account only has: 145000000000000\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runTx.js:93:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3947:1\n at o (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1031:1)\n at f (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:998:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:966:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:4079:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:3:1\n at l (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:16:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:28:39\n at t.default (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/eachLimit.js:20:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/slice.js:3:1\n at g.n.emit (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async-eventemitter/lib/AsyncEventEmitter.js:58:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runTx.js:88:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3947:1\n at o (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1031:1)\n at f (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:998:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:966:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:4079:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runTx.js:85:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3947:1\n at o (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1031:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1032:1\n at Ae (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1038:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1049:10\n at ua (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3873:6)\n at Object.Ta [as series] (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:4849:1)\n at g.e.exports [as runTx] (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runTx.js:68:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runBlock.js:104:1\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3204:1\n at o (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1031:1)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1032:1\n at Ut (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3245:1)\n at Object. (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1049:10)\n at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/runBlock.js:84:1","name":"Error"}}}
