### ISSUE TITLE
GetTransactionCount EARLIEST block exception

### ISSUE THREAD

**Issue by AlexanderShniperson** [web3j/web3j#820]
Hello

Looks like there is a problem, when i do this
```
val web3 = Web3j.build(new HttpService("https://api.myetherwallet.com/eth"))
    val req = web3.ethGetTransactionCount(
      "0x2020fE9fA0f43fDe44360AAe03138C4B6AB35055",
      DefaultBlockParameterName.EARLIEST
    )
    val resp = req.send()
    println(s"Transactions ${resp.getTransactionCount}")
```
i receive  runtime exception
```
org.web3j.exceptions.MessageDecodingException: Value must be in format 0x[1-9]+[0-9]* or 0x0
	at org.web3j.utils.Numeric.decodeQuantity(Numeric.java:32)
	at org.web3j.protocol.core.methods.response.EthGetTransactionCount.getTransactionCount(EthGetTransactionCount.java:13)
```
used fresh version 3.4.0

**Comment by snazha-blkio** [comment]
Hi @AlexanderShniperson 

3.4.0 is an older release, could you please try with 4.0.3 and let us know if you still encounter this?

**Comment by snazha-blkio** [comment]
Closing - no user feedback.
