### ISSUE TITLE
WebsocketNotConnectedException causing RunTimeException

### ISSUE THREAD

**Issue by kagile** [web3j/web3j#843]
`WebsocketNotConnectedException` is causing app to crash forcefully. It would be nice to have listener rather than `RunTimeException`.

Library version : 4.1.0-android
StackTrace:
```
org.java_websocket.exceptions.WebsocketNotConnectedException
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:51)
        at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
        at io.reactivex.internal.disposables.SequentialDisposable.dispose(SequentialDisposable.java:72)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.cancel(FlowableCreate.java:301)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.cancel(FlowableFlatMap.java:353)
        at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.cancel(FlowableSubscribeOn.java:141)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.cancel(FlowableObserveOn.java:154)
        at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181)
        at io.reactivex.internal.subscribers.LambdaSubscriber.cancel(LambdaSubscriber.java:119)
        at io.reactivex.internal.subscribers.LambdaSubscriber.dispose(LambdaSubscriber.java:104)
        at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:235)
        at io.reactivex.disposables.CompositeDisposable.clear(CompositeDisposable.java:201)
        at com.example.old_code.smartcontractapp.controller.GameController.dispose(GameController.java:526)
        at com.example.old_code.smartcontractapp.activity.MainActivity.onDestroy(MainActivity.java:52)
        at android.app.Activity.performDestroy(Activity.java:6525)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4186)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226)
        at android.app.ActivityThread.access$1500(ActivityThread.java:177)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1503)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5951)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
     Caused by: org.java_websocket.exceptions.WebsocketNotConnectedException
        at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
        at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
        at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309)
        at org.web3j.protocol.websocket.WebSocketService.sendRequest(WebSocketService.java:164)
        at org.web3j.protocol.websocket.WebSocketService.sendAsync(WebSocketService.java:153)
        at org.web3j.protocol.websocket.WebSocketService.send(WebSocketService.java:131)
        at org.web3j.protocol.core.Request.send(Request.java:73)
        at org.web3j.protocol.core.filters.Filter.cancel(Filter.java:147)
        at org.web3j.protocol.rx.-$$Lambda$hQrQec4L_zeiM5rhfKCtEbuvzkI.cancel(lambda)
        at io.reactivex.internal.disposables.CancellableDisposable.dispose(CancellableDisposable.java:48)
        at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124) 
        at io.reactivex.internal.disposables.SequentialDisposable.dispose(SequentialDisposable.java:72) 
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.cancel(FlowableCreate.java:301) 
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.cancel(FlowableFlatMap.java:353) 
        at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181) 
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.cancel(FlowableSubscribeOn.java:141) 
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.cancel(FlowableObserveOn.java:154) 
        at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181) 
        at io.reactivex.internal.subscribers.LambdaSubscriber.cancel(LambdaSubscriber.java:119) 
        at io.reactivex.internal.subscribers.LambdaSubscriber.dispose(LambdaSubscriber.java:104) 
        at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:235) 
        at io.reactivex.disposables.CompositeDisposable.clear(CompositeDisposable.java:201) 
        at com.example.old_code.smartcontractapp.controller.GameController.dispose(GameController.java:526) 
        at com.example.old_code.smartcontractapp.activity.MainActivity.onDestroy(MainActivity.java:52) 
        at android.app.Activity.performDestroy(Activity.java:6525) 
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154) 
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4186) 
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:177) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1503) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:5951)
```

**Comment by snazha-blkio** [comment]
It is an unexpected exception so that's why it reverts to a RuntimeException.

What's stopping you from handling that alongside the IOException?

**Comment by AlexandrouR** [comment]
Closed due to inactivity.
