### ISSUE TITLE
Web3j compile contract json error

### ISSUE THREAD

**Issue by sywuestc** [web3j/web3j#882]
code Link: https://etherscan.io/address/0x66d9c4d19b4c8e23a54c6dc4ceed141f66b8111c#code

Generating com.gomo.ethchain.contract.FountainTokenUpgrade ... Exception in thread "main" java.lang.IllegalArgumentException: not a valid name:
        at com.squareup.javapoet.Util.checkArgument(Util.java:64)
        at com.squareup.javapoet.FieldSpec.builder(FieldSpec.java:92)
        at com.squareup.javapoet.TypeSpec$Builder.addField(TypeSpec.java:499)
        at org.web3j.codegen.SolidityFunctionWrapper.buildEventResponseObject(SolidityFunctionWrapper.java:854)
        at org.web3j.codegen.SolidityFunctionWrapper.buildEventFunctions(SolidityFunctionWrapper.java:999)
        at org.web3j.codegen.SolidityFunctionWrapper.buildFunctionDefinitions(SolidityFunctionWrapper.java:266)
        at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:137)
        at org.web3j.codegen.TruffleJsonFunctionWrapperGenerator.generate(TruffleJsonFunctionWrapperGenerator.java:134)
        at org.web3j.codegen.TruffleJsonFunctionWrapperGenerator.main(TruffleJsonFunctionWrapperGenerator.java:98)
        at org.web3j.codegen.TruffleJsonFunctionWrapperGenerator.run(TruffleJsonFunctionWrapperGenerator.java:62)
        at org.web3j.console.Runner.main(Runner.java:42)

**Comment by AlexandrouR** [comment]
Hey is this still an issue? if so please provide more information.

**Comment by iikirilov** [comment]
@AlexandrouR you can grab the json and and the bytecode from the link provided in the first post. You can try to generate the smart contract using web3j command line tools.

**Comment by AlexandrouR** [comment]
Using the instruction in the web3j documentation i generated the smart contract without any errors.

**Comment by AlexandrouR** [comment]
@sywuestc  Is this still an issue ?

**Comment by iikirilov** [comment]
@sywuestc we cannot reproduce your issue, could you please try with the latest version of web3j.
