### ISSUE TITLE
Common error "replacement transaction underpriced"

### ISSUE THREAD

**Issue by dgrmunch** [web3j/web3j#883]
Is there a way to avoid this recurrent error?

java.lang.RuntimeException: Error processing transaction request: replacement transaction underpriced
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:67)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:51)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:87)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:291)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:275)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:269)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:321)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)

**Comment by AlexandrouR** [comment]
It has to do with the amount of gas value when you submit a transaction. Take a look at this issue 
https://github.com/ethereum/go-ethereum/issues/15612

**Comment by AlexandrouR** [comment]
Usually this happens if you are trying to override a transaction that had a low gas price and it is taking too long to be mined. 

We can give you better advice if we had a steps to reproduce this.

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
