### ISSUE TITLE
Web3J Websocket Connection Closes

### ISSUE THREAD

**Issue by geekybcresearcher** [web3j/web3j#920]
While using Web3j websocket connection faced connection closed issue. After some time the connection was established and served few requests abruptly the connection closes.

Request you to share the way to reconnect WebSocket or any other better way to handle it.

Additionally, is it really required to explicitly invoke the connect() method of WebSocketService object?

> **Implementation**

    WebSocketService ws = new WebSocketService("http://localhost:7081", false);
    ws.connect();
    Admin web3Admin = web3Admin = Admin.build(ws);		

> **Logs**

    [ctReadThread-18] o.w.protocol.websocket.WebSocketClient   : Closed WebSocket connection to http://localhost:7082, because of reason: ''.Connection closed remotely: true
    
    org.java_websocket.exceptions.WebsocketNotConnectedException: null
    	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608) ~[Java-WebSocket-1.3.8.jar:na]
    	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585) ~[Java-WebSocket-1.3.8.jar:na]
    	at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309) ~[Java-WebSocket-1.3.8.jar:na]
    	at org.web3j.protocol.websocket.WebSocketService.sendRequest(WebSocketService.java:165) ~[core-4.1.1.jar:na]
    	at org.web3j.protocol.websocket.WebSocketService.sendAsync(WebSocketService.java:154) ~[core-4.1.1.jar:na]

**Comment by AlexandrouR** [comment]
I will need more information to reproduce mainly the type of network you are running.
Also a small observation in the implementation you connect to port 7081 but the exception is thrown on port 7082.

**Comment by AlexandrouR** [comment]
Related to #703  i am closing this issue as the conversation will be continued there.
