### ISSUE TITLE
Permit private networks to bypass ENS contract registry

### ISSUE THREAD

**Issue by 9607835** [web3j/web3j#930]
- expect: able to deploy contract to private network.
- results: web3j #95 assumes that a ENS contract is deployed on the network when it isn't and thus the library can not load previously created contracts.
- current fix: reverting to a previous version 

```
Caused by: org.web3j.ens.EnsResolutionException: Unable to resolve ENS registry contract for network id: 72
        at org.web3j.ens.Contracts.resolveRegistryContract(Contracts.java:23)
        at org.web3j.ens.EnsResolver.lookupResolver(EnsResolver.java:122)
        at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:58)
        ... 53 more
```
even changing to one of the three supported networks in `org/web3j/ens/Contracts.java` still does not work because then it tries to USE the ENS contract in `org/web3j/ens/EnsResolver.java:130`
`String resolverAddress = ensRegistry.resolver(nameHash).send();`
and since this is a private network NO ENS contract *exists* in the first place and so...
```
Caused by: org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract
        at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:250)
        at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:317)
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
        at org.web3j.ens.EnsResolver.lookupResolver(EnsResolver.java:130)
        at org.web3j.ens.EnsResolver.obtainPublicResolver(EnsResolver.java:58)
        ... 53 more
```

**Comment by 9607835** [comment]
wow, I'm glad I looked deeper at the source code, it detects hex contract addresses by character length, so if it is exactly 40 hex digits it bypasses ENS, I was rapidly testing deployment and so I changed the address to trigger an automatic deployment and apparently removed one digit by accident at some point.
