### ISSUE TITLE
personalNewAccount gives SocketTimeoutException when mining going on

### ISSUE THREAD

**Issue by adneerav** [web3j/web3j#937]
Hello,

I am facing one issue while creating new account using web3j android.

Its not allowing me to create new address in geth when mining is started.
To create new account below code I've used.
`val personalUnlockAccount = web3j.personalNewAccount(PASSWORD).send()`

By following above its allowing to create new personal account(address) successfully if mining is not going on.(miner.stop())

And it give error(SocketTimeoutException) if the mining is going on and trying to create new account(address).

For geth node initialization and rpc attach below are my configuration and command

`geth --rpc --networkid 3811 --datadir ./peer1 --rpc --rpcaddr 192.168.43.18 --rpcport "8000" --rpcapi "eth,net,web3,personal" --rpccorsdomain "*"`

`geth attach ipc:/home/USER/Ethereum/peer1/geth.ipc`

Note : for rpcapi parameter I've tried with different options too but same issue.
```
2019-05-24 17:17:15.267 4694-4723/com.evm W/System.err: java.net.SocketTimeoutException: timeout
2019-05-24 17:17:15.268 4694-4723/com.evm W/System.err:     at okio.Okio$4.newTimeoutException(Okio.java:232)
2019-05-24 17:17:15.269 4694-4723/com.evm W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
2019-05-24 17:17:15.269 4694-4723/com.evm W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
2019-05-24 17:17:15.269 4694-4723/com.evm W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
2019-05-24 17:17:15.269 4694-4723/com.evm W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
2019-05-24 17:17:15.270 4694-4723/com.evm W/System.err:     at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
2019-05-24 17:17:15.270 4694-4723/com.evm W/System.err:     at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
2019-05-24 17:17:15.270 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
2019-05-24 17:17:15.271 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-24 17:17:15.271 4694-4723/com.evm W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
2019-05-24 17:17:15.271 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-24 17:17:15.271 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-24 17:17:15.272 4694-4723/com.evm W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-05-24 17:17:15.272 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-24 17:17:15.272 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-24 17:17:15.273 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-05-24 17:17:15.273 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-24 17:17:15.273 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-05-24 17:17:15.273 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-24 17:17:15.274 4694-4723/com.evm W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-24 17:17:15.274 4694-4723/com.evm W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
2019-05-24 17:17:15.274 4694-4723/com.evm W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
2019-05-24 17:17:15.274 4694-4723/com.evm W/System.err:     at org.web3j.protocol.http.HttpService.performIO(HttpService.java:151)
2019-05-24 17:17:15.274 4694-4723/com.evm W/System.err:     at org.web3j.protocol.Service.send(Service.java:35)
2019-05-24 17:17:15.274 4694-4723/com.evm W/System.err:     at org.web3j.protocol.core.Request.send(Request.java:73)
```

Can anyone please help me on this.

Thanks

**Comment by UnexpectedCharacter** [comment]
Did you fix this issue?

**Comment by iikirilov** [comment]
@adneerav do you get any exceptions in the logs of geth?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
