### ISSUE TITLE
Transactions with >32kb of data

### ISSUE THREAD

**Issue by jefftellew** [web3j/web3j#964]
## Submitting transactions with more than 32 kb of data
I am trying to submit a transaction to a local chain that is running on geth where the transaction has over 32 kb of data. I have modified geth to allow this, but web3j is telling me that I have an invalid transaction whenever I try and submit one that exceeds 32 kb. Would it be possible for me to modify web3j in order to enable transactions that are greater than this size?

Here is the stack trace for the error:

`Could not send transaction - org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: okhttp3.internal.http.RealResponseBody@45c7e403
org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: okhttp3.internal.http.RealResponseBody@45c7e403
        at org.web3j.protocol.http.HttpService.performIO(HttpService.java:114)
        at org.web3j.protocol.Service.send(Service.java:31)
        at org.web3j.protocol.core.Request.send(Request.java:71)
        at org.web3j.tx.RawTransactionManager.signAndSend(RawTransactionManager.java:107)
        at org.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:91)
        at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:49)
        at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:87)
        at org.web3j.tx.Contract.executeTransaction(Contract.java:275)
        at org.web3j.tx.Contract.executeTransaction(Contract.java:259)
        at org.web3j.tx.Contract.executeTransaction(Contract.java:253)
        at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:305)
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
        at CertificateDBSC.addNewCertificate(CertificateDBSC.java:230)
        at WebCertificateDB.addNewCertificateFromWeb(WebCertificateDB.java:93)
        at WebCertificateDBTester.addRandomCertificate(WebCertificateDBTester.java:181)
        at WebCertificateDBTester.testAddCertificates(WebCertificateDBTester.java:85)
        at WebCertificateDBTester.main(WebCertificateDBTester.java:51)`

If there is any other information I can provide that would be helpful, please let me know and I will be happy to do my best to update this.

**Comment by fosgate29** [comment]
Does it work using ganache?

**Comment by jefftellew** [comment]
> Does it work using ganache?

@fosgate29 I have not tried ganache, but I can see if I can get it to work and get back to you.
