### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid point

### ISSUE THREAD

**Issue by binny1024** [web3j/web3j#977]
# _Bug_title_
Invalid point

## Steps To Reproduce
when i import mnemonic words 

## Environment

- `Web3j version`:  org.web3j:core:4.2.0-android
-  `Java or Android version`: java11--android 
- `butcoinj` :4.4  api 'org.bitcoinj:bitcoinj-core:0.14.7'
- Operating System

## Additional context
```
 java.lang.IllegalArgumentException: Invalid point
        at org.spongycastle.math.ec.ECAlgorithms.validatePoint(ECAlgorithms.java:193)
W/System.err:     at org.spongycastle.math.ec.AbstractECMultiplier.multiply(AbstractECMultiplier.java:22)
        at org.bitcoinj.core.ECKey.publicPointFromPrivate(ECKey.java:469)
        at org.bitcoinj.crypto.DeterministicKey.<init>(DeterministicKey.java:91)
W/System.err:     at org.bitcoinj.crypto.HDKeyDerivation.createMasterPrivKeyFromBytes(HDKeyDerivation.java:88)
        at org.bitcoinj.crypto.HDKeyDerivation.createMasterPrivateKey(HDKeyDerivation.java:73)
```

**Comment by AlexandrouR** [comment]
Please can you provide example code to in order to reproduce this.

**Comment by klblk** [comment]
Google brought me here. I not use web3j, but i get this crash use spongycastle. Code sample:
```
        val privateKeySpec = getPrivKeySpec(salt, passcode)
        val q = ecSpec.g.multiply(privateKeySpec.d)
        val publicKeySpec = ECPublicKeySpec(q, ecSpec)
        val publicKey = ecdsaKf.generatePublic(publicKeySpec)
```

But environment is very specific: Emulator Android 4.4 and debug application version. Not reproduce on other Emulator version (Android 5.0+). And not reproduce on release app (with R8 and sign release key). I do not have a real device with Android 4.4 for test. 

Maybe something will help:)

**Comment by AlexandrouR** [comment]
Closing this due to inactivity.
