### ISSUE TITLE
org.web3j.protocol.core.filters.FilterException: Invalid request: The method eth_newFilter does not exist/is not available

### ISSUE THREAD

**Issue by ryuheimat** [web3j/web3j#986]

**Comment by AlexandrouR** [comment]
Hey @ryuheimat  what version of web3j are you using and can you please provide a way to reproduce the exception please?

**Comment by ryuheimat** [comment]
I am using this 4.2.0
org.web3j:core:4.2.0

here is exception

org.web```
3j.protocol.core.filters.FilterException: Invalid request: The method eth_newFilter does not exist/is not available
        at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:172)
        at org.web3j.protocol.core.filters.Filter.run(Filter.java:53)
        at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:73)
        at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogFlowable$2(JsonRpc2_0Rx.java:65)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.Flowable.subscribe(Flowable.java:14752)
        at io.reactivex.Flowable.subscribeWith(Flowable.java:14861)
        at com.blockunison.loteo.service.impl.EthService.postConstruct(EthService.java:201)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by ryuheimat** [comment]
i was trying to handle the contract event.

**Comment by AlexandrouR** [comment]
@ryuheimat Take a look at the ethLogFlowable in the JsonRpc2_0Rx class. Take a look [here](https://docs.web3j.io/filters.html#topic-filters-and-evm-events).

**Comment by s-m-sufyian** [comment]
Guys , is this issue resolved ? I am also facing the same issue

**Comment by aran-arunakiri** [comment]
facing same issue
